name = "cenbachillerato"
main = ".open-next/worker.js"
compatibility_date = "2026-05-12"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[observability]
enabled = true

[observability.logs]
enabled = true
