export const GLOSARIO_PFH: Record<string, { t: string; d: string }[]> = {
  "PFH-I": [
    { t: "Argumento", d: "Razón que se ofrece para sostener una afirmación." },
    { t: "Comunidad de diálogo", d: "Grupo que reflexiona en conjunto, escucha y argumenta de forma respetuosa." },
    { t: "Conceptualizar", d: "Formar y precisar las ideas o conceptos con que pensamos algo." },
    { t: "Controversia", d: "Desacuerdo sobre un tema que, encauzado con respeto, abre el diálogo." },
    { t: "Devenir", d: "El cambio constante de las cosas a lo largo del tiempo." },
    { t: "Diálogo filosófico", d: "Conversación reflexiva en la que se construye conocimiento de forma colectiva, con escucha y argumentos." },
    { t: "Epistemología", d: "Rama de la filosofía que estudia el conocimiento: qué podemos conocer y cómo." },
    { t: "Escucha activa", d: "Atender con apertura y respeto lo que el otro dice, para comprenderlo." },
    { t: "Filosofar", d: "Acto de preguntarse, dudar y reflexionar de forma crítica sobre la realidad y la propia existencia." },
    { t: "Filosofía indígena", d: "Pensamiento de los pueblos originarios sobre la vida, la comunidad y la naturaleza." },
    { t: "Filosofía oriental", d: "Tradiciones de pensamiento de Asia, como el budismo, el taoísmo o el confucianismo." },
    { t: "Interculturalidad", d: "Diálogo y respeto entre culturas distintas, reconociendo su valor." },
    { t: "Pensamiento filosófico", d: "Forma de pensar que problematiza lo que se da por evidente y busca razones." },
    { t: "Percepción", d: "Conocimiento que obtenemos a través de los sentidos." },
    { t: "Perspectiva humanista", d: "Enfoque que pone en el centro a la persona, su dignidad y su capacidad de pensar." },
    { t: "Posverdad", d: "Situación en que las emociones y creencias personales influyen más que los hechos en la opinión pública." },
    { t: "Pregunta epistemológica", d: "Pregunta sobre el conocimiento y cómo lo obtenemos." },
    { t: "Pregunta ética", d: "Pregunta sobre lo bueno, lo justo y cómo actuar." },
    { t: "Pregunta filosófica", d: "Cuestión que problematiza lo evidente y busca razones y sentidos profundos." },
    { t: "Pregunta ontológica", d: "Pregunta sobre el ser y la realidad." },
    { t: "Problema filosófico", d: "Cuestión profunda y abierta sobre la realidad, la existencia o el sentido que admite distintas respuestas." },
    { t: "Razón", d: "Capacidad de pensar, comprender y argumentar." },
    { t: "Sentido de la vida", d: "Reflexión sobre el propósito, el valor y la dirección de la existencia." },
    { t: "Tradición filosófica", d: "Conjunto de ideas y formas de pensar desarrolladas por una cultura a lo largo del tiempo." },
    { t: "Validez de una pregunta", d: "Que la pregunta esté bien formulada y sea pertinente para abrir reflexión." },
    { t: "Verdad", d: "Cualidad de una afirmación que corresponde a los hechos o es coherente y fundada." },
  ],
  "PFH-II": [
    { t: "Asombro", d: "Estado de admiración ante la realidad que despierta la pregunta filosófica." },
    { t: "Bioética", d: "Reflexión ética sobre los problemas derivados de la vida, la salud y la biotecnología." },
    { t: "Desigualdad de género", d: "Trato o acceso injusto basado en el género de las personas." },
    { t: "Dilema moral", d: "Situación en la que valores o deberes entran en conflicto y obligan a decidir." },
    { t: "Dualismo", d: "Postura que sostiene la existencia de dos sustancias o principios radicalmente distintos, como mente y cuerpo (Descartes)." },
    { t: "Equidad", d: "Trato justo que reconoce y corrige las desventajas para lograr igualdad real." },
    { t: "Ética", d: "Reflexión filosófica y crítica sobre los fundamentos de la moral y la buena conducta." },
    { t: "Ética del pensamiento", d: "Compromiso de pensar con rigor, honestidad y responsabilidad ante los demás." },
    { t: "Existencia", d: "Modo de ser concreto y real de un ente en el mundo, a diferencia de su mera posibilidad lógica." },
    { t: "Feminismo", d: "Pensamiento y movimiento que busca la igualdad de derechos y cuestiona la desigualdad de género." },
    { t: "Filosofía de la animalidad", d: "Reflexión sobre el estatus moral de los animales y nuestra relación con ellos." },
    { t: "Género", d: "Construcción social y cultural de lo que se considera propio de mujeres y hombres." },
    { t: "Humanismo Mexicano", d: "Perspectiva que pone en el centro la dignidad humana, la justicia y el bien común desde nuestra cultura." },
    { t: "Idealismo", d: "Corriente filosófica que plantea que la realidad es, en última instancia, de naturaleza mental o espiritual." },
    { t: "Inteligencia artificial", d: "Tecnología que simula procesos del pensamiento humano y plantea debates sobre el Ser." },
    { t: "Justicia", d: "Valor que busca dar a cada quien lo que le corresponde y un trato equitativo." },
    { t: "Libertad", d: "Capacidad de decidir y actuar de forma responsable, asumiendo sus consecuencias." },
    { t: "Materialismo", d: "Postura filosófica según la cual solo existe la materia y sus propiedades; la mente y el espíritu son fenómenos materiales." },
    { t: "Metafísica", d: "Rama de la filosofía que estudia la naturaleza última de la realidad, más allá de lo que es observable empíricamente." },
    { t: "Moral", d: "Conjunto de normas, valores y costumbres que orientan la conducta en una comunidad." },
    { t: "Mundo habitable y justo", d: "Horizonte de una convivencia digna, equitativa y respetuosa de la vida." },
    { t: "Ontología", d: "Rama de la filosofía que estudia el ser, la existencia y la realidad en sus aspectos más fundamentales." },
    { t: "Particulares", d: "Entidades únicas, concretas e individuales, a diferencia de los universales abstractos." },
    { t: "Postura ética", d: "Posición razonada sobre lo correcto frente a un problema, como el ambiental." },
    { t: "Praxis transformadora", d: "Unión de reflexión y acción orientada a transformar la realidad para bien." },
    { t: "Problema medioambiental", d: "Daño al entorno que plantea responsabilidades éticas hacia la vida y el futuro." },
    { t: "Realidad y apariencia", d: "Distinción entre lo que las cosas son y cómo se nos muestran a la percepción." },
    { t: "Realismo", d: "Postura filosófica que sostiene que la realidad existe de manera independiente de nuestra mente o percepción." },
    { t: "Ser", d: "Concepto filosófico que designa todo lo que existe, ya sea de manera concreta, abstracta, potencial o actual." },
    { t: "Síntesis filosófica", d: "Integración de distintos saberes y perspectivas para comprender y actuar mejor." },
    { t: "Subjetividad trans", d: "Experiencia y forma de ser de las personas trans, que amplía la comprensión de la identidad." },
    { t: "Universales", d: "En filosofía, propiedades o esencias abstractas que se aplican a múltiples particulares concretos." },
  ],
  "PFH-III": [
    { t: "Abducción", d: "Tipo de razonamiento que infiere la explicación más plausible para un hecho observado. Es el razonamiento del diagnóstico y la investigación científica." },
    { t: "Ad hominem", d: "Falacia que consiste en atacar a la persona que presenta el argumento en lugar de refutar el argumento mismo. Descalifica al emisor en vez de evaluar las razones." },
    { t: "Apelación a la autoridad", d: "Falacia que usa el prestigio o la autoridad de una persona para validar un argumento, en lugar de ofrecer evidencia o razones. Es especialmente problemática cuando la autoridad citada no es experta en el tema." },
    { t: "Argumento válido", d: "Argumento cuya estructura lógica garantiza que si las premisas son verdaderas, la conclusión también lo es. La validez es una propiedad formal, independiente del contenido." },
    { t: "Conclusión", d: "Afirmación que se deriva de las premisas de un argumento y que el argumento pretende demostrar o apoyar." },
    { t: "Deducción", d: "Tipo de razonamiento en el que la conclusión se sigue necesariamente de las premisas: si las premisas son verdaderas, la conclusión no puede ser falsa." },
    { t: "Democracia deliberativa", d: "Modelo democrático que legitima las decisiones colectivas mediante el intercambio público de razones entre ciudadanos, más allá del simple conteo de votos." },
    { t: "Desobediencia civil", d: "Acto político público, no violento y colectivo que viola una ley considerada injusta para interpelar a la autoridad y a la opinión pública." },
    { t: "Diagnóstico filosófico", d: "Primera etapa de la praxis: identificar y analizar el problema desde categorías filosóficas (éticas, políticas, estéticas) antes de diseñar la acción." },
    { t: "Enfoque de las capacidades (Nussbaum)", d: "Marco filosófico que evalúa la justicia de una sociedad según qué capacidades centrales (vida, salud, juego, afiliación política, etc.) pueden ejercer efectivamente sus miembros." },
    { t: "Estado", d: "Organización política que ejerce poder soberano sobre un territorio y una población mediante instituciones jurídicas, coercitivas y administrativas." },
    { t: "Estética", d: "Rama de la filosofía que estudia la belleza, el arte, la sensibilidad y la experiencia que tenemos de lo bello, lo sublime y lo artístico." },
    { t: "Estética latinoamericana", d: "Corriente que analiza las manifestaciones artísticas y culturales de América Latina considerando la colonialidad, la hibridación cultural y las resistencias estéticas propias." },
    { t: "Experiencia estética", d: "Modo de percepción y valoración sensible-afectiva en el que se suspende la utilidad inmediata y se atiende a la forma, el significado o la expresión del objeto." },
    { t: "Falacia", d: "Error en el razonamiento que hace que un argumento parezca válido o convincente sin serlo realmente. Puede ser formal (violar las reglas lógicas) o informal (usar recursos retóricos engañosos)." },
    { t: "Falsa dicotomía", d: "Falacia que presenta solo dos opciones como si fueran las únicas posibles, ocultando otras alternativas intermedias o distintas." },
    { t: "Filosofía comunitaria", d: "Enfoque filosófico que sitúa el diálogo con las comunidades como punto de partida y destino del pensamiento filosófico, reconociendo saberes locales." },
    { t: "Filosofía de la liberación (Dussel)", d: "Corriente latinoamericana que parte de la experiencia de los oprimidos y excluidos para construir una ética y una política alternativas al eurocentrismo." },
    { t: "Hombre de paja", d: "Falacia que consiste en distorsionar o exagerar la postura del oponente para atacar más fácilmente esa versión deformada, en lugar de enfrentar el argumento real." },
    { t: "Inducción", d: "Tipo de razonamiento que va de casos particulares a una conclusión general. A diferencia de la deducción, la conclusión es probable pero no necesariamente verdadera." },
    { t: "Intervención social filosófica", d: "Acción planificada y argumentada filosóficamente que busca transformar una situación problemática en una comunidad específica." },
    { t: "Lo bello (Kant)", d: "Categoría estética que designa aquello cuya contemplación produce un placer desinteresado con pretensión de universalidad, sin mediación de conceptos determinados." },
    { t: "Lo sublime", d: "Experiencia de algo de magnitud o poder tan grande que desborda nuestra capacidad sensible y produce una mezcla de asombro y cierta inquietud." },
    { t: "Mímesis", d: "Concepto griego que significa 'imitación': Platón la usó para criticar el arte (imitación de copias), Aristóteles la revalorizó como representación que produce catarsis." },
    { t: "Pedagogía crítica (Freire)", d: "Propuesta educativa de Paulo Freire que rechaza la 'educación bancaria' y propone un diálogo horizontal entre educador y educando para leer críticamente su mundo." },
    { t: "Pendiente resbaladiza", d: "Falacia que sostiene que una acción o política llevará inevitablemente a consecuencias extremas negativas, sin justificar por qué cada paso de la cadena ocurrirá." },
    { t: "Praxis", d: "Actividad humana consciente, libre y transformadora que integra teoría y práctica para modificar las condiciones de la realidad social." },
    { t: "Premisa", d: "Afirmación o proposición que sirve como punto de partida de un argumento y que se usa para apoyar la conclusión." },
    { t: "Proposición", d: "Enunciado declarativo que puede ser verdadero o falso. Es la unidad mínima del razonamiento lógico." },
    { t: "Silogismo", d: "Forma de razonamiento deductivo compuesto por dos premisas y una conclusión que se deriva de ellas necesariamente. Fue formalizado por Aristóteles." },
    { t: "Tabla de verdad", d: "Herramienta que lista todos los valores posibles de proposiciones simples y calcula el valor de verdad de proposiciones compuestas (∧, ∨, →, ↔)." },
    { t: "Transformación social", d: "Cambio intencional y colectivo en las estructuras, prácticas o valores de una comunidad, orientado por principios filosóficos de justicia, dignidad y bien común." },
    { t: "Velo de ignorancia (Rawls)", d: "Dispositivo conceptual que exige diseñar principios de justicia sin conocer la propia posición social, asegurando imparcialidad." },
  ],
};
