export const GLOSARIO_LC: Record<string, { t: string; d: string }[]> = {
  "LC-I": [
    { t: "Apoyo visual", d: "Recurso como diapositivas o mapas mentales que refuerza el mensaje oral." },
    { t: "Código alfabético", d: "Sistema que relaciona letras con sonidos; es la base, pero no el límite, de leer y escribir." },
    { t: "Conclusión", d: "Parte final que retoma lo más importante y cierra la exposición." },
    { t: "Concordancia", d: "Acuerdo entre los elementos de la oración: sustantivo-adjetivo en género y número, y sujeto-verbo en número y persona." },
    { t: "Conector", d: "Palabra o frase que une ideas dentro de una oración o entre párrafos." },
    { t: "Conector causal", d: "Conector que indica la causa o el motivo de algo." },
    { t: "Conector comparativo", d: "Conector que establece una semejanza o comparación." },
    { t: "Conector de adición", d: "Conector que agrega información a lo dicho." },
    { t: "Desarrollo", d: "Parte central donde se explican los puntos principales del tema." },
    { t: "Dicción", d: "Pronunciación clara y correcta de los sonidos y sílabas." },
    { t: "Elemento paralingüístico", d: "Recurso de la voz que acompaña a las palabras: tono, volumen, ritmo, pausas, énfasis." },
    { t: "Elemento paratextual", d: "Recurso que rodea al texto y ayuda a anticiparlo: título, subtítulos, imágenes, índice." },
    { t: "Empatía", d: "Capacidad de comprender lo que siente o piensa otra persona; la escritura y la lectura la fortalecen." },
    { t: "Entonación", d: "Variación del tono de la voz para expresar preguntas, exclamaciones o afirmaciones." },
    { t: "Escritura", d: "Práctica de crear significado mediante signos para que otra persona lo lea; desarrolla el pensamiento y la comunicación." },
    { t: "Formato", d: "Manera en que se organiza y presenta visualmente el texto." },
    { t: "Idea principal", d: "La información más importante de un párrafo o texto." },
    { t: "Idea secundaria", d: "Información que apoya, ejemplifica o amplía la idea principal." },
    { t: "Introducción", d: "Parte inicial que presenta el tema y capta la atención del público." },
    { t: "Lectura", d: "Práctica de construir significado a partir de las palabras de otra persona; es un diálogo entre contextos." },
    { t: "Oración temática", d: "Oración que expresa la idea principal del párrafo." },
    { t: "Párrafo", d: "Unidad básica de organización del texto que desarrolla una idea principal." },
    { t: "Párrafo argumentativo", d: "Párrafo que defiende una postura con razones para convencer." },
    { t: "Párrafo descriptivo", d: "Párrafo que detalla cómo es una persona, lugar u objeto." },
    { t: "Párrafo narrativo", d: "Párrafo que relata hechos en una secuencia temporal." },
    { t: "Pausa", d: "Silencio breve que permite al oyente procesar lo escuchado." },
    { t: "Planeación", d: "Etapa de definir el tema, investigar y seleccionar la información relevante." },
    { t: "Práctica social", d: "Uso de la lengua en situaciones reales para relacionarnos, aprender, expresarnos y transformar la realidad." },
    { t: "Resumen", d: "Versión breve que reescribe las ideas principales con palabras propias." },
    { t: "Ritmo", d: "Velocidad adecuada de la lectura, ni demasiado rápida ni demasiado lenta." },
    { t: "Soporte", d: "Material o medio físico/electrónico donde aparece el texto." },
    { t: "Subrayado", d: "Estrategia de marcar las palabras o frases clave durante la lectura." },
    { t: "Texto digital", d: "Texto que circula en pantallas y plataformas electrónicas." },
    { t: "Texto informativo", d: "Texto que reporta hechos y datos verificables sobre la realidad." },
    { t: "Texto narrativo", d: "Texto que relata hechos reales o ficticios a lo largo del tiempo." },
  ],
  "LC-II": [
    { t: "Antagonista", d: "Personaje que se opone al protagonista o le crea conflicto." },
    { t: "Borrador", d: "Primera versión de un texto que luego se revisa y corrige." },
    { t: "Caracterización", d: "Conjunto de rasgos físicos, psicológicos y de conducta que definen a un personaje." },
    { t: "Comparación de temas", d: "Analizar cómo distintas narrativas tratan un mismo tema." },
    { t: "Conector textual", d: "Palabra o frase que enlaza ideas y marca su jerarquía u orden." },
    { t: "Conflicto", d: "Problema o situación de tensión que enfrenta el personaje." },
    { t: "Creepypasta", d: "Relato breve de terror que circula y se reescribe en internet." },
    { t: "Descripción", d: "Explicación de cómo son las personas, lugares, objetos o emociones." },
    { t: "Diálogo entre pares", d: "Conversación entre compañeros para compartir ideas y puntos de vista." },
    { t: "Edición", d: "Proceso de mejorar la grabación cortando, ajustando o añadiendo elementos." },
    { t: "Elementos extralingüísticos", d: "Recursos de la voz y el cuerpo que acompañan al mensaje: tono, ritmo, pausas, volumen." },
    { t: "Escenario", d: "Lugar y ambiente donde se desarrolla la historia." },
    { t: "Ficción y realidad", d: "La ficción es lo inventado o imaginado; la realidad es lo que ocurrió de verdad." },
    { t: "Grabación", d: "Registro del audio o video del guion ejecutado." },
    { t: "Guion", d: "Texto creado que organiza lo que se dirá y hará en una producción de audio o video." },
    { t: "Idea principal", d: "Afirmación más importante que el texto hace sobre el tema." },
    { t: "Idea prioritaria", d: "Idea principal de un texto, la más importante que sostiene el mensaje." },
    { t: "Idea secundaria", d: "Idea que complementa o apoya a la idea principal con detalles." },
    { t: "Leyenda", d: "Relato tradicional que mezcla hechos reales con elementos fantásticos." },
    { t: "Mito", d: "Relato tradicional que explica el origen del mundo, dioses o fenómenos." },
    { t: "Narración", d: "Relato de hechos o situaciones que suceden a lo largo del tiempo, con un orden." },
    { t: "Narrativa popular", d: "Relato que nace de la cultura y la tradición de un pueblo o comunidad." },
    { t: "Oralidad", d: "Transmisión de relatos de boca en boca, sin estar escritos." },
    { t: "Organización de ideas", d: "Ordenar lo que se va a escribir antes y durante la redacción." },
    { t: "Personaje secundario", d: "Personaje que acompaña o apoya la historia sin ser el centro." },
    { t: "Pódcast", d: "Formato digital de audio, generalmente por episodios, para contar historias o tratar temas." },
    { t: "Procedimiento narrativo", d: "Recurso o estrategia que se usa para construir una narración." },
    { t: "Protagonista", d: "Personaje principal alrededor del cual gira la historia." },
    { t: "Retroalimentación", d: "Comentarios que señalan aciertos y aspectos a mejorar de un trabajo." },
    { t: "Sentido comunicativo", d: "Propósito o intención con la que se escribe un texto." },
    { t: "Tema", d: "Asunto general del que trata un texto, expresable en pocas palabras." },
    { t: "Texto colaborativo", d: "Texto creado entre varias personas que aportan y acuerdan ideas." },
    { t: "Texto descriptivo", d: "Texto cuyo propósito es mostrar cómo son personas, lugares u objetos." },
    { t: "Texto narrativo", d: "Texto que relata hechos o sucesos en una secuencia temporal." },
    { t: "Tipo de narración", d: "Clase de relato según su contenido: realista, fantástica, histórica o autobiográfica." },
    { t: "Tono narrativo", d: "Actitud o intención emocional con que se cuenta la historia." },
    { t: "Trama", d: "Conjunto ordenado de acontecimientos que forman la historia." },
  ],
  "LC-III": [
    { t: "autoficción", d: "Subgénero que combina elementos autobiográficos reales con recursos ficcionales, borrando los límites entre verdad y ficción." },
    { t: "Barroco", d: "Movimiento literario del siglo XVII caracterizado por el lenguaje ornamental, los contrastes extremos (luz/sombra, vida/muerte) y el tema del desengaño del mundo." },
    { t: "ciencia ficción", d: "Subgénero que especula sobre futuros posibles a partir de avances científicos o tecnológicos y sus consecuencias sociales." },
    { t: "coloquio", d: "Conversación académica estructurada entre participantes que debaten un tema con posiciones argumentadas." },
    { t: "conocimientos previos", d: "Saberes que el lector ya posee y que activa para interpretar un texto nuevo." },
    { t: "contextualización", d: "Situar la obra en su contexto histórico, cultural y literario (movimiento, época, autor)." },
    { t: "cuento", d: "Género narrativo breve, con un único conflicto central, pocos personajes y final generalmente sorpresivo o revelador." },
    { t: "drama", d: "Género teatral escrito para ser representado en escena; incluye diálogo, acotaciones y conflicto dramático." },
    { t: "ejecución", d: "Desarrollo real de la exposición oral siguiendo el plan establecido, con claridad, cohesión y adecuación al público." },
    { t: "ensayo", d: "Texto no ficcional en prosa donde el autor reflexiona, argumenta e interpreta un tema desde su perspectiva." },
    { t: "foro", d: "Espacio de debate abierto, presencial o virtual, donde el público puede intervenir con preguntas y comentarios." },
    { t: "hipérbaton", d: "Alteración del orden sintáctico habitual para lograr énfasis o musicalidad." },
    { t: "hipérbole", d: "Exageración extrema de una cualidad o situación para crear un efecto expresivo intenso." },
    { t: "idea principal", d: "Tesis o valoración central que el reseñista defiende sobre la obra." },
    { t: "idea secundaria", d: "Argumento o ejemplo que apoya y desarrolla la idea principal de la reseña." },
    { t: "inferencia", d: "Conclusión que el lector deduce a partir de pistas en el texto, sin que se diga explícitamente." },
    { t: "intención del autor", d: "Propósito que guía la escritura: informar, persuadir, entretener, reflexionar o criticar." },
    { t: "interpretación", d: "Lectura argumentada y personal de los temas, recursos y sentidos de la obra." },
    { t: "ironía", d: "Expresión que dice lo contrario de lo que se piensa, con intención crítica o humorística." },
    { t: "literaturas del Antropoceno", d: "Narrativas que reflexionan sobre el impacto humano en el planeta, la crisis ecológica y las relaciones entre naturaleza y cultura." },
    { t: "metáfora", d: "Identificación implícita de dos elementos por su semejanza, sin usar 'como'." },
    { t: "Modernismo", d: "Movimiento hispanoamericano de fines del siglo XIX e inicios del XX que renovó el lenguaje literario con musicalidad, preciosismo, cosmopolitismo y una búsqueda de la belleza como valor supremo." },
    { t: "narrador", d: "Voz que cuenta la historia en los textos narrativos; puede ser omnisciente, en primera persona o testigo." },
    { t: "Naturalismo", d: "Variante extrema del Realismo que aplicó métodos científicos (determinismo biológico y social) a la literatura, mostrando cómo el ambiente y la herencia condicionan el comportamiento humano." },
    { t: "Neoclasicismo", d: "Movimiento del siglo XVIII que priorizó la razón, el orden y la claridad sobre la emoción; valoró la función didáctica y moral de la literatura como vehículo ilustrado." },
    { t: "neorrealismo urbano", d: "Subgénero contemporáneo que retrata la vida cotidiana en las ciudades, sus conflictos sociales y personajes marginales." },
    { t: "novela", d: "Género narrativo extenso con personajes complejos, trama desarrollada en múltiples capítulos y universo ficcional detallado." },
    { t: "paráfrasis", d: "Reformulación de las ideas de un texto con las propias palabras, manteniendo el sentido original." },
    { t: "planeación logística", d: "Organización previa que define tema, tiempo, materiales, roles y distribución del espacio para la exposición." },
    { t: "poesía", d: "Género lírico que expresa emociones, experiencias o ideas a través del verso, el ritmo y figuras retóricas." },
    { t: "postura crítica", d: "Juicio argumentado que el lector emite ante las ideas del autor, a favor o en contra, con razones." },
    { t: "prosopopeya", d: "Atribución de cualidades o acciones humanas a seres inanimados, animales o abstracciones." },
    { t: "Realismo", d: "Movimiento de la segunda mitad del siglo XIX que buscó representar objetivamente la realidad social, con crítica a las instituciones y personajes ordinarios como protagonistas." },
    { t: "Realismo mágico", d: "Corriente narrativa latinoamericana del siglo XX que integra elementos maravillosos o sobrenaturales en la realidad cotidiana de manera natural, sin asombro por parte de los personajes." },
    { t: "reseña crítica", d: "Texto que presenta una obra, la describe brevemente, la interpreta y emite una valoración argumentada." },
    { t: "rima y métrica", d: "La rima es la repetición de sonidos al final del verso; la métrica es la medida silábica de cada verso." },
    { t: "Romanticismo", d: "Movimiento del siglo XIX (primera mitad) que exaltó el individualismo, la emoción, la naturaleza sublime y la rebeldía frente al orden racional establecido por la Ilustración." },
    { t: "seguimiento y retroalimentación", d: "Evaluación del proceso antes, durante y después de la exposición para identificar fortalezas y áreas de mejora." },
    { t: "sentido global", d: "Significado general que se construye al interpretar tema, estructura e intención del texto en conjunto." },
    { t: "simposio", d: "Evento académico donde varios especialistas o ponentes presentan perspectivas distintas sobre un mismo tema." },
    { t: "suspenso", d: "Subgénero que genera tensión e incertidumbre mediante la dilación de la resolución y la amenaza constante." },
    { t: "terror", d: "Subgénero que busca provocar miedo mediante lo sobrenatural, lo abyecto o lo psicológico." },
    { t: "valoración", d: "Juicio global sobre la calidad, relevancia o impacto de la obra, justificado con argumentos." },
    { t: "Vanguardias", d: "Conjunto de movimientos artísticos y literarios de 1910-1940 (creacionismo, ultraísmo, surrealismo, futurismo) que rompieron radicalmente con las convenciones formales y temáticas anteriores." },
  ],
};
