export const GLOSARIO_CNEYT: Record<string, { t: string; d: string }[]> = {
  "CNEYT-I": [
    { t: "Aislante", d: "Material que casi no deja pasar la corriente." },
    { t: "Biología", d: "Ciencia que estudia a los seres vivos." },
    { t: "Cambio físico", d: "Transformación sin cambio en la composición química." },
    { t: "Cambio químico", d: "Transformación que produce nuevas sustancias." },
    { t: "Carga eléctrica", d: "Propiedad de las partículas: positiva (protón) o negativa (electrón)." },
    { t: "Catión / Anión", d: "Ion positivo (pierde e⁻) / ion negativo (gana e⁻)." },
    { t: "Ciencia básica y aplicada", d: "La básica busca comprender; la aplicada resuelve problemas concretos." },
    { t: "Cifras significativas", d: "Dígitos de una medida que aportan información confiable." },
    { t: "Compuesto", d: "Sustancia pura de dos o más elementos unidos químicamente." },
    { t: "Concentración", d: "Cantidad de soluto respecto a la disolución (diluida, concentrada, saturada)." },
    { t: "Conductor", d: "Material que deja pasar la corriente por tener electrones libres." },
    { t: "Corriente eléctrica", d: "Movimiento ordenado de cargas (electrones) por un material." },
    { t: "Cuerpo", d: "Porción limitada de materia con forma propia." },
    { t: "Densidad", d: "Masa por unidad de volumen (ρ = m/V)." },
    { t: "Disolución", d: "Mezcla homogénea de soluto disuelto en un disolvente." },
    { t: "Electrón de valencia", d: "Electrón de la última capa; participa en los enlaces." },
    { t: "Electronegatividad", d: "Tendencia de un átomo a atraer electrones del enlace." },
    { t: "Elemento", d: "Sustancia pura de un solo tipo de átomo." },
    { t: "Energía cinética", d: "Energía asociada al movimiento de las partículas." },
    { t: "Energía interna", d: "Suma de la energía cinética y potencial de todas las partículas." },
    { t: "Energía potencial", d: "Energía asociada a las fuerzas de atracción entre partículas." },
    { t: "Enlace iónico / covalente / metálico", d: "Ceder electrones / compartirlos / mar de electrones libres." },
    { t: "Epistemología", d: "Rama que estudia cómo se produce y valida el conocimiento." },
    { t: "Falsabilidad", d: "Propiedad de una hipótesis que permite ponerla a prueba y refutarla." },
    { t: "Física", d: "Ciencia que estudia la materia, la energía y sus interacciones." },
    { t: "Gases de efecto invernadero", d: "Gases como el CO₂ que retienen calor en la atmósfera." },
    { t: "Grupo y periodo", d: "Columna y fila de la tabla periódica." },
    { t: "Hipótesis", d: "Explicación provisional y falsable que se pone a prueba." },
    { t: "Incertidumbre", d: "Margen de error inevitable de toda medición." },
    { t: "Interculturalidad", d: "Reconocimiento del valor de distintos saberes y culturas." },
    { t: "Interdisciplina", d: "Trabajo conjunto de varias ciencias para entender un fenómeno." },
    { t: "Invisibilización", d: "Borrar o ignorar la contribución de personas o grupos." },
    { t: "Ion", d: "Átomo con carga por ganar o perder electrones." },
    { t: "Isótopo", d: "Átomos del mismo elemento con distinto número de neutrones." },
    { t: "Ley de conservación de la materia", d: "La materia no se crea ni se destruye, solo se transforma." },
    { t: "Lise Meitner", d: "Física fundamental en el descubrimiento de la fisión nuclear." },
    { t: "Masa", d: "Cantidad de materia de un cuerpo; se mide en kg." },
    { t: "Materia", d: "Todo lo que tiene masa y ocupa un espacio." },
    { t: "Microplástico", d: "Fragmento de plástico menor a 5 mm que contamina ecosistemas." },
    { t: "Modelo de Bohr", d: "Electrones en niveles de energía definidos alrededor del núcleo." },
    { t: "Modelo de Dalton", d: "El átomo como esfera maciza e indivisible." },
    { t: "Modelo de Schrödinger", d: "Modelo cuántico: orbitales como zonas de probabilidad del electrón." },
    { t: "Molécula", d: "Grupo de átomos unidos por enlaces covalentes." },
    { t: "Naturaleza corpuscular", d: "La materia está formada por partículas (átomos, iones, electrones)." },
    { t: "Número atómico (Z)", d: "Número de protones del núcleo; define el elemento." },
    { t: "Número de masa (A)", d: "Suma de protones y neutrones del núcleo." },
    { t: "Peso", d: "Fuerza con que la gravedad atrae a un cuerpo." },
    { t: "Práctica social", d: "Actividad construida por comunidades humanas con sus contextos e intereses." },
    { t: "Química", d: "Ciencia que estudia la composición de la materia y sus transformaciones." },
    { t: "Replicación", d: "Repetir un experimento para verificar que da los mismos resultados." },
    { t: "Revisión por pares", d: "Evaluación de una investigación por otros expertos antes de publicarse." },
    { t: "Rosalind Franklin", d: "Científica cuya imagen del ADN fue clave para la doble hélice." },
    { t: "Semiconductor", d: "Material que conduce en condiciones controladas." },
    { t: "Sesgo de género", d: "Prejuicio que favorece o perjudica a alguien por su género." },
    { t: "Sistema Internacional (SI)", d: "Conjunto estándar de unidades de medida (m, kg, s, K…)." },
    { t: "Soluto / disolvente", d: "El que se disuelve / el que disuelve." },
    { t: "Sublimación", d: "Cambio directo de sólido a gas." },
    { t: "Sustentabilidad", d: "Uso de recursos sin comprometer a las futuras generaciones." },
    { t: "Tecnología", d: "Aplicación del conocimiento científico para resolver necesidades humanas." },
    { t: "Temperatura", d: "Medida de la energía cinética promedio de las partículas." },
    { t: "Teoría cinética molecular", d: "Modelo que explica la materia como partículas en movimiento constante." },
    { t: "Transformación de energía", d: "Cambio de un tipo de energía a otro." },
    { t: "Variable dependiente", d: "La que se mide como resultado." },
    { t: "Variable independiente", d: "La que se manipula a propósito en el experimento." },
    { t: "Volumen", d: "Espacio que ocupa un cuerpo; se mide en m³ o L." },
  ],
  "CNEYT-II": [
    { t: "Aplicación tecnológica", d: "Uso del conocimiento científico para crear dispositivos o procesos útiles." },
    { t: "Calor", d: "Energía en tránsito entre cuerpos a distinta temperatura; se mide en joules (J)." },
    { t: "Capacidad térmica específica (c)", d: "Energía necesaria para elevar 1 °C la temperatura de 1 kg de sustancia (J/kg·K)." },
    { t: "Cero absoluto", d: "Temperatura más baja posible: 0 K = −273.15 °C; es inalcanzable." },
    { t: "Conclusión científica", d: "Interpretación basada en datos que responde la pregunta de investigación y confirma, rechaza o modifica la hipótesis." },
    { t: "Conducción", d: "Propagación del calor por contacto directo entre partículas, sin que la materia se desplace." },
    { t: "Conductividad térmica (k)", d: "Propiedad que indica qué tan bien un material conduce el calor (W/m·K)." },
    { t: "Conservación de la energía", d: "Principio según el cual la energía no se crea ni se destruye, solo se transforma." },
    { t: "Consumo energético", d: "Cantidad de energía que usan las personas, hogares, industrias o países." },
    { t: "Convección", d: "Propagación del calor por el movimiento de un fluido (líquido o gas)." },
    { t: "Datos cualitativos", d: "Datos descriptivos no numéricos que aportan contexto o características observadas." },
    { t: "Datos cuantitativos", d: "Datos expresados en números y unidades que permiten comparaciones precisas y análisis estadístico." },
    { t: "Eficiencia energética", d: "Lograr el mismo resultado utilizando menos energía." },
    { t: "Energía", d: "Capacidad de un sistema para producir cambios o realizar trabajo." },
    { t: "Energía cinética", d: "Energía que tiene un cuerpo debido a su movimiento." },
    { t: "Energía cinética (Ec)", d: "Energía debida al movimiento; Ec = ½mv²." },
    { t: "Energía eólica", d: "Energía obtenida del viento mediante aerogeneradores." },
    { t: "Energía geotérmica", d: "Energía obtenida del calor interno de la Tierra." },
    { t: "Energía interna (U)", d: "Energía total contenida en un sistema, asociada al movimiento y a las interacciones de sus partículas." },
    { t: "Energía mecánica", d: "Suma de la energía cinética y la energía potencial de un cuerpo." },
    { t: "Energía no renovable", d: "Energía de fuentes que se agotan, como los combustibles fósiles." },
    { t: "Energía potencial", d: "Energía almacenada que depende de la posición o el estado de un cuerpo." },
    { t: "Energía potencial (Ep)", d: "Energía almacenada por la posición; la gravitatoria es Ep = mgh." },
    { t: "Energía química", d: "Energía almacenada en los enlaces de las sustancias." },
    { t: "Energía renovable", d: "Energía que proviene de fuentes que se reponen de forma natural." },
    { t: "Energía solar", d: "Energía obtenida de la radiación del Sol." },
    { t: "Energía total", d: "Suma de todas las formas de energía de un sistema; en un sistema aislado se mantiene constante." },
    { t: "Entalpía (H)", d: "Magnitud que mide el calor intercambiado a presión constante; H = U + PV." },
    { t: "Entropía (S)", d: "Medida del desorden de un sistema o de la dispersión de la energía; tiende a aumentar." },
    { t: "Equilibrio térmico", d: "Estado en que dos cuerpos en contacto alcanzan la misma temperatura." },
    { t: "Fenómeno energético", d: "Suceso natural o artificial en el que intervienen transformaciones de energía." },
    { t: "Fricción", d: "Fuerza que se opone al movimiento entre superficies en contacto y que produce calor." },
    { t: "Fuerza (F)", d: "Acción capaz de cambiar el movimiento o la forma de un cuerpo; se mide en newtons." },
    { t: "Gas ideal", d: "Modelo de gas cuyas partículas no interactúan y cumple la ecuación PV = nRT." },
    { t: "Generador eléctrico", d: "Dispositivo que transforma energía mecánica en energía eléctrica." },
    { t: "Gravedad (g)", d: "Aceleración con que la Tierra atrae a los cuerpos, cercana a 9.8 m/s²." },
    { t: "Hipótesis", d: "Explicación provisional y comprobable que responde a la pregunta de investigación antes de obtener datos." },
    { t: "Impacto ambiental", d: "Efecto que producen las actividades humanas sobre el ambiente." },
    { t: "Joule (J)", d: "Unidad de energía y de trabajo en el Sistema Internacional." },
    { t: "Ley de Fourier", d: "Relación del flujo de calor por conducción: Q/t = k·A·ΔT/L." },
    { t: "Ley de Stefan-Boltzmann", d: "La potencia radiada crece con la cuarta potencia de la temperatura: Q/t = ε·σ·A·T⁴." },
    { t: "Máquina térmica", d: "Dispositivo que transforma calor en trabajo mecánico." },
    { t: "Metodología", d: "Descripción detallada y reproducible del procedimiento, materiales y técnicas usadas en la investigación." },
    { t: "Pregunta de investigación", d: "Interrogante específica, medible y delimitada que orienta todo el proceso científico." },
    { t: "Primera ley", d: "Conservación de la energía en termodinámica: ΔU = Q − W." },
    { t: "Principio cero", d: "Si dos sistemas están en equilibrio térmico con un tercero, lo están entre sí; fundamenta la temperatura." },
    { t: "Proceso endotérmico", d: "Proceso que absorbe calor del entorno." },
    { t: "Proceso exotérmico", d: "Proceso que libera calor al entorno." },
    { t: "Radiación", d: "Propagación del calor por ondas electromagnéticas; no necesita medio material." },
    { t: "Reproducibilidad", d: "Capacidad de obtener resultados similares al repetir el experimento en condiciones iguales; criterio básico de validez científica." },
    { t: "Segunda ley", d: "En todo proceso espontáneo la entropía total del universo aumenta; el calor fluye de lo caliente a lo frío." },
    { t: "Sistema termodinámico", d: "Porción del universo que se estudia, delimitada del entorno por fronteras." },
    { t: "Sustentabilidad", d: "Uso de los recursos que satisface el presente sin comprometer el futuro." },
    { t: "Temperatura", d: "Medida de la agitación o energía cinética promedio de las partículas de un cuerpo." },
    { t: "Trabajo mecánico (W)", d: "Energía transferida cuando una fuerza desplaza un cuerpo; W = F·d." },
    { t: "Transferencia de energía", d: "Paso de energía de un cuerpo o sistema a otro." },
    { t: "Transformación de energía", d: "Cambio de la energía de una forma a otra." },
    { t: "Variable dependiente", d: "Factor que se mide u observa para detectar el efecto de la variable independiente." },
    { t: "Variable independiente", d: "Factor que el investigador manipula o controla deliberadamente para observar su efecto." },
    { t: "Variables controladas", d: "Factores que se mantienen constantes durante el experimento para que no interfieran con los resultados." },
    { t: "Variables de estado", d: "Magnitudes que describen el estado de un sistema: presión, volumen, temperatura y cantidad de sustancia." },
    { t: "Velocidad (v)", d: "Rapidez con dirección con que se mueve un cuerpo; se mide en m/s." },
  ],
  "CNEYT-III": [
    { t: "Agencia ciudadana ambiental", d: "Capacidad y disposición de los ciudadanos para actuar deliberadamente en defensa y mejora del ambiente, a través de acciones individuales, colectivas o políticas." },
    { t: "Aire", d: "Mezcla de gases: ~78% N₂, ~21% O₂ y ~1% otros." },
    { t: "Área Natural Protegida (ANP)", d: "Zona del territorio nacional en la que el Estado restringe actividades humanas para conservar ecosistemas, biodiversidad y servicios ambientales, según la LGEEPA." },
    { t: "Atmósfera", d: "Envoltura gaseosa de la Tierra compuesta principalmente por N₂ (78 %) y O₂ (21 %); regula el clima y protege de la radiación UV." },
    { t: "Atmósfera reductora", d: "Atmósfera sin oxígeno libre, rica en gases que ceden electrones (CH₄, NH₃, H₂)." },
    { t: "Biodiversidad", d: "Variedad de formas de vida en la Tierra en sus tres niveles: diversidad genética (dentro de una especie), diversidad de especies (entre especies) y diversidad de ecosistemas." },
    { t: "Bioma", d: "Gran unidad ecológica definida por el clima y la vegetación dominante que se extiende a escala continental." },
    { t: "Biomagnificación", d: "Aumento progresivo de la concentración de un contaminante al ascender en la cadena trófica." },
    { t: "Biosfera", d: "Zona de la Tierra donde existe vida; integra partes de la atmósfera, hidrosfera y litosfera." },
    { t: "Cambio climático antropogénico", d: "Modificación del clima global causada por actividades humanas que aumentan los gases de efecto invernadero." },
    { t: "Capa de ozono (O₃)", d: "Capa de la estratósfera que filtra la radiación ultravioleta." },
    { t: "Carbono neutral", d: "Estado en que las emisiones de CO₂ de una actividad u organización son compensadas por la captura o reducción equivalente de CO₂, resultando en un balance neto de cero emisiones." },
    { t: "Ciclo biogeoquímico", d: "Movimiento continuo de elementos químicos entre los componentes bióticos y abióticos de la biosfera." },
    { t: "Ciclo del agua", d: "Movimiento continuo del agua por cambios de estado: evaporación, condensación y precipitación." },
    { t: "Ciclo del fósforo", d: "Ciclo sin fase gaseosa significativa; el P se libera por erosión de rocas, pasa al suelo y agua, y es absorbido por plantas y animales." },
    { t: "Ciclo del oxígeno", d: "Circulación del O₂: producido en la fotosíntesis y consumido en la respiración." },
    { t: "Ciencia ciudadana", d: "Participación de ciudadanos no especializados en la recolección y análisis de datos científicos para proyectos de investigación o conservación." },
    { t: "Clima", d: "Patrón promedio del tiempo en una región durante muchos años." },
    { t: "Clorofila", d: "Pigmento verde localizado en los cloroplastos que absorbe principalmente luz roja y azul para la fotosíntesis." },
    { t: "Coeficiente", d: "Número grande delante de una fórmula; indica cuántas moléculas (o moles) de esa sustancia participan." },
    { t: "Componente abiótico", d: "Elemento no vivo del ecosistema: luz solar, temperatura, agua, suelo, nutrientes." },
    { t: "Componente biótico", d: "Todos los organismos vivos que forman parte de un ecosistema." },
    { t: "CONANP", d: "Comisión Nacional de Áreas Naturales Protegidas; organismo federal encargado de administrar y conservar las ANP de México." },
    { t: "Consumidor primario", d: "Herbívoro que se alimenta directamente de los productores." },
    { t: "Consumidor secundario", d: "Organismo que se alimenta de consumidores primarios." },
    { t: "Corredor biológico", d: "Zona de conectividad que une áreas protegidas aisladas para permitir el movimiento de especies y el flujo genético." },
    { t: "Deforestación", d: "Eliminación de la cubierta forestal por tala, incendios o conversión de tierras para agricultura o ganadería." },
    { t: "Denitrificación", d: "Proceso bacteriano que convierte nitratos (NO₃⁻) de nuevo en N₂ gaseoso, completando el ciclo del nitrógeno." },
    { t: "Densidad", d: "Masa por unidad de volumen (masa/volumen)." },
    { t: "Descomponedor", d: "Organismo (hongo, bacteria) que degrada materia orgánica muerta liberando nutrientes inorgánicos." },
    { t: "Diagnóstico ambiental", d: "Evaluación del estado actual de un ecosistema que identifica sus principales problemas, causas y actores involucrados como base para la acción." },
    { t: "Ecosistema", d: "Sistema formado por la comunidad de organismos (biocenosis) y su ambiente físico-químico (biotopo) en interacción." },
    { t: "Ecuación balanceada", d: "Aquella en la que el número de átomos de cada elemento es igual en reactivos y productos." },
    { t: "Ecuación química", d: "Representación escrita de una reacción usando fórmulas, coeficientes, una flecha y simbología." },
    { t: "Efecto invernadero natural", d: "Fenómeno en que la atmósfera retiene calor solar gracias a gases como CO₂, CH₄ y H₂O, manteniendo la temperatura media en ~15 °C." },
    { t: "Especie invasora", d: "Especie introducida fuera de su distribución natural que compite con las nativas y puede alterar el ecosistema." },
    { t: "Especie nativa", d: "Especie que evolucionó en un ecosistema y forma parte de sus relaciones ecológicas naturales." },
    { t: "Estado de agregación (s, l, g, ac)", d: "Simbología entre paréntesis que indica si una sustancia es sólida (s), líquida (l), gaseosa (g) o acuosa (ac, disuelta en agua)." },
    { t: "Estados de agregación", d: "Formas de la materia: sólido, líquido y gas." },
    { t: "Eutrofización", d: "Exceso de nutrientes (N y P) en cuerpos de agua que provoca crecimiento masivo de algas y depleción de oxígeno." },
    { t: "Evapotranspiración", d: "Suma de la evaporación del agua superficial y la transpiración de las plantas; incorpora vapor de agua a la atmósfera." },
    { t: "Fijación de nitrógeno", d: "Conversión del N₂ atmosférico en amonio (NH₄⁺) o nitratos por bacterias fijadoras, haciéndolo asimilable para las plantas." },
    { t: "Flecha de reacción (→)", d: "Símbolo que separa reactivos de productos y se lee «se transforma en» o «produce»." },
    { t: "Fotólisis del agua", d: "Separación de la molécula de agua mediante la energía luminosa en la fase luminosa de la fotosíntesis; libera O₂." },
    { t: "Fotosíntesis", d: "Proceso mediante el cual los organismos autótrofos convierten energía luminosa en energía química almacenada en glucosa." },
    { t: "Gran Oxidación", d: "Periodo en que la fotosíntesis llenó de O₂ océanos y atmósfera." },
    { t: "Hidrosfera", d: "Toda el agua de la Tierra en sus tres estados: océanos, ríos, glaciares, agua subterránea y vapor de agua." },
    { t: "Hipótesis de Oparin-Haldane", d: "Propuesta de que la vida surgió en una atmósfera primitiva reductora." },
    { t: "Huella de carbono", d: "Cantidad total de gases de efecto invernadero emitidos directa o indirectamente por una persona, organización o producto." },
    { t: "Huella ecológica", d: "Indicador que mide cuánta superficie bioproductiva (tierra y agua) necesita una población para generar los recursos que consume y absorber los residuos que produce." },
    { t: "Indicador de impacto", d: "Variable medible que permite evaluar el efecto de una acción de conservación sobre el ecosistema." },
    { t: "Interacción entre subsistemas", d: "Proceso mediante el cual los cuatro subsistemas terrestres se influyen mutuamente de manera continua." },
    { t: "Investigación acción participativa (IAP)", d: "Metodología que combina investigación científica y acción social: los propios afectados participan en identificar el problema, investigar sus causas y diseñar soluciones. Valora el conocimiento local." },
    { t: "Ley de conservación de la materia", d: "Principio de Lavoisier: la materia no se crea ni se destruye, solo se transforma; los átomos de cada elemento se conservan." },
    { t: "LGEEPA", d: "Ley General del Equilibrio Ecológico y la Protección al Ambiente; principal marco jurídico ambiental federal de México (1988)." },
    { t: "Litosfera", d: "Capa sólida externa de la Tierra que incluye la corteza y el manto litosférico superior; dividida en placas tectónicas." },
    { t: "Lluvia ácida", d: "Precipitación con pH bajo causada por la disolución de SO₂ y NOₓ en la atmósfera; daña bosques, suelos y cuerpos de agua." },
    { t: "Objetivos de Desarrollo Sostenible (ODS)", d: "Los 17 objetivos adoptados por la ONU en 2015 como parte de la Agenda 2030, que buscan erradicar la pobreza, proteger el planeta y garantizar la paz y prosperidad para 2030." },
    { t: "Organismos fotosintéticos", d: "Seres que producen materia orgánica y liberan O₂ usando la luz." },
    { t: "Óxido", d: "Compuesto de oxígeno con otro elemento." },
    { t: "Óxido ácido", d: "Óxido de un no metal con el oxígeno; al disolverse da ácidos." },
    { t: "Óxido básico", d: "Óxido de un metal con el oxígeno; al disolverse da bases." },
    { t: "País megadiverso", d: "País que concentra un porcentaje desproporcionadamente alto de la biodiversidad mundial." },
    { t: "Plantas C3", d: "Plantas que fijan el CO₂ directamente en el ciclo de Calvin formando un compuesto de 3 carbonos (3-PGA). Son las más comunes." },
    { t: "Plantas C4", d: "Plantas con mecanismo de pre-fijación del CO₂ en células del mesófilo; más eficientes en climas cálidos y luminosos." },
    { t: "Plantas CAM", d: "Plantas que fijan el CO₂ de noche (estomas cerrados de día) para minimizar la pérdida de agua en ambientes áridos." },
    { t: "Presión atmosférica", d: "Peso del aire por unidad de área; disminuye con la altura." },
    { t: "Productor (autótrofo)", d: "Organismo que sintetiza materia orgánica a partir de fuentes inorgánicas mediante fotosíntesis o quimiosíntesis." },
    { t: "Productos", d: "Las sustancias nuevas que se forman; se escriben a la derecha de la flecha." },
    { t: "Reacción química", d: "Proceso en el que unas sustancias (reactivos) se transforman en otras nuevas (productos) reorganizando sus átomos." },
    { t: "Reacción reversible", d: "Reacción que ocurre en ambos sentidos a la vez; se escribe con flecha doble ⇌." },
    { t: "Reactivos", d: "Las sustancias que entran a la reacción; se escriben a la izquierda de la flecha." },
    { t: "Red trófica", d: "Conjunto de cadenas alimentarias interconectadas que muestra las relaciones de alimentación en un ecosistema." },
    { t: "Regla del 10 %", d: "Solo el 10 % de la energía de un nivel trófico se transfiere al siguiente; el 90 % se pierde como calor." },
    { t: "Reserva de la biosfera", d: "Categoría de ANP con zonas núcleo (protección estricta), amortiguamiento y transición; designadas por la UNESCO dentro del programa MAB." },
    { t: "Resiliencia ecológica", d: "Capacidad de un ecosistema para absorber perturbaciones y reorganizarse mientras experimenta cambios, manteniendo esencialmente la misma estructura, función y biodiversidad." },
    { t: "Restauración ecológica", d: "Proceso de asistir la recuperación de un ecosistema degradado, dañado o destruido para restablecer su estructura, composición y función." },
    { t: "Servicio ecosistémico", d: "Beneficio que los ecosistemas proveen a los seres humanos: provisión (agua, alimentos), regulación (clima, inundaciones), soporte (ciclos de nutrientes) y culturales." },
    { t: "Servicios ecosistémicos", d: "Beneficios que los ecosistemas proveen a las sociedades humanas, clasificados en: servicios de aprovisionamiento (alimentos, agua, madera), servicios de regulación (clima, inundaciones, polinización), servicios culturales y servicios de soporte (ciclos de nutrientes, fotosíntesis)." },
    { t: "Subíndice", d: "Número pequeño dentro de una fórmula; indica cuántos átomos de un elemento hay en una molécula (si no aparece, es 1)." },
    { t: "Sumidero de carbono", d: "Reservorio que absorbe más CO₂ del que libera, reduciendo su concentración en la atmósfera." },
    { t: "Temperatura", d: "Medida de la energía del movimiento de las partículas." },
    { t: "Tiempo atmosférico", d: "Estado de la atmósfera en un lugar y momento concretos." },
  ],
  "CNEYT-IV": [
    { t: "Ácido carboxílico", d: "Compuesto orgánico con el grupo funcional carboxilo (-COOH); es ácido débil que cede un protón H⁺ en solución." },
    { t: "Ácido de Arrhenius", d: "Sustancia que en solución acuosa libera iones hidrógeno (H⁺). Según Brønsted-Lowry, es un donador de protones." },
    { t: "Ácido nucleico", d: "Polímero de nucleótidos (ADN y ARN) que almacena y transmite la información genética y dirige la síntesis de proteínas." },
    { t: "Aditivo alimentario", d: "Sustancia orgánica o inorgánica añadida a los alimentos para mejorar sabor, color, textura o vida útil." },
    { t: "Agente oxidante", d: "Especie que gana electrones (se reduce) y provoca la oxidación de otra." },
    { t: "Agente reductor", d: "Especie que cede electrones (se oxida) y provoca la reducción de otra." },
    { t: "Alcano", d: "Hidrocarburo saturado con fórmula general CₙH₂ₙ₊₂ que solo contiene enlaces simples C-C." },
    { t: "Alcohol", d: "Compuesto orgánico con el grupo funcional hidroxilo (-OH) unido a un carbono saturado." },
    { t: "Alqueno", d: "Hidrocarburo insaturado con al menos un doble enlace C=C; fórmula general CₙH₂ₙ para cadena abierta." },
    { t: "Aminoácido", d: "Unidad estructural de las proteínas; molécula con un grupo amino (-NH₂), un grupo carboxilo (-COOH) y una cadena lateral (R) variable." },
    { t: "ATP (adenosín trifosfato)", d: "La «moneda energética» de la célula; almacena y libera energía al ganar o perder un grupo fosfato." },
    { t: "Balanceo por tanteo", d: "Método para ajustar los coeficientes de una ecuación química igualando el número de átomos de cada elemento en ambos lados de la flecha." },
    { t: "Base de Arrhenius", d: "Sustancia que en solución acuosa libera iones hidróxido (OH⁻). Según Brønsted-Lowry, es un aceptor de protones." },
    { t: "Bioacumulación", d: "Acumulación de un contaminante en los tejidos de un organismo a mayor concentración que en su entorno." },
    { t: "Bioplástico", d: "Polímero derivado de fuentes biológicas renovables (almidón, celulosa, PLA) en lugar de petróleo; generalmente biodegradable." },
    { t: "Buffer (solución tampón)", d: "Solución que resiste cambios bruscos de pH al añadir pequeñas cantidades de ácido o base." },
    { t: "Cadena transportadora de electrones", d: "Serie de proteínas de la membrana mitocondrial donde los electrones del NADH/FADH₂ impulsan la síntesis de la mayor parte del ATP; el O₂ es el aceptor final." },
    { t: "Carbohidrato (glúcido)", d: "Biomolécula compuesta por C, H y O con fórmula general Cₙ(H₂O)ₙ; función principal: fuente de energía rápida y almacenamiento." },
    { t: "Catalizador", d: "Sustancia que acelera ambas reacciones por igual; acerca el equilibrio sin desplazarlo ni cambiar Kc." },
    { t: "Ciclo de Krebs", d: "Etapa mitocondrial que oxida el acetil-CoA liberando CO₂ y cargando NADH y FADH₂." },
    { t: "Cociente de reacción (Q)", d: "Mismo cociente que Kc pero con las concentraciones de cualquier instante; predice el sentido del avance." },
    { t: "Coeficiente estequiométrico", d: "Número entero que se coloca frente a una fórmula química para indicar la proporción molar de esa sustancia en la reacción." },
    { t: "Combustión", d: "Reacción redox rápida de un combustible con oxígeno que libera calor y luz." },
    { t: "Constante de equilibrio (Kc)", d: "Cociente [productos]^coef / [reactivos]^coef en el equilibrio; depende solo de la temperatura." },
    { t: "Contaminante orgánico persistente (COP)", d: "Compuesto orgánico sintético resistente a la degradación, altamente tóxico, que se bioacumula en la cadena trófica." },
    { t: "Economía circular", d: "Modelo económico que busca eliminar residuos manteniendo materiales y productos en uso el mayor tiempo posible mediante reutilización, reparación y reciclaje." },
    { t: "Ecuación química", d: "Representación simbólica de una reacción química que muestra reactivos y productos con sus fórmulas y coeficientes." },
    { t: "Equilibrio dinámico", d: "El equilibrio no es reposo: las moléculas siguen reaccionando en ambos sentidos al mismo ritmo." },
    { t: "Equilibrio químico", d: "Estado en que las velocidades directa e inversa son iguales y las concentraciones permanecen constantes." },
    { t: "Equipo de protección personal (EPP)", d: "Conjunto de dispositivos de seguridad (bata, gafas, guantes, mascarilla) que protegen al experimentador de riesgos químicos o físicos." },
    { t: "Fármaco", d: "Compuesto químico (mayoritariamente orgánico) que interactúa con moléculas biológicas para prevenir, tratar o curar enfermedades." },
    { t: "Fermentación", d: "Proceso metabólico anaerobio en que microorganismos (levaduras, bacterias) transforman azúcares en productos orgánicos útiles: etanol, ácido láctico, ácido acético." },
    { t: "Fermentación alcohólica", d: "El piruvato se convierte en etanol y CO₂, realizada por levaduras." },
    { t: "Fermentación láctica", d: "El piruvato se convierte en ácido láctico (lactato)." },
    { t: "Fotodegradación de plásticos", d: "Fragmentación de polímeros plásticos en partículas más pequeñas por la acción de la radiación ultravioleta del sol." },
    { t: "Glucólisis", d: "Primera etapa, en el citoplasma y sin oxígeno: la glucosa se parte en 2 piruvato con saldo de 2 ATP netos y 2 NADH." },
    { t: "Glucosa", d: "Azúcar de seis carbonos (C₆H₁₂O₆) que sirve de combustible principal de la célula." },
    { t: "Grupo control", d: "Grupo del experimento que no recibe el tratamiento estudiado; sirve como referencia para comparar los resultados." },
    { t: "Grupo funcional", d: "Átomo o conjunto de átomos que determina las propiedades químicas características de una familia de compuestos orgánicos." },
    { t: "Hidrocarburo", d: "Compuesto orgánico formado exclusivamente por carbono e hidrógeno; incluye alcanos, alquenos, alquinos y aromáticos." },
    { t: "Hipótesis", d: "Explicación tentativa y falsable de un fenómeno observado, que puede comprobarse mediante experimentación." },
    { t: "Indicador de pH", d: "Sustancia (natural o sintética) que cambia de color en función del pH de la solución, permitiendo estimar su acidez o basicidad." },
    { t: "Indicador natural de pH", d: "Pigmento vegetal que cambia de color en función del pH; se extrae de plantas como el repollo morado, la Jamaica o la cúrcuma." },
    { t: "Ley de conservación de la masa", d: "Principio que establece que la masa total de los reactivos es igual a la masa total de los productos en cualquier reacción química." },
    { t: "Lípido", d: "Biomolécula apolar formada principalmente por C, H y O; funciones: reserva energética, componente de membranas y señalización." },
    { t: "Metal pesado", d: "Elemento metálico de alta densidad (Pb, Hg, Cd, As) que es tóxico incluso en pequeñas concentraciones y no es biodegradable." },
    { t: "Microplástico", d: "Fragmento de plástico con diámetro menor a 5 mm que persiste en el ambiente acuático y terrestre." },
    { t: "NADH / FADH₂", d: "Transportadores que llevan electrones «cargados» a la cadena transportadora." },
    { t: "Neutralización", d: "Reacción entre un ácido y una base que produce sal y agua, aproximando el pH al valor neutro 7." },
    { t: "Nucleótido", d: "Unidad estructural de los ácidos nucleicos; compuesto por una base nitrogenada, un azúcar (ribosa o desoxirribosa) y un grupo fosfato." },
    { t: "Número de oxidación", d: "Carga aparente de un átomo; sube al oxidarse y baja al reducirse." },
    { t: "Oxidación", d: "Proceso en que una especie pierde electrones; su número de oxidación aumenta." },
    { t: "Óxido-reducción (redox)", d: "Reacción en la que hay transferencia de electrones entre especies." },
    { t: "Petroquímica", d: "Industria que procesa el petróleo y el gas natural para obtener compuestos orgánicos base: plásticos, combustibles, fibras sintéticas, solventes y fertilizantes." },
    { t: "pH", d: "Medida de la concentración de iones hidrógeno (H⁺) en solución, en escala de 0 a 14. pH < 7 ácido, pH = 7 neutro, pH > 7 básico." },
    { t: "Pila galvánica", d: "Dispositivo que aprovecha un redox espontáneo para producir corriente eléctrica." },
    { t: "Piruvato", d: "Molécula de tres carbonos producto de la glucólisis; su destino depende de si hay oxígeno." },
    { t: "Polímero", d: "Macromolécula formada por la unión repetida de unidades pequeñas llamadas monómeros mediante reacciones de polimerización." },
    { t: "Potencial estándar de reducción (E°)", d: "Tendencia de una semirreacción a reducirse, medida en volts frente al electrodo de hidrógeno." },
    { t: "Precipitado", d: "Sólido insoluble que se forma dentro de una solución como resultado de una reacción de doble desplazamiento." },
    { t: "Principio de Le Châtelier", d: "Si se altera un sistema en equilibrio, este se desplaza en el sentido que contrarresta la alteración." },
    { t: "Proceso Haber-Bosch", d: "Síntesis industrial del amoniaco (N₂ + 3 H₂ ⇌ 2 NH₃) a alta presión, base de los fertilizantes." },
    { t: "Producto", d: "Sustancia que se forma como resultado de una reacción química; aparece al lado derecho de la flecha." },
    { t: "Proteína", d: "Polímero de aminoácidos unidos por enlaces peptídicos; funciones: estructura, catálisis (enzimas), transporte, defensa inmune y señalización." },
    { t: "Reacción de combustión", d: "Un combustible reacciona con oxígeno liberando energía en forma de calor y luz. La combustión completa de hidrocarburos produce CO₂ y H₂O." },
    { t: "Reacción de descomposición", d: "Tipo de reacción en que una sola sustancia se divide en dos o más productos más simples. Patrón: AB → A + B." },
    { t: "Reacción de desplazamiento simple", d: "Un elemento desplaza a otro en un compuesto. Patrón: A + BC → AC + B." },
    { t: "Reacción de doble desplazamiento", d: "Dos compuestos iónicos intercambian sus cationes formando dos nuevos compuestos. Patrón: AB + CD → AD + CB." },
    { t: "Reacción de síntesis", d: "Tipo de reacción en que dos o más sustancias se combinan para formar un único compuesto. Patrón: A + B → AB." },
    { t: "Reacción endotérmica / exotérmica", d: "La que absorbe (ΔH>0) o libera (ΔH<0) calor; determina el efecto de la temperatura sobre el equilibrio." },
    { t: "Reacción exotérmica", d: "Reacción que libera energía al entorno; su ΔH es negativa." },
    { t: "Reacción irreversible", d: "La que avanza prácticamente en un solo sentido hasta agotar un reactivo; se escribe con →." },
    { t: "Reacción reversible", d: "La que ocurre en ambos sentidos y puede alcanzar un equilibrio; se escribe con doble flecha ⇌." },
    { t: "Reactivo", d: "Sustancia que se consume en una reacción química; aparece al lado izquierdo de la flecha." },
    { t: "Reducción", d: "Proceso en que una especie gana electrones; su número de oxidación disminuye." },
    { t: "Respiración aerobia", d: "Oxidación completa de la glucosa con oxígeno (glucólisis + Krebs + cadena transportadora); rinde ~38 ATP." },
    { t: "Variable dependiente", d: "Factor que se mide u observa en respuesta a los cambios en la variable independiente." },
    { t: "Variable independiente", d: "Factor que el investigador manipula deliberadamente para observar su efecto en la variable dependiente." },
  ],
  "CNEYT-V": [
    { t: "Amplitud (A)", d: "Desplazamiento máximo de una partícula del medio respecto a su posición de equilibrio. Se mide en metros (m). Determina la energía transportada por la onda (E ∝ A²)." },
    { t: "Brecha digital", d: "Desigualdad en el acceso y uso de tecnologías de la información y comunicación (TIC) entre diferentes grupos sociales, regiones geográficas o países. Tiene implicaciones éticas sobre equidad educativa y oportunidades." },
    { t: "Caída libre", d: "Caso especial de MRUA en dirección vertical con aceleración g ≈ 9.8 m/s² (hacia abajo), sin resistencia del aire. Ecuaciones: v = v₀ + gt; h = v₀t + ½gt²." },
    { t: "Campo magnético y corriente eléctrica", d: "Una corriente eléctrica genera un campo magnético circular alrededor del conductor (ley de Ampère). Un electroimán es un conductor en bobina que intensifica este campo." },
    { t: "Capilaridad", d: "Ascenso (o descenso) de un líquido por tubos muy finos debido a la tensión superficial y la adhesión." },
    { t: "Densidad (ρ)", d: "Masa por unidad de volumen (kg/m³). Decide si un cuerpo flota o se hunde en un fluido." },
    { t: "Dispersión de la luz", d: "Separación de la luz blanca en sus colores componentes porque el índice de refracción depende de la longitud de onda. La luz violeta se refracta más que la roja en el vidrio." },
    { t: "Ecuación de continuidad", d: "El caudal se conserva en una tubería: A₁·v₁ = A₂·v₂. Al estrecharse, el fluido acelera." },
    { t: "Espectro electromagnético", d: "Conjunto de todas las ondas electromagnéticas ordenadas por frecuencia (o longitud de onda). De menor a mayor frecuencia: radio, microondas, infrarrojo, luz visible, ultravioleta, rayos X, rayos gamma. Todas viajan a c ≈ 3 × 10⁸ m/s en el vacío." },
    { t: "Ética tecnológica", d: "Reflexión sobre las consecuencias morales, sociales y ambientales del desarrollo y uso de tecnologías. Incluye preguntas sobre quién se beneficia, quién asume los riesgos, y la responsabilidad de los desarrolladores y gobiernos." },
    { t: "Fisión nuclear", d: "Proceso en el que un núcleo atómico pesado (como ²³⁵U) absorbe un neutrón y se divide en núcleos más ligeros, liberando energía (E = mc²) y más neutrones que pueden provocar una reacción en cadena." },
    { t: "Fluido", d: "Sustancia que fluye y adopta la forma del recipiente que la contiene; incluye líquidos y gases." },
    { t: "Frecuencia (f)", d: "Número de ciclos completos de oscilación por segundo. Unidad: hertz (Hz = 1/s). Relacionada con el período: f = 1/T." },
    { t: "Fricción (rozamiento)", d: "Fuerza de contacto que se opone al movimiento o al intento de movimiento entre dos superficies. Puede ser estática (objeto en reposo) o cinética (objeto en movimiento)." },
    { t: "Fuerza neta (resultante)", d: "Suma vectorial de todas las fuerzas que actúan sobre un cuerpo. Si la fuerza neta es cero, el cuerpo se encuentra en equilibrio (reposo o movimiento rectilíneo uniforme)." },
    { t: "Fusión nuclear", d: "Proceso en el que dos núcleos ligeros (como deuterio y tritio, isótopos del hidrógeno) se fusionan formando un núcleo más pesado y liberando enorme cantidad de energía. Es la fuente de energía del Sol." },
    { t: "Generador eléctrico (alternador)", d: "Dispositivo que convierte energía mecánica en energía eléctrica mediante la inducción electromagnética: una bobina giratoria en un campo magnético genera corriente alterna." },
    { t: "Gráfica posición-tiempo (x-t)", d: "En MRU: línea recta con pendiente = velocidad. En MRUA: parábola. La pendiente de la tangente en un punto indica la velocidad instantánea." },
    { t: "Gráfica velocidad-tiempo (v-t)", d: "En MRU: línea horizontal (v constante, a = 0). En MRUA: línea recta con pendiente = aceleración. El área bajo la curva v-t = desplazamiento." },
    { t: "Gravedad en la superficie (g)", d: "g = GM/R², donde M es la masa del planeta y R su radio. En la Tierra g ≈ 9.8 m/s²; en la Luna g ≈ 1.62 m/s²; en Marte g ≈ 3.72 m/s²." },
    { t: "Índice de refracción (n)", d: "Razón entre la velocidad de la luz en el vacío (c) y su velocidad en el medio: n = c/v. El vacío tiene n = 1. Medios más densos tienen mayor n (aire ≈ 1.00, agua ≈ 1.33, vidrio ≈ 1.5, diamante ≈ 2.42)." },
    { t: "Inercia", d: "Tendencia de un cuerpo a resistir cambios en su estado de movimiento. Un objeto en reposo tiende a permanecer en reposo y uno en movimiento tiende a seguir moviéndose con la misma velocidad y dirección." },
    { t: "Infrarrojo (IR)", d: "Longitudes de onda de 700 nm a 1 mm. Por debajo de la luz roja visible. Aplicaciones: control remoto, visión nocturna, termografía médica, calentadores." },
    { t: "Lentes convergentes y divergentes", d: "Lente convergente (convexa): refracta los rayos hacia el eje óptico; tiene foco real. Aplicaciones: lupas, cámaras, corrección de hipermetropía. Lente divergente (cóncava): dispersa los rayos; tiene foco virtual. Aplicaciones: corrección de miopía." },
    { t: "Ley de Faraday (inducción electromagnética)", d: "Una variación del flujo magnético (Φ_B) a través de un circuito induice una fuerza electromotriz: fem = −ΔΦ_B/Δt. El signo negativo indica que la corriente inducida se opone al cambio (ley de Lenz)." },
    { t: "Ley de gravitación universal (Newton)", d: "F = G·m₁·m₂/r², donde F es la fuerza gravitacional, G ≈ 6.674 × 10⁻¹¹ N·m²/kg², m₁ y m₂ son las masas y r es la distancia entre sus centros. La fuerza es siempre atractiva." },
    { t: "Longitud de onda (λ)", d: "Distancia entre dos puntos consecutivos en igual fase (por ejemplo, entre dos crestas o dos valles consecutivos). Unidad: metro (m)." },
    { t: "Luz visible", d: "Franja del espectro detectable por el ojo humano: longitudes de onda de 400 nm (violeta) a 700 nm (rojo). Incluye todos los colores del arcoíris: ROYGBIV." },
    { t: "Motor eléctrico", d: "Dispositivo que convierte energía eléctrica en energía mecánica usando la fuerza que ejerce un campo magnético sobre un conductor que lleva corriente (fuerza de Lorentz: F = I·L × B)." },
    { t: "Movimiento rectilíneo uniforme (MRU)", d: "Movimiento en línea recta con velocidad constante y aceleración cero. La posición varía linealmente con el tiempo: x = x₀ + vt." },
    { t: "Movimiento rectilíneo uniformemente acelerado (MRUA)", d: "Movimiento en línea recta con aceleración constante. Ecuaciones: v = v₀ + at; x = x₀ + v₀t + ½at²; v² = v₀² + 2a(x − x₀)." },
    { t: "Ondas de radio y microondas", d: "Ondas de radio (f < 300 MHz, λ > 1 m): telecomunicaciones, radiodifusión AM/FM, WiFi. Microondas (300 MHz - 300 GHz): hornos, radar, telefonía móvil, satélites GPS." },
    { t: "Ondas transversales y longitudinales", d: "Transversales: las oscilaciones son perpendiculares a la dirección de propagación (ej. ondas en una cuerda, ondas de luz). Longitudinales: las oscilaciones son paralelas a la dirección de propagación (ej. sonido, ondas sísmicas P)." },
    { t: "Período (T)", d: "Tiempo que tarda una partícula en completar un ciclo completo de oscilación. Unidad: segundo (s). T = 1/f." },
    { t: "Peso y masa", d: "La masa (kg) es la cantidad de materia de un cuerpo; el peso (N) es la fuerza gravitacional que actúa sobre ella: W = mg, donde g ≈ 9.8 m/s² en la superficie terrestre." },
    { t: "Presión (P)", d: "Fuerza por unidad de área, en pascales (Pa = N/m²)." },
    { t: "Primera ley de Kepler (órbitas elípticas)", d: "Cada planeta se mueve en una órbita elíptica alrededor del Sol, con el Sol situado en uno de los dos focos de la elipse." },
    { t: "Principio de Arquímedes", d: "Todo cuerpo sumergido recibe un empuje hacia arriba igual al peso del fluido que desaloja: E = ρ_fluido·V_sumergido·g." },
    { t: "Principio de Bernoulli", d: "A lo largo de una línea de corriente, P + ½ρv² + ρgh es constante: donde la velocidad sube, la presión baja." },
    { t: "Principio de Pascal", d: "Un aumento de presión aplicado a un fluido confinado se transmite por igual a todos sus puntos." },
    { t: "Principio de precaución", d: "Principio ético y político según el cual ante la incertidumbre sobre riesgos de daño grave o irreversible (ambiental, de salud), se deben tomar medidas preventivas aunque no haya certeza científica absoluta." },
    { t: "Radiactividad y residuos nucleares", d: "Los materiales radiactivos emiten partículas o radiación al desintegrarse. Los residuos nucleares de alta actividad pueden permanecer peligrosos durante miles de años, representando un desafío ético de almacenamiento seguro para generaciones futuras." },
    { t: "Rayos gamma", d: "Mayor frecuencia y energía del espectro (f > 10¹⁹ Hz, λ < 0.01 nm). Origen: núcleos radiactivos. Aplicaciones: radioterapia oncológica, gammagrafía, esterilización médica." },
    { t: "Reflexión de la luz", d: "Cambio de dirección de la luz al rebotar sobre una superficie. Ley: el ángulo de incidencia θᵢ es igual al ángulo de reflexión θᵣ (ambos medidos respecto a la normal). Reflexión especular: superficie lisa. Reflexión difusa: superficie rugosa." },
    { t: "Reflexión total interna", d: "Cuando la luz viaja de un medio más denso a uno menos denso y el ángulo de incidencia supera el ángulo crítico, la luz se refleja totalmente sin refractarse. Base de las fibras ópticas." },
    { t: "Refracción de la luz", d: "Cambio de dirección y velocidad de la luz al pasar de un medio a otro con diferente índice de refracción. Ley de Snell: n₁·sen(θ₁) = n₂·sen(θ₂)." },
    { t: "Segunda ley de Kepler (áreas iguales)", d: "La línea que une un planeta con el Sol barre áreas iguales en tiempos iguales. Implica que los planetas se mueven más rápido cerca del Sol (perihelio) y más lento lejos (afelio)." },
    { t: "Segunda ley de Newton (F = ma)", d: "La fuerza neta sobre un cuerpo es igual al producto de su masa por su aceleración: F = ma. La aceleración es directamente proporcional a F e inversamente proporcional a m." },
    { t: "Tecnologías cotidianas del electromagnetismo", d: "Inducción electromagnética aplicada a: cargadores inalámbricos (inducción), tarjetas de transporte (RFID), cocinas de inducción, bocinas, micrófonos, discos duros." },
    { t: "Tensión superficial", d: "Fuerza que mantiene cohesionada la superficie de un líquido, como una membrana elástica." },
    { t: "Tercera ley de Kepler (períodos y distancias)", d: "El cuadrado del período orbital T es proporcional al cubo del semieje mayor a de la órbita: T² ∝ a³. Para el sistema solar: T²/a³ = constante." },
    { t: "Tercera ley de Newton (acción y reacción)", d: "Por cada fuerza de acción que un cuerpo A ejerce sobre un cuerpo B, existe una fuerza de reacción de B sobre A, igual en magnitud, misma línea de acción y sentido contrario." },
    { t: "Transformador eléctrico", d: "Dispositivo que aumenta (transformador elevador) o disminuye (reductor) la tensión de CA usando inducción mutua entre dos bobinas. Relación: V₁/V₂ = N₁/N₂, donde N es el número de espiras." },
    { t: "Ultravioleta (UV) y rayos X", d: "UV (10-400 nm): produce vitamina D en la piel, esteriliza superficies, causa quemaduras. Rayos X (0.01-10 nm): diagnóstico médico (radiografías), seguridad aeroportuaria." },
    { t: "Velocidad de escape", d: "Velocidad mínima que debe tener un objeto para escapar del campo gravitacional de un cuerpo: v_esc = √(2GM/R). Para la Tierra, v_esc ≈ 11.2 km/s." },
    { t: "Velocidad de propagación (v = f·λ)", d: "Rapidez a la que la energía de la onda se desplaza por el medio. v = f·λ. Depende de las propiedades del medio, no de la amplitud ni la fuente." },
    { t: "Velocidad media", d: "Razón entre el desplazamiento total y el tiempo transcurrido: v_med = Δx/Δt. No indica cómo varía la velocidad instante a instante." },
    { t: "Viscosidad", d: "Medida de la resistencia interna de un fluido a fluir (Pa·s)." },
  ],
  "CNEYT-VI": [
    { t: "Alelos y locus génico", d: "Un gen ocupa una posición específica en el cromosoma llamada locus. Los alelos son formas alternativas del mismo gen. Un individuo diploide tiene dos alelos por locus (uno de cada progenitor): puede ser homocigoto (AA o aa) o heterocigoto (Aa)." },
    { t: "Anton van Leeuwenhoek", d: "Holandés que observó por primera vez microorganismos vivos." },
    { t: "Aparato de Golgi", d: "Sistema de sacos membranosos apilados (cisternas) que recibe proteínas del RE, las modifica (glucosilación, corte), clasifica y empaqueta en vesículas para enviarlas a su destino: membrana plasmática, lisosomas o secreción." },
    { t: "Bioprospección y propiedad intelectual en biotecnología", d: "La bioprospección es la búsqueda de organismos con propiedades útiles para biotecnología. Genera debates éticos sobre: propiedad de los recursos genéticos de países megadiversos, biopiratería (patentar conocimiento indígena sin compensación) y el Protocolo de Nagoya (acceso y beneficios compartidos)." },
    { t: "Cadena de transporte de electrones y fosforilación oxidativa", d: "Tercera etapa. Ocurre en la membrana interna mitocondrial. Los electrones de NADH y FADH₂ pasan por proteínas (complejos I-IV) que bombean H⁺ al espacio intermembranoso. El flujo de H⁺ de regreso a través de la ATP sintasa genera ~32-34 ATP. El O₂ es el aceptor final de electrones, formando H₂O." },
    { t: "Célula", d: "Unidad fundamental (estructural, funcional y de origen) de todos los seres vivos." },
    { t: "Ciclo de Calvin (fase oscura / fase de fijación de CO₂)", d: "Ocurre en el estroma del cloroplasto. Usa el ATP y NADPH de la fase lumínica. La enzima RuBisCO fija CO₂ en la ribulosa 1,5-bisfosfato (RuBP) (5C). Por cada 3 CO₂ fijados se produce 1 gliceraldehído-3-fosfato (G3P), precursor de glucosa y otros azúcares." },
    { t: "Ciclo de Krebs (ciclo del ácido cítrico)", d: "Segunda etapa de la respiración aerobia. Ocurre en la matriz mitocondrial. El piruvato se convierte en acetil-CoA (2C) que ingresa al ciclo, produciendo por cada vuelta: 3 NADH, 1 FADH₂, 1 GTP (≈1 ATP) y 2 CO₂. Por glucosa: 2 vueltas = 6 NADH, 2 FADH₂, 2 ATP y 4 CO₂." },
    { t: "Clonación", d: "Proceso que produce copias genéticamente idénticas. Clonación molecular: amplifica fragmentos de ADN. Clonación reproductiva: produce un organismo con el mismo genoma que el donante (ej: Dolly, 1996, por transferencia nuclear de células somáticas). Clonación terapéutica: produce células madre embrionarias para medicina regenerativa, sin propósito reproductivo." },
    { t: "Cloroplasto", d: "Organelo exclusivo de células vegetales y algas con doble membrana y un sistema interno de tilacoides apilados (grana) en el estroma. Es el sitio de la fotosíntesis: convierte luz solar, CO₂ y H₂O en glucosa y O₂." },
    { t: "Coacervados y protocélulas", d: "Los coacervados son agregados esféricos de polímeros en solución acuosa que pueden concentrar moléculas y llevar a cabo reacciones sencillas. Representan un modelo de protocélula: estructura precelular que precedió a las células verdaderas." },
    { t: "Código genético y codones", d: "Lenguaje de tripletes de bases del ARNm que codifican aminoácidos. 64 codones posibles (4³) codifican 20 aminoácidos más 3 codones de parada. Es universal (mismo en casi todos los seres vivos), degenerado (varios codones por aminoácido) y sin solapamiento." },
    { t: "CRISPR-Cas9", d: "Sistema de edición génica derivado de un mecanismo inmune bacteriano contra fagos. Un ARN guía (sgRNA) lleva a la proteína Cas9 a una secuencia específica del genoma donde hace un corte de doble cadena. La célula repara el corte por NHEJ (deleción/mutación) o HDR (inserción precisa). Más rápido, barato y preciso que técnicas anteriores." },
    { t: "Cromátida hermana", d: "Cada una de las dos copias idénticas de un cromosoma duplicado, unidas por el centrómero." },
    { t: "Cromosoma", d: "Estructura de ADN muy compactado que porta los genes; en humanos hay 46 (23 pares)." },
    { t: "Cromosomas homólogos", d: "El par de cromosomas con los mismos genes, uno de origen materno y otro paterno." },
    { t: "Crossing over", d: "Intercambio de fragmentos de ADN entre cromátidas de homólogos durante la Profase I." },
    { t: "Deriva génica", d: "Cambio aleatorio en la frecuencia de alelos en una población, especialmente pronunciado en poblaciones pequeñas. No es adaptativo; puede fijar alelos neutros o perjudiciales. Incluye el efecto fundador (nueva población a partir de pocos individuos) y el cuello de botella (reducción drástica del tamaño poblacional)." },
    { t: "Diferencias clave procariota vs eucariota", d: "Procariota: sin núcleo membranoso, ADN circular en nucleoide, ribosomas 70S, sin organelos membranosos, tamaño ~1-10 µm. Eucariota: núcleo con envoltura nuclear, ADN lineal en cromosomas, ribosomas 80S, organelos especializados, tamaño ~10-100 µm." },
    { t: "Diploide (2n)", d: "Célula con dos juegos completos de cromosomas, uno de cada progenitor." },
    { t: "Dogma central de la biología molecular", d: "Flujo de información genética propuesto por Francis Crick (1958): ADN → ARN → Proteína. La replicación reproduce el ADN; la transcripción produce ARN; la traducción produce proteínas. Las retrovirus (VIH) añaden transcripción inversa: ARN → ADN." },
    { t: "Dominancia incompleta y codominancia", d: "Dominancia incompleta: el heterocigoto presenta fenotipo intermedio (ej: rojo × blanco → rosa). Codominancia: ambos alelos se expresan simultáneamente sin mezcla (ej: grupo sanguíneo AB: se expresan antígenos A y B)." },
    { t: "Edición de línea germinal vs somática", d: "Edición somática: modifica células del cuerpo del individuo; los cambios no son heredables; ejemplos en ensayos clínicos para cáncer y enfermedades genéticas. Edición germinal: modifica embriones, óvulos o espermatozoides; los cambios se heredan indefinidamente. Caso He Jiankui (2018): primer bebé CRISPR, generó condena científica y ética internacional." },
    { t: "Especiación", d: "Proceso por el cual surgen nuevas especies. Especiación alopátrica: separación geográfica impide el flujo génico entre poblaciones que divergen hasta no poder reproducirse. Especiación simpátrica: aislamiento reproductivo dentro del mismo territorio (poliploidía, selección disruptiva)." },
    { t: "Estructura de la doble hélice del ADN", d: "El ADN es un polímero de desoxirribonucleótidos formado por dos cadenas antiparalelas enrolladas en hélice. Las bases nitrogenadas (A, T, G, C) se complementan: A-T (2 H) y G-C (3 H). El esqueleto exterior es de fosfato-desoxirribosa." },
    { t: "Estructuras homólogas y analogías", d: "Homólogas: misma estructura anatómica derivada del mismo ancestro, adaptada a funciones distintas (ej: extremidad anterior de humano, ballena, murciélago). Son evidencia de ancestro común. Análogas: funciones similares pero origen evolutivo independiente (convergencia); ej: ala de ave vs ala de insecto." },
    { t: "Evidencia fósil de la evolución", d: "El registro fósil muestra la cronología de aparición de grupos biológicos, formas de transición y extinciones. Las dataciones radiométricas permiten establecer la edad de los fósiles. Las series de fósiles de equinos, cetáceos (de ungulados a ballenas) y homínidos son secuencias evolutivas documentadas." },
    { t: "Experimento de Miller-Urey (1953)", d: "Stanley Miller y Harold Urey simularon la atmósfera primitiva (CH₄, NH₃, H₂, H₂O) y aplicaron descargas eléctricas. Tras una semana obtuvieron más de 20 aminoácidos distintos, confirmando la síntesis abiótica de moléculas orgánicas." },
    { t: "Fase lumínica de la fotosíntesis", d: "Ocurre en las membranas de los tilacoides del cloroplasto. La luz solar excita la clorofila; los fotosistemas II y I captan fotones. El agua se fotoliza (H₂O → O₂ + H⁺ + e⁻) y los electrones energizados generan ATP (fotofosforilación) y NADPH. El O₂ se libera." },
    { t: "Fermentación", d: "Proceso anaeróbico que regenera el NAD⁺ a partir del NADH para que la glucólisis continúe. Fermentación láctica: piruvato → lactato (músculo, bacterias lácticas). Fermentación alcohólica: piruvato → etanol + CO₂ (levaduras). Solo produce 2 ATP por glucosa." },
    { t: "Gameto", d: "Célula sexual haploide (óvulo o espermatozoide) que se une en la fecundación." },
    { t: "Generación espontánea (refutada)", d: "Teoría antigua que afirmaba que los seres vivos podían surgir directamente de materia inerte sin progenitores. Refutada definitivamente por Louis Pasteur en 1859 con sus matraces de cuello de cisne." },
    { t: "Glucólisis", d: "Primera etapa de la respiración celular. Ocurre en el citosol. Convierte 1 glucosa (6C) en 2 piruvatos (3C) con ganancia neta de 2 ATP y 2 NADH. No requiere oxígeno; es la única vía energética en anaerobios estrictos." },
    { t: "Haploide (n)", d: "Célula con un solo juego de cromosomas; es el estado de los gametos." },
    { t: "Herencia ligada al sexo", d: "Herencia de genes ubicados en el cromosoma X. Los hombres (XY) expresan cualquier alelo recesivo ligado al X porque solo tienen una copia. Las mujeres (XX) necesitan dos copias recesivas para expresar el rasgo. Ejemplos: hemofilia A, daltonismo." },
    { t: "Herencia poligénica", d: "Rasgos determinados por la interacción de múltiples genes (cada uno con efecto pequeño y aditivo). Producen variación continua con distribución normal en la población. También influye el ambiente (herencia multifactorial)." },
    { t: "Hipótesis de Oparin-Haldane (sopa primordial)", d: "Propone que en la Tierra primitiva (hace ~4000 millones de años), la atmósfera sin oxígeno libre y con H₂, CH₄, NH₃ y H₂O permitió la síntesis abiótica de moléculas orgánicas que se acumularon en los océanos formando una 'sopa primordial'." },
    { t: "Hipótesis del mundo de ARN", d: "Postula que en el origen de la vida el ARN actuó tanto como molécula de almacenamiento de información (como el ADN hoy) y como catalizador (como las proteínas). Las ribozimas (ARN catalítico) son evidencia de esa capacidad dual." },
    { t: "Matthias Schleiden", d: "Botánico que concluyó (1838) que todas las plantas están hechas de células." },
    { t: "Meiosis", d: "Dos divisiones sucesivas que producen cuatro células haploides distintas (2n → n)." },
    { t: "Microscopio", d: "Instrumento que aumenta la imagen de objetos diminutos, invisibles al ojo." },
    { t: "Mitocondria", d: "Organelo con doble membrana (externa lisa e interna plegada en crestas) donde se lleva a cabo la respiración celular aerobia. Produce la mayor parte del ATP celular mediante la cadena de transporte de electrones." },
    { t: "Mitosis", d: "División celular que produce dos células hijas idénticas a la madre (2n → 2n)." },
    { t: "Mutación cromosómica", d: "Cambio en la estructura o número de cromosomas. Estructurales: deleción (pérdida de segmento), duplicación, inversión, translocación. Numéricas: aneuploidía (pérdida o ganancia de cromosomas, ej: trisomía 21 = síndrome de Down) o poliploidía." },
    { t: "Mutación génica puntual", d: "Cambio en uno o pocos pares de bases del ADN. Tipos: (1) Sustitución: una base se reemplaza por otra; puede ser sinónima (sin cambio de aminoácido), missense (cambia aminoácido) o nonsense (genera codón de parada prematuro). (2) Inserción/deleción de 1-2 bases: causa desplazamiento del marco de lectura (frameshift), alterando todos los aminoácidos siguientes." },
    { t: "Mutaciones germinales vs somáticas", d: "Germinales: ocurren en células de la línea germinal (gametos); son heredables y afectan a toda la descendencia. Somáticas: ocurren en células del cuerpo del individuo; no son heredables, pero pueden causar cáncer si afectan genes reguladores del ciclo celular (proto-oncogenes, genes supresores de tumor)." },
    { t: "Mutágenos físicos, químicos y biológicos", d: "Agentes que aumentan la tasa de mutación. Físicos: radiación UV (dímeros de timina), rayos X y gamma (roturas de doble cadena). Químicos: benzopirenos del humo de tabaco, aflatoxinas, agentes alquilantes. Biológicos: virus que integran su ADN en el genoma (VPH, retrovirus)." },
    { t: "Núcleo celular", d: "Organelo rodeado por la envoltura nuclear (doble membrana con poros). Contiene el ADN genómico organizado en cromosomas y es el sitio de la replicación del ADN y la transcripción del ARN." },
    { t: "Organismos genéticamente modificados (OGM/transgénicos)", d: "Organismos a los que se les ha transferido material genético exógeno mediante técnicas de ADN recombinante (plásmidos, vectores virales, biobalística). Aplicaciones: agricultura (resistencia a herbicidas, plagas, sequía), medicina (insulina, vacunas, factores de coagulación), industria (enzimas para alimentos, biocombustibles)." },
    { t: "Panspermia", d: "Hipótesis que propone que la vida o sus precursores orgánicos llegaron a la Tierra desde el espacio exterior a través de meteoritos, cometas o polvo cósmico. No explica el origen último de la vida, solo su llegada." },
    { t: "Primera ley de Mendel: segregación", d: "Los dos alelos de un gen se separan (segregan) durante la meiosis y cada gameto recibe solo uno. Al fecundarse, el cigoto recibve un alelo de cada progenitor. Esto explica las proporciones fenotípicas 3:1 en F2 de cruzamientos monohíbridos." },
    { t: "Principios de bioética", d: "Marco para evaluar intervenciones biotecnológicas: (1) Beneficencia: buscar el mayor beneficio. (2) No maleficencia: evitar daños. (3) Justicia: acceso equitativo a los beneficios. (4) Autonomía: consentimiento informado. En biotecnología también aplican: precaución (actuar con cuidado ante incertidumbre), transparencia y soberanía alimentaria." },
    { t: "Recombinación genética", d: "Nuevas combinaciones de genes que surgen por crossing over y distribución independiente." },
    { t: "Reparación del ADN", d: "Las células poseen sistemas de reparación para corregir errores de replicación y daños al ADN: (1) Reparación por escisión de nucleótidos (NER): elimina dímeros de timina y lesiones voluminosas. (2) Reparación de emparejamientos erróneos (MMR). (3) Unión de extremos no homólogos (NHEJ) para roturas de doble cadena. Fallos en estos sistemas aumentan el riesgo de cáncer." },
    { t: "Replicación del ADN (semiconservativa)", d: "Proceso por el cual el ADN se duplica antes de la división celular. La ADN helicasa separa las cadenas; la ADN polimerasa III sintetiza la nueva cadena en dirección 5'→3' usando cada cadena como molde. Resultado: dos moléculas hijas idénticas, cada una con una cadena parental." },
    { t: "Retículo endoplasmático (RE)", d: "Red de membranas continua con el núcleo. El RE rugoso (con ribosomas) sintetiza y procesa proteínas de secreción o de membrana. El RE liso (sin ribosomas) sintetiza lípidos y desintoxica compuestos." },
    { t: "Robert Hooke", d: "Científico inglés que en 1665 observó el corcho y acuñó la palabra «célula»." },
    { t: "Rudolf Virchow", d: "Médico que afirmó (1855) que toda célula proviene de otra célula." },
    { t: "Segunda ley de Mendel: surtido independiente", d: "Para genes en cromosomas distintos, los alelos de un gen se distribuyen en los gametos independientemente de los alelos de otro gen. Esto produce proporciones 9:3:3:1 en cruzamientos dihíbridos (F2)." },
    { t: "Selección natural (Darwin-Wallace)", d: "Mecanismo evolutivo que actúa sobre la variación heredable en una población. Los individuos con variaciones que aumentan su supervivencia y reproducción en el ambiente actual dejan más descendencia, por lo que esas variaciones se vuelven más frecuentes en la siguiente generación." },
    { t: "Teoría celular", d: "Principio de que la célula es la unidad fundamental de la vida." },
    { t: "Theodor Schwann", d: "Zoólogo que extendió (1839) la idea celular a los animales." },
    { t: "Tipos de selección natural", d: "Selección estabilizadora: favorece fenotipos intermedios, reduce la varianza (ej: peso al nacer en humanos). Selección direccional: favorece un extremo del rango fenotípico (ej: resistencia a antibióticos). Selección disruptiva: favorece ambos extremos, puede llevar a especiación." },
    { t: "Traducción", d: "Síntesis de proteínas en el ribosoma usando el ARNm como molde. Los ARNt (con anticodón complementario al codón) llevan aminoácidos específicos. El ribosoma cataliza la formación de enlaces peptídicos. Termina al encontrar un codón de parada." },
    { t: "Transcripción", d: "Síntesis de ARNm a partir del ADN. La ARN polimerasa se une al promotor, separa el ADN y sintetiza el ARNm complementario en dirección 5'→3'. En eucariotas ocurre en el núcleo; el ARNm se procesa (capuchón 5', cola poli-A, eliminación de intrones) antes de salir al citoplasma." },
    { t: "Unidad de origen", d: "Toda célula proviene de otra célula preexistente." },
    { t: "Unidad estructural", d: "Todos los seres vivos están formados por una o más células." },
    { t: "Variabilidad genética y evolución", d: "Las mutaciones introducen nuevos alelos en las poblaciones; la recombinación durante la meiosis crea nuevas combinaciones de alelos. Ambos procesos generan diversidad fenotípica sobre la que actúa la selección natural, la deriva génica y el flujo génico, impulsando la evolución." },
  ],
};
