export const GLOSARIO_CS: Record<string, { t: string; d: string }[]> = {
  "CS-I": [
    { t: "Cambio social", d: "Transformación de normas e instituciones a lo largo del tiempo." },
    { t: "Captura del Estado", d: "Cuando intereses privados controlan al Estado en su beneficio." },
    { t: "Ciudadanía digital", d: "Derechos y responsabilidades en el entorno virtual." },
    { t: "Ciudadanía formal", d: "Estatus jurídico reconocido por el Estado (votar, identidad, servicios)." },
    { t: "Ciudadanía sustantiva", d: "Capacidad real de ejercer los derechos que se tienen formalmente." },
    { t: "Construcción histórica", d: "Algo que no es natural sino producto de una época y contexto." },
    { t: "Democracia procedimental", d: "La que garantiza procesos como las elecciones y el voto." },
    { t: "Democracia sustantiva", d: "La que asegura participación real e igualdad de condiciones." },
    { t: "Derecho de petición", d: "Derecho a dirigir solicitudes a la autoridad y recibir respuesta." },
    { t: "Desobediencia civil", d: "Incumplimiento pacífico y consciente de una ley injusta." },
    { t: "Discriminación", d: "Trato injusto a una persona o grupo por su diferencia." },
    { t: "Diversidad", d: "Pluralidad de identidades: étnica, cultural, de género, capacidad y clase." },
    { t: "División de poderes", d: "Separación de funciones en Ejecutivo, Legislativo y Judicial para evitar abusos." },
    { t: "Estado", d: "Organización política de una sociedad con territorio, población y gobierno." },
    { t: "Impunidad", d: "Falta de castigo a quien comete un delito." },
    { t: "Inclusión", d: "Garantizar que todos los grupos participen en igualdad." },
    { t: "Institución", d: "Conjunto estable de normas y organizaciones que estructuran la vida social." },
    { t: "Monopolio legítimo de la fuerza", d: "Solo el Estado puede usar la fuerza de forma legal (policía, ejército)." },
    { t: "Norma formal", d: "Regla escrita y obligatoria (ley, reglamento)." },
    { t: "Norma informal", d: "Regla no escrita basada en costumbre o expectativa cultural." },
    { t: "Participación", d: "Acción de involucrarse en los asuntos públicos." },
    { t: "Racismo estructural", d: "Discriminación racial inscrita en instituciones y prácticas sociales." },
    { t: "Sufragio", d: "Derecho a votar y ser votado." },
  ],
  "CS-II": [
    { t: "Bienestar social", d: "Conjunto de condiciones que permiten a las personas vivir con dignidad y satisfacer sus necesidades." },
    { t: "Degradación ambiental", d: "Deterioro de la naturaleza causado por la actividad humana y ciertos modelos de desarrollo." },
    { t: "Discriminación", d: "Trato desigual e injusto hacia una persona o grupo por características como origen, color de piel, género o creencias." },
    { t: "Distribución", d: "Forma en que se reparten la riqueza, los bienes y los ingresos producidos en una sociedad." },
    { t: "Diversidad cultural", d: "Coexistencia de distintas culturas, lenguas, tradiciones y formas de vida en una sociedad." },
    { t: "Economía informal", d: "Actividades económicas que no están registradas ni reguladas oficialmente y suelen carecer de prestaciones." },
    { t: "Enfoque de derechos", d: "Perspectiva que entiende el bienestar como un conjunto de derechos garantizados para todas las personas, no como un favor." },
    { t: "Exclusión social", d: "Proceso por el cual a ciertas personas o grupos se les impide participar plenamente en la sociedad." },
    { t: "Factores de producción", d: "Elementos que se combinan para producir bienes y servicios: tierra, trabajo, capital, organización y tiempo." },
    { t: "Hegemonía", d: "Dominio o liderazgo de un grupo que se sostiene mediante consensos, no solo por la fuerza." },
    { t: "Intercambio desigual", d: "Relación de comercio en la que una región o país obtiene más beneficio que otro." },
    { t: "Interseccionalidad", d: "Enfoque que estudia cómo se cruzan distintas desigualdades (clase, género, raza, origen étnico, orientación sexual, edad) en una persona." },
    { t: "Modos de producción", d: "Maneras en que una sociedad organiza la producción de bienes y las relaciones de trabajo." },
    { t: "Necesidad", d: "Carencia o falta de algo indispensable para la vida y el desarrollo de las personas." },
    { t: "Necesidades vitales", d: "Aquellas indispensables para sobrevivir y vivir con dignidad, como alimentación, salud, vivienda y educación." },
    { t: "Organización comunitaria", d: "Forma en que las personas de una comunidad se agrupan y cooperan para resolver asuntos comunes." },
    { t: "Racismo", d: "Forma de discriminación que considera superiores a unas personas sobre otras por su origen étnico o color de piel." },
    { t: "Relaciones de poder", d: "Vínculos en los que unas personas o grupos influyen, deciden o controlan sobre otros dentro de la sociedad." },
    { t: "Satisfactor", d: "Bien, servicio o relación social con el que se cubre una necesidad." },
    { t: "Trabajo no remunerado", d: "Trabajo que sostiene la vida pero por el que no se recibe pago, como las tareas del hogar y de cuidados." },
  ],
  "CS-III": [
    { t: "Activismo digital", d: "Uso de plataformas y herramientas digitales para difundir causas, movilizar apoyos, organizar acciones colectivas y presionar a autoridades o empresas." },
    { t: "Actor social", d: "Individuo, grupo, organización o institución que tiene intereses, recursos y capacidad de acción frente a una situación social determinada." },
    { t: "Agencia juvenil", d: "Capacidad de las personas jóvenes para tomar decisiones, organizarse, reflexionar críticamente y actuar sobre su entorno social, político y cultural." },
    { t: "Causa estructural", d: "Factor de fondo, profundo y duradero —económico, político, cultural o histórico— que origina o agrava una crisis, más allá de sus detonantes inmediatos." },
    { t: "Ciclo de política pública", d: "Proceso iterativo que comprende las fases de identificación del problema, diseño, implementación, evaluación y retroalimentación de una política." },
    { t: "Construcción social de la juventud", d: "Proceso mediante el cual una sociedad define qué es ser joven, cuáles son sus roles, derechos y expectativas, determinado por el contexto histórico, cultural y socioeconómico." },
    { t: "Contraloría social", d: "Mecanismo mediante el cual la ciudadanía organizada vigila, evalúa y denuncia irregularidades en la ejecución de programas y obras públicas." },
    { t: "Crisis social", d: "Situación de ruptura o tensión grave en los vínculos, instituciones o condiciones de vida de una sociedad, que afecta la cohesión y el bienestar colectivo." },
    { t: "Diversidad juvenil", d: "Reconocimiento de que no existe una juventud homogénea: las experiencias juveniles varían según género, clase social, etnicidad, región, orientación sexual y contexto cultural." },
    { t: "Equidad en políticas públicas", d: "Principio que orienta las políticas a distribuir recursos y oportunidades según las necesidades de cada grupo, priorizando a quienes enfrentan mayores desventajas." },
    { t: "Escala de análisis", d: "Nivel territorial o social desde el que se observa un fenómeno: local, regional, nacional o global. El mismo problema puede verse diferente según la escala elegida." },
    { t: "Evaluación de impacto", d: "Análisis sistemático que mide los efectos causales de una política pública sobre la población objetivo, distinguiendo qué cambios son atribuibles a la intervención." },
    { t: "Participación ciudadana", d: "Involucramiento activo de la población en los asuntos públicos: desde informarse y votar hasta cogestionar programas o ejercer contraloría social." },
    { t: "Participación política juvenil", d: "Conjunto de acciones mediante las cuales las personas jóvenes intervienen en los asuntos públicos: voto, militancia, activismo, organización comunitaria, expresión cultural o digital." },
    { t: "Perspectiva multiescalar", d: "Enfoque analítico que conecta distintos niveles de la realidad social —desde lo cotidiano hasta lo global— para comprender un fenómeno de manera integral." },
    { t: "Política pública", d: "Conjunto de decisiones, acciones y omisiones del Estado orientadas a dar respuesta a un problema social reconocido como de interés colectivo." },
    { t: "Sujeto histórico", d: "Actor individual o colectivo que protagoniza y transforma los procesos históricos, no como mero receptor pasivo sino como agente activo de cambio." },
    { t: "Violencia estructural", d: "Forma de violencia invisible inscrita en las estructuras económicas, políticas y sociales que produce sufrimiento sin necesidad de un agresor directo identificable." },
  ],
};
