export const GLOSARIO_CD: Record<string, { t: string; d: string }[]> = {
  "CD-I": [
    { t: "Algoritmo", d: "Secuencia ordenada y finita de pasos para resolver un problema o realizar una tarea." },
    { t: "Basura electrónica (e-waste)", d: "Aparatos electrónicos desechados que contaminan si no se reciclan." },
    { t: "Brecha digital", d: "Desigualdad en el acceso y uso de las tecnologías digitales por motivos socioeconómicos, regionales o de género." },
    { t: "Ciberacoso", d: "Acoso u hostigamiento hacia una persona mediante medios digitales." },
    { t: "Código fuente", d: "Instrucciones escritas por las personas programadoras que se necesitan para estudiar y modificar un programa." },
    { t: "Colonialismo de datos", d: "Apropiación y control de los datos de las personas por grandes corporaciones, generando relaciones de poder desiguales." },
    { t: "Comunicación inclusiva", d: "Forma de comunicarse que respeta y representa a todas las personas." },
    { t: "Constante", d: "Valor con nombre que se mantiene fijo." },
    { t: "Contaminación digital", d: "Impacto ambiental de lo digital: consumo eléctrico, huella de carbono y basura electrónica." },
    { t: "Copyleft", d: "Licenciamiento que permite copiar, modificar y redistribuir una obra conservando las mismas libertades." },
    { t: "Creative Commons", d: "Conjunto de licencias libres para compartir obras (textos, imágenes, música) indicando qué usos se permiten." },
    { t: "Credenciales de acceso", d: "Datos que usas para entrar a un servicio digital, como usuario y contraseña." },
    { t: "Dato", d: "Valor sin procesar, como un número o un texto." },
    { t: "Dependencia tecnológica", d: "Situación en que personas o países dependen de tecnologías o empresas que no controlan." },
    { t: "Derecho a la privacidad", d: "Derecho a controlar quién accede a tu información personal." },
    { t: "Derecho al olvido", d: "Posibilidad de solicitar que se elimine información personal que ya no es pertinente." },
    { t: "Desinformación", d: "Información falsa o engañosa que se difunde, a veces de forma intencional." },
    { t: "Diagrama de flujo", d: "Representación gráfica de los pasos de un algoritmo usando símbolos conectados." },
    { t: "Diversidad digital", d: "Presencia de personas con distintas identidades, culturas y formas de pensar en el ciberespacio." },
    { t: "Estructura de control", d: "Forma de organizar las instrucciones: secuencial, condicional o repetitiva." },
    { t: "GNU/Linux", d: "Sistema operativo libre formado por el proyecto GNU y el núcleo Linux." },
    { t: "Hardware", d: "Conjunto de elementos físicos que componen un dispositivo electrónico." },
    { t: "Hoja de cálculo", d: "Programa para organizar datos en filas y columnas y hacer cálculos." },
    { t: "Identidad digital", d: "Conjunto de datos, perfiles y acciones que te representan en el ciberespacio." },
    { t: "Libertad de expresión digital", d: "Derecho a expresarse en línea con responsabilidad y respeto a los demás." },
    { t: "Licencia GPL", d: "Licencia (General Public License) que garantiza las libertades del software libre y que las versiones derivadas las conserven." },
    { t: "Licencia libre", d: "Permiso que autoriza usar, estudiar, modificar y compartir el software." },
    { t: "Licencia privativa", d: "Permiso de uso de software que restringe copiarlo, modificarlo o compartirlo." },
    { t: "Mercantilización de la atención", d: "Convertir la atención y el tiempo de las personas usuarias en un producto que se vende a anunciantes." },
    { t: "Navegador", d: "Programa que permite acceder y visualizar páginas y servicios de internet." },
    { t: "Netiqueta", d: "Conjunto de normas de buena conducta y respeto en la comunicación digital." },
    { t: "Open source", d: "Enfoque que destaca las ventajas prácticas del código abierto; suele coincidir con el software libre, pero con otra motivación." },
    { t: "Operador", d: "Símbolo que opera sobre valores: aritmético, relacional o lógico." },
    { t: "Phishing", d: "Engaño que suplanta a una entidad de confianza para robar datos o contraseñas." },
    { t: "Presentación electrónica", d: "Programa para crear diapositivas para exponer un tema." },
    { t: "Procesador de texto", d: "Programa para escribir y dar formato a documentos." },
    { t: "Protección de datos", d: "Resguardo de la información personal frente a usos indebidos." },
    { t: "Protección de datos personales", d: "Normas que regulan cómo se recogen, usan y guardan tus datos." },
    { t: "Respaldo (backup)", d: "Copia de seguridad de tus archivos para no perderlos." },
    { t: "Seguridad digital", d: "Conjunto de prácticas para proteger tu información, dispositivos y cuentas." },
    { t: "Sistema operativo", d: "Software base que administra el hardware y permite ejecutar otros programas." },
    { t: "Software", d: "Conjunto de programas, instrucciones y reglas que permiten que el dispositivo funcione." },
    { t: "Software libre", d: "Software que respeta las cuatro libertades: usar, estudiar, distribuir y mejorar." },
    { t: "Suite ofimática", d: "Conjunto de programas de oficina: procesador de texto, hoja de cálculo y presentaciones." },
    { t: "Unidad de medida digital", d: "Cantidad para expresar almacenamiento, velocidad o procesamiento." },
    { t: "Uso responsable de la IA", d: "Empleo crítico y ético de la inteligencia artificial: verificar, dar crédito y respetar la autoría." },
    { t: "Variable", d: "Espacio con nombre cuyo valor puede cambiar durante el proceso." },
    { t: "Vigilancia digital", d: "Seguimiento de la actividad en línea de las personas, a veces sin su consentimiento." },
  ],
  "CD-II": [
    { t: "Acceso libre", d: "Característica de un recurso o herramienta que puede usarse sin costo ni restricciones de licencia." },
    { t: "Análisis de contenido en línea", d: "Técnica para examinar de forma sistemática textos, imágenes o videos digitales." },
    { t: "Blogspot (Blogger)", d: "Servicio gratuito de Google para crear y publicar blogs de forma sencilla." },
    { t: "Buscar información", d: "Localizar datos sobre un tema usando buscadores y fuentes digitales." },
    { t: "Ciberetnografía", d: "Método que estudia culturas, prácticas y comunidades de las personas en entornos digitales." },
    { t: "Cryptpad", d: "Herramienta colaborativa libre que permite escribir y compartir documentos cuidando la privacidad mediante cifrado." },
    { t: "Difusión", d: "Acción de dar a conocer información a un público amplio." },
    { t: "Discriminar información", d: "Distinguir las fuentes confiables y pertinentes de las que no lo son." },
    { t: "Edición en tiempo real", d: "Posibilidad de que varias personas modifiquen un documento simultáneamente y vean los cambios al instante." },
    { t: "Entrevista", d: "Conversación dirigida con preguntas para obtener información de una persona." },
    { t: "Gestionar información", d: "Organizar, guardar y dar sentido a la información para usarla en un propósito." },
    { t: "Grupo focal", d: "Reunión de un grupo pequeño para conversar y recoger opiniones sobre un tema." },
    { t: "Licencia permisiva", d: "Licencia que autoriza usar, compartir y a veces modificar una obra o programa." },
    { t: "Media (promedio)", d: "Suma de todos los valores dividida entre la cantidad de datos." },
    { t: "Medida de dispersión", d: "Valor que indica qué tan separados están los datos entre sí." },
    { t: "Medida de tendencia central", d: "Valor que resume un conjunto de datos: media, mediana o moda." },
    { t: "Página web", d: "Documento en internet que combina texto, imágenes y enlaces para compartir información." },
    { t: "Perspectiva ética y crítica", d: "Forma de publicar que verifica la información, cita fuentes y respeta a las personas." },
    { t: "Representación gráfica", d: "Forma visual de mostrar datos para entenderlos y comunicarlos." },
    { t: "Riseup pad", d: "Editor de texto colaborativo en línea, libre y sencillo, para escribir entre varias personas al mismo tiempo." },
    { t: "Software estadístico libre", d: "Programas gratuitos y abiertos para analizar datos." },
    { t: "TICCAD", d: "Tecnologías de Información, Comunicación, Conocimiento y Aprendizajes Digitales." },
    { t: "Trabajo colaborativo digital", d: "Forma de trabajar en equipo usando herramientas digitales para construir un producto común." },
    { t: "Transversalidad", d: "Conexión de un tema o proyecto con varias asignaturas a la vez." },
    { t: "WordPress", d: "Plataforma para crear sitios web y blogs con plantillas, sin necesidad de programar." },
  ],
  "CD-III": [
    { t: "Accesibilidad digital", d: "Diseño de contenidos y plataformas que pueden ser usados por todas las personas, independientemente de sus capacidades físicas, sensoriales o cognitivas. Incluye subtítulos, descripciones de audio, contraste visual y lenguaje sencillo." },
    { t: "Análisis crítico de medios digitales", d: "Práctica de examinar mensajes digitales preguntando: ¿quién lo produce?, ¿con qué intención?, ¿qué voces incluye y cuáles excluye?, ¿qué valores implica?, ¿qué efectos puede tener? Es una competencia de ciudadanía digital." },
    { t: "Brecha de género en STEM", d: "Subrepresentación histórica de mujeres y personas de géneros no binarios en carreras de Ciencia, Tecnología, Ingeniería y Matemáticas. Se origina en estereotipos de género, falta de referentes, sesgos en la enseñanza y ambientes laborales poco inclusivos." },
    { t: "Brecha digital de género", d: "Desigualdad en el acceso, uso, habilidades y participación en entornos digitales entre personas de diferentes géneros. Afecta especialmente a mujeres y disidencias en comunidades rurales, de bajos ingresos y en países en desarrollo." },
    { t: "Burbuja de filtro (filter bubble)", d: "Fenómeno por el cual los algoritmos personalizan el contenido que recibe un usuario basándose en sus interacciones previas, limitando su exposición a perspectivas diversas y reforzando sus creencias existentes." },
    { t: "Ciberseguridad", d: "Campo profesional dedicado a proteger sistemas informáticos, redes, datos y usuarios de ataques, accesos no autorizados, robo de información y otros riesgos digitales. Incluye roles como analista de seguridad, hacker ético y gestor de incidentes." },
    { t: "Ciencia de datos (Data Science)", d: "Disciplina que combina estadística, programación y conocimiento del dominio para extraer información valiosa de grandes conjuntos de datos. Permite tomar decisiones basadas en evidencia en áreas como salud, educación, negocios y gobierno." },
    { t: "Ciudadanía digital activa", d: "Práctica de participar responsablemente en la vida cívica, política y comunitaria a través de herramientas digitales: peticiones, campañas, consultas, difusión de información y organización colectiva en línea." },
    { t: "Comunicación multimodal", d: "Forma de comunicar que combina de manera simultánea e integrada diferentes modos semióticos: texto escrito, imagen, audio, video, color, gesto y diseño espacial. El significado emerge de la interacción entre todos los modos." },
    { t: "Contenido digital de calidad", d: "Producción digital que es veraz, accesible, relevante para su audiencia, éticamente producida (cita fuentes, respeta derechos de autor), estéticamente cuidada y orientada a un propósito comunicativo claro." },
    { t: "Diagnóstico comunitario", d: "Proceso sistemático de identificar y analizar las necesidades, recursos, actores y contexto de una comunidad antes de diseñar una intervención. En proyectos digitales, incluye mapear el acceso a tecnología y las competencias digitales de la comunidad." },
    { t: "Diseño participativo", d: "Enfoque de diseño que involucra a los usuarios finales (en este caso, la comunidad) como co-creadores del proyecto desde el inicio, no solo como receptores de soluciones. Garantiza pertinencia y apropiación del proyecto." },
    { t: "Diseño UX/UI", d: "UX (User Experience) se ocupa de que los productos digitales sean funcionales, intuitivos y satisfactorios para el usuario. UI (User Interface) diseña los elementos visuales e interactivos de la interfaz. Ambos roles son fundamentales en el desarrollo de apps y sitios web." },
    { t: "Evaluación de impacto comunitario", d: "Proceso de medir y valorar los cambios producidos por un proyecto en la comunidad: participación, conocimiento generado, problemas resueltos, redes fortalecidas. Incluye indicadores cuantitativos y cualitativos." },
    { t: "Herramientas de participación digital", d: "Plataformas y aplicaciones que facilitan la organización, comunicación y acción colectiva en comunidades. Incluyen: grupos de WhatsApp/Telegram, encuestas en línea (Google Forms), plataformas de peticiones (Change.org), mapas colaborativos (Google Maps, Ushahidi) y redes sociales." },
    { t: "Identidad digital", d: "Conjunto de rasgos, representaciones y datos que caracterizan a una persona en entornos digitales. Se construye a partir de publicaciones propias, datos recopilados por plataformas, interacciones y la narrativa que los algoritmos elaboran sobre el usuario." },
    { t: "Lenguaje incluyente", d: "Uso del lenguaje que evita la invisibilización o estereotipación de géneros. Puede incluir formas no binarias (la/el directora/director), términos neutros (estudiantado, comunidad) o el uso del género no marcado según contexto." },
    { t: "Modo semiótico", d: "Sistema de recursos culturales y sociales para crear significado. Los modos digitales incluyen: texto, imagen estática, imagen en movimiento, audio, color, tipografía y diseño de interfaz." },
    { t: "Narrativa digital y construcción de realidad", d: "Las narrativas que circulan en entornos digitales configuran percepciones colectivas sobre grupos sociales, eventos y valores. A través de la repetición y viralización, ciertos relatos se naturalizan como 'realidad'." },
    { t: "Perspectiva de género", d: "Enfoque analítico que examina cómo las normas, roles y expectativas sociales asignadas por género producen desigualdades. En la producción digital, implica crear contenidos que cuestionen estereotipos y promuevan relaciones más equitativas." },
    { t: "Sector TIC (Tecnologías de la Información y Comunicación)", d: "Conjunto de industrias y profesiones relacionadas con la creación, gestión, difusión y uso de tecnologías digitales. Incluye programación, diseño digital, ciencia de datos, ciberseguridad, comunicación digital, inteligencia artificial y más." },
    { t: "Sostenibilidad del proyecto", d: "Capacidad de un proyecto comunitario de mantenerse activo y generar impacto más allá del período inicial sin depender de recursos externos constantes. Implica formación de capacidades locales, liderazgo distribuido y uso de tecnologías de bajo costo." },
    { t: "Transformación social digital", d: "Uso de herramientas y plataformas digitales para visibilizar problemáticas sociales, movilizar comunidades, amplificar voces marginadas y proponer soluciones colectivas a injusticias estructurales." },
    { t: "Trayectoria formativa no lineal", d: "En el sector digital, muchas personas construyen su carrera combinando educación formal (universidad, técnico) con aprendizaje autodidacta, cursos en línea (MOOC), bootcamps, proyectos personales y comunidades de práctica. No existe una única ruta." },
  ],
};
