export const GLOSARIO_IN: Record<string, { t: string; d: string }[]> = {
  "IN-I": [
    { t: "Address", d: "Dirección o domicilio." },
    { t: "at / on / in", d: "Preposiciones de tiempo: at (hora), on (día), in (mes/año)." },
    { t: "backpack", d: "Mochila." },
    { t: "because", d: "Conector para dar una razón." },
    { t: "big / small", d: "Tamaños: grande / pequeño." },
    { t: "board", d: "Pizarrón." },
    { t: "Can you repeat that, please?", d: "Pedir que repitan algo de forma cortés." },
    { t: "curly / straight / wavy", d: "Tipo de cabello: rizado / lacio / ondulado." },
    { t: "desk", d: "Escritorio o pupitre." },
    { t: "Do you like...?", d: "Pregunta de gusto. Respuesta: Yes, I do / No, I don't." },
    { t: "Email address", d: "Correo electrónico." },
    { t: "Excuse me", d: "Frase cortés para iniciar una pregunta a un desconocido." },
    { t: "First name / Last name", d: "Nombre de pila / apellido." },
    { t: "Good morning", d: "Saludo formal usado por la mañana." },
    { t: "Goodbye / Bye", d: "Despedida. 'Bye' es la forma informal." },
    { t: "Hand in your homework", d: "Instrucción: entregar la tarea." },
    { t: "Hello / Hi", d: "Saludo. 'Hello' es neutro y 'Hi' es informal." },
    { t: "How old are you?", d: "Pregunta de edad. Se responde 'I am ... years old'." },
    { t: "I agree / I disagree", d: "Expresar acuerdo o desacuerdo." },
    { t: "I don't mind", d: "No me molesta (gusto neutro)." },
    { t: "I don't understand", d: "Frase para indicar que no comprendiste." },
    { t: "I like / I don't like", d: "Me gusta / no me gusta." },
    { t: "I love / I hate", d: "Me encanta / odio (grados extremos)." },
    { t: "in front of / behind", d: "Enfrente de / detrás de." },
    { t: "It is raining / snowing", d: "Está lloviendo / nevando (acción en curso)." },
    { t: "May I...?", d: "Forma cortés de pedir permiso." },
    { t: "mine / yours / hers", d: "Pronombres posesivos (van solos, sin sustantivo)." },
    { t: "my / your / his / her", d: "Adjetivos posesivos (van antes del sustantivo)." },
    { t: "Nationality", d: "Nacionalidad (con mayúscula en inglés)." },
    { t: "next to / near", d: "Preposiciones de lugar: al lado de / cerca de." },
    { t: "Nice to meet you", d: "Frase que se dice al conocer a alguien por primera vez (mucho gusto)." },
    { t: "our / their", d: "Nuestro / su (de ellos)." },
    { t: "round / square", d: "Formas: redondo / cuadrado." },
    { t: "Saxon genitive ('s)", d: "Apóstrofo + s para indicar posesión." },
    { t: "sunny / cloudy / rainy", d: "Clima: soleado / nublado / lluvioso." },
    { t: "tall / short", d: "Estatura: alto / bajo." },
    { t: "There is / There are", d: "Para indicar que hay algo (singular / plural)." },
    { t: "This is...", d: "Estructura para presentar a otra persona." },
    { t: "to be (am/is/are)", d: "Verbo ser/estar. I am, you are, he/she is." },
    { t: "to belong to", d: "Pertenecer a." },
    { t: "to have (has)", d: "Tener; describe rasgos físicos." },
    { t: "to wear", d: "Llevar puesta una prenda." },
    { t: "verb + -ing", d: "Forma del verbo tras 'like' (gerundio)." },
    { t: "When / What time", d: "Palabras para preguntar tiempo (cuándo / a qué hora)." },
    { t: "Where", d: "Palabra interrogativa para lugar (dónde)." },
    { t: "Where are you from?", d: "Pregunta de origen. Se responde 'I'm from ...'." },
    { t: "Whose...?", d: "Pregunta de posesión: ¿de quién es...?" },
    { t: "Work in pairs", d: "Instrucción: trabajar en parejas." },
  ],
  "IN-II": [
    { t: "-er + than", d: "Comparativo de adjetivos cortos (1 sílaba)." },
    { t: "3rd person -s", d: "Con he/she/it el verbo agrega -s en presente simple." },
    { t: "ability", d: "Something you know how to do." },
    { t: "always / usually / sometimes / never", d: "Adverbios de frecuencia (siempre / usualmente / a veces / nunca)." },
    { t: "better / worse", d: "Comparativos irregulares de good / bad." },
    { t: "by bus / on foot", d: "Medios de transporte: en autobús / a pie." },
    { t: "can / can't", d: "Verbo modal para habilidad y permiso (poder / no poder)." },
    { t: "Can I...?", d: "Forma de pedir permiso de manera cortés." },
    { t: "cardinal numbers", d: "Números para contar: one, two... hundred, thousand." },
    { t: "cheaper / more expensive", d: "Más barato / más caro (para comparar precios)." },
    { t: "comparative adjective", d: "An adjective used to compare two things." },
    { t: "countable / uncountable", d: "Sustantivos contables (apples) e incontables (water, rice)." },
    { t: "countable noun", d: "A noun you can count with numbers (apple, book, friend)." },
    { t: "days of the week", d: "Días de la semana: Monday, Tuesday, Wednesday..." },
    { t: "Do / Does ...?", d: "Auxiliares para hacer preguntas en presente simple." },
    { t: "don't / doesn't", d: "Formas negativas del presente simple (do not / does not)." },
    { t: "every day / on weekends", d: "Expresiones de tiempo: todos los días / los fines de semana." },
    { t: "food & drinks", d: "Alimentos y bebidas: bread, milk, coffee, juice." },
    { t: "frequency adverb", d: "A word that says how often something happens (always, usually, sometimes, never)." },
    { t: "go straight", d: "Imperativo: sigue derecho/recto." },
    { t: "his / her / their", d: "Adjetivos posesivos (de él / de ella / de ellos)." },
    { t: "hobby", d: "Pasatiempo, actividad de ocio." },
    { t: "How do you spell...?", d: "Pregunta para pedir el deletreo de una palabra." },
    { t: "How much / How many", d: "Cantidad: how much (incontable) / how many (contable)." },
    { t: "How much is it?", d: "¿Cuánto cuesta? (para preguntar precios)." },
    { t: "hundred / thousand", d: "Cien / mil (números grandes)." },
    { t: "I prefer", d: "Prefiero (para expresar elecciones)." },
    { t: "I'd like (would like)", d: "Forma cortés de pedir algo o expresar un deseo." },
    { t: "in the morning / at night", d: "Momentos del día: en la mañana / en la noche." },
    { t: "into / across", d: "Preposiciones de movimiento: hacia dentro de / a través de." },
    { t: "is wearing", d: "Present continuous para la ropa que lleva alguien." },
    { t: "more + adjective + than", d: "Comparativo de adjetivos largos (2+ sílabas)." },
    { t: "next to / across from", d: "Preposiciones de lugar: al lado de / enfrente de." },
    { t: "ordinal numbers", d: "Números de orden: first (1st), second (2nd), third (3rd)." },
    { t: "permission", d: "Being allowed or not allowed to do something." },
    { t: "places in town", d: "Lugares en la ciudad: park, hospital, market, bus station." },
    { t: "preposition of movement", d: "A word showing direction or movement (into, across, past, along)." },
    { t: "present continuous", d: "A tense used for actions happening right now (subject + is/are + verb-ing)." },
    { t: "present simple", d: "Tiempo para hábitos y hechos (con -s en 3ª persona singular)." },
    { t: "routine", d: "A set of activities done regularly and in the same order." },
    { t: "seasons", d: "Estaciones: spring, summer, autumn/fall, winter." },
    { t: "short answers", d: "Respuestas cortas: Yes, I do / No, he doesn't." },
    { t: "sunny / cloudy / rainy / windy", d: "Adjetivos de clima: soleado / nublado / lluvioso / ventoso." },
    { t: "T-shirt / jeans / jacket", d: "Prendas de vestir: playera / jeans / chamarra." },
    { t: "than", d: "Palabra que conecta los dos elementos comparados (que)." },
    { t: "the alphabet", d: "El abecedario en inglés, usado para deletrear." },
    { t: "to cook / to swim", d: "Cocinar / nadar (habilidades comunes)." },
    { t: "to do homework", d: "Hacer la tarea." },
    { t: "to get up", d: "Levantarse de la cama." },
    { t: "to hang out", d: "Pasar el rato con amigos." },
    { t: "to have / has", d: "Tener; describe rasgos físicos (he/she usa 'has')." },
    { t: "to have breakfast", d: "Desayunar." },
    { t: "to play the guitar", d: "Tocar la guitarra." },
    { t: "to play video games", d: "Jugar videojuegos." },
    { t: "turn left / turn right", d: "Imperativos: da vuelta a la izquierda / derecha." },
    { t: "uncountable noun", d: "A noun you cannot count directly (water, information, money)." },
    { t: "would like", d: "A polite way to express a wish or preference." },
    { t: "would like + to + verb", d: "Para expresar un deseo de hacer algo." },
  ],
  "IN-III": [
    { t: "above / below", d: "Higher than (above) or lower than (below) something (encima de / debajo de)." },
    { t: "After that / Next", d: "Conectores: después de eso / a continuación — pasos intermedios." },
    { t: "already / yet", d: "Ya (afirmativo) / todavía no (negativo/pregunta)." },
    { t: "at the end / in the end", d: "Al final (de un evento o historia)." },
    { t: "behind", d: "At the back of something (detrás de)." },
    { t: "behind / opposite", d: "Preposiciones de lugar: detrás de / frente a (al otro lado)." },
    { t: "between", d: "In the space that separates two things (entre — dos cosas)." },
    { t: "can (posibilidad)", d: "'Can' is also used to express possibility — something that is possible to find or do in a place." },
    { t: "can (possibility)", d: "'Can' para indicar lo que es posible hacer en un lugar." },
    { t: "chores at home", d: "Quehaceres del hogar: do the dishes, take out the rubbish, tidy your room." },
    { t: "community responsibilities", d: "Responsabilidades en la comunidad: recycle, keep the streets clean." },
    { t: "comparative (-er than / more...than)", d: "Para comparar dos cosas (revisión): taller than / more comfortable than." },
    { t: "Comparatives & superlatives", d: "Revisar: -er than / more...than y the -est / the most." },
    { t: "Did...?", d: "Auxiliar para formar preguntas en pasado simple." },
    { t: "didn't + verb base", d: "Forma negativa del pasado simple para todos los sujetos." },
    { t: "don't have to / doesn't have to", d: "No es necesario (pero es opcional)." },
    { t: "ever / never", d: "Alguna vez / nunca — marcadores de experiencia." },
    { t: "Finally", d: "Conector: finalmente — para el último paso." },
    { t: "First / Then", d: "Conectores: primero / después — para el 1er y 2do paso." },
    { t: "frequency adverbs", d: "Adverbios de frecuencia: always, usually, often, sometimes, rarely, never." },
    { t: "have / has + past participle", d: "Estructura del presente perfecto (experiencias, logros recientes)." },
    { t: "have to / has to", d: "Obligación externa: tener que (he/she usa 'has to')." },
    { t: "Have you...? / I have...", d: "Estructura de pregunta y respuesta en presente perfecto." },
    { t: "imperative (affirmative)", d: "Verbo base sin sujeto para dar instrucciones: Open, Close, Write, Read." },
    { t: "imperative (negative)", d: "Don't + verbo base para prohibir o advertir." },
    { t: "in front of", d: "Facing something, on the opposite side (enfrente de)." },
    { t: "instructions vocabulary", d: "Verbos comunes en instrucciones: click, press, add, mix, cut, turn on/off." },
    { t: "irregular verbs", d: "Verbos con forma de pasado única (go→went, eat→ate, see→saw)." },
    { t: "irregular verbs (list)", d: "Irregulares frecuentes: go→went, see→saw, eat→ate, buy→bought, meet→met, take→took." },
    { t: "later / afterwards", d: "Conectores: más tarde / después — para un evento posterior." },
    { t: "like + noun / like + verb-ing", d: "Expresar gustos: I like coffee / I like swimming." },
    { t: "must / have to / mustn't / don't have to", d: "Modales: obligación, prohibición y ausencia de obligación." },
    { t: "must / mustn't", d: "Obligación fuerte o prohibición: deber / no deber (está prohibido)." },
    { t: "Narrative connectors", d: "Conectores de narración: then, after, later, suddenly, in the end." },
    { t: "next to", d: "Immediately beside something or someone (al lado de)." },
    { t: "next to / between / in front of", d: "Preposiciones de lugar: al lado de / entre / enfrente de." },
    { t: "on the corner of", d: "Located at the intersection of two streets (en la esquina de)." },
    { t: "opposite", d: "On the other side of a street or space (frente a, en el lado contrario)." },
    { t: "past participle", d: "3ª forma del verbo: visited, eaten, seen, been, done." },
    { t: "places of interest", d: "Lugares de interés: market, cathedral, museum, park, beach." },
    { t: "prefer...to", d: "Preferir una cosa sobre otra." },
    { t: "Present Perfect vs. Past Simple", d: "Perfecto = experiencia sin tiempo fijo. Pasado simple = tiempo específico." },
    { t: "regular verbs (-ed)", d: "Verbos que forman el pasado agregando -ed." },
    { t: "rules at school", d: "Normas del colegio: be on time, respect others, keep quiet." },
    { t: "Sequential connectors", d: "Conectores de instrucción: first, then, after that, finally." },
    { t: "should / can (recommendations & possibility)", d: "Should para recomendar; can para posibilidad o habilidad." },
    { t: "suddenly / all of a sudden", d: "De repente — para eventos inesperados." },
    { t: "superlative (the -est / the most)", d: "Para el extremo de una serie: the fastest / the most popular." },
    { t: "the best / the worst", d: "Superlativos irregulares de good/bad." },
    { t: "then / after", d: "Conectores: luego / después — para el siguiente evento en la historia." },
    { t: "there are", d: "Used to say that multiple things exist or can be found in a place (plural)." },
    { t: "there is", d: "Used to say that something exists or can be found in a place (singular)." },
    { t: "There is / There are", d: "Hay (singular / plural) para describir lo que existe en un lugar." },
    { t: "this week / recently", d: "Esta semana / recientemente — para rutinas pasadas recientes." },
    { t: "while / when", d: "Mientras / cuando — para situar dos eventos simultáneos o relacionados." },
    { t: "with whom / with my family", d: "Con quién — para describir experiencias compartidas." },
    { t: "yesterday / last week / ago", d: "Marcadores de tiempo del pasado (ayer / la semana pasada / hace)." },
    { t: "you should / you can", d: "Recomendaciones básicas: deberías / puedes." },
  ],
  "IN-IV": [
    { t: "anecdote opener", d: "Expresión para captar la atención al iniciar una historia." },
    { t: "anecdote structure", d: "Estructura de la anécdota: apertura, escena, complicación, resolución, reacción." },
    { t: "Anyway", d: "De todas formas, de todos modos, bueno. Se usa para cambiar de tema, volver al tema principal, o cerrar educadamente una conversación." },
    { t: "Anyway, I should get going.", d: "Expresión para empezar a cerrar la conversación." },
    { t: "backchannels (Really? / That's great!)", d: "Respuestas breves que muestran atención e interés." },
    { t: "be going to / I'm planning to / I hope to", d: "Estructuras para planes, intenciones y deseos futuros." },
    { t: "be going to + infinitive", d: "Plan o intención ya decidida para el futuro." },
    { t: "be used to + verb-ing", d: "Estar acostumbrado/a a algo (ya no es difícil)." },
    { t: "because", d: "Porque. Conjunción causal que introduce la razón o causa de una acción. Conecta dos cláusulas." },
    { t: "because / since / as", d: "Conectores causales para justificar una preferencia." },
    { t: "By the way", d: "Por cierto, a propósito. Se usa para introducir un tema nuevo o información adicional en la conversación." },
    { t: "commute", d: "Viajar diariamente entre el hogar y el trabajo o escuela (trasladarse). Se usa como verbo y como sustantivo." },
    { t: "complication", d: "El evento inesperado o problema central de la anécdota." },
    { t: "context phrases", d: "Frases contextuales: on school days, at weekends, during the week." },
    { t: "detail expressions", d: "Frases para añadir detalle: with my family, at the time, right there." },
    { t: "due to", d: "Debido a, a causa de. Conector causal más formal que 'because'. Se usa antes de un sustantivo o frase nominal." },
    { t: "Excuse me, could I...?", d: "Forma educada de iniciar una conversación o pedir algo." },
    { t: "future time expressions", d: "Marcadores temporales: next year, soon, by the end of, in the future." },
    { t: "get used to", d: "Acostumbrarse a algo (adaptarse a una nueva situación o hábito). Se usa con verbo en -ing o sustantivo." },
    { t: "go to bed", d: "Ir a dormir, acostarse por la noche (irse a la cama)." },
    { t: "have breakfast / lunch / dinner", d: "Tomar el desayuno / almuerzo / cena. En inglés no usamos artículo (no se dice 'have a breakfast')." },
    { t: "Have you thought about + verb-ing?", d: "Sugerencia amable que invita a reflexionar." },
    { t: "How are you?", d: "Saludo informal: ¿Cómo estás? / ¿Cómo te encuentras? Es una expresión de cortesía, no siempre una pregunta literal sobre la salud." },
    { t: "How have you been?", d: "Saludo de continuación para alguien que no ves hace tiempo." },
    { t: "I hope to + infinitive", d: "Deseo o aspiración para el futuro." },
    { t: "I tend to + infinitive", d: "Tener tendencia a hacer algo habitualmente." },
    { t: "I'd rather + bare infinitive", d: "Preferir hacer algo en este momento o en general." },
    { t: "I'm planning to + infinitive", d: "Intención planificada o bien pensada." },
    { t: "Ice-breaker", d: "Una actividad o pregunta para romper el hielo — para hacer que personas que no se conocen se sientan más cómodas al inicio de una conversación o reunión." },
    { t: "If I were you, I would...", d: "Consejo empático usando el condicional II." },
    { t: "in my opinion / personally", d: "Expresiones para introducir una opinión o preferencia personal." },
    { t: "in the end / luckily / unfortunately", d: "Expresiones para la resolución o reacción final." },
    { t: "It was nice/great talking to you!", d: "Frase de despedida cordial y natural." },
    { t: "It was the first time I...", d: "Expresión para hablar de una experiencia completamente nueva." },
    { t: "narrative connectors", d: "Conectores narrativos: then, after that, suddenly, all of a sudden, eventually." },
    { t: "Nice to meet you", d: "Mucho gusto / Encantado(a) de conocerte. Expresión formal o informal al conocer a alguien por primera vez." },
    { t: "past continuous (was/were + -ing)", d: "Background action ongoing at a moment in the past." },
    { t: "Past continuous + past simple", d: "Combinación para narrar: fondo (past continuous) + evento (past simple)." },
    { t: "past simple (interruption)", d: "A completed action that interrupts a background activity." },
    { t: "Polite expressions", d: "Expresiones de cortesía en inglés: please, thank you, excuse me, I'm sorry, you're welcome. Son esenciales en conversaciones formales e informales." },
    { t: "prefer / I'd rather / If I were you", d: "Estructuras para preferencias y consejos empáticos." },
    { t: "prefer X to Y", d: "Estructura para preferir X sobre Y (sustantivos o verbos -ing)." },
    { t: "present simple (habits)", d: "Tiempo para acciones habituales o rutinas: I walk, she studies, we eat." },
    { t: "rarely", d: "Rara vez, casi nunca. Adverbio de frecuencia (~10-20% del tiempo). Indica poca frecuencia." },
    { t: "reaction phrases", d: "Expresar cómo te sentiste al final: I couldn't believe it, It was hilarious, I was so relieved." },
    { t: "reason connectors", d: "Conectores causales para explicar hábitos: because, since, as a result." },
    { t: "See you around", d: "Nos vemos por ahí, hasta luego. Expresión informal para despedirse sin una fecha concreta de volverte a ver." },
    { t: "setting the scene", d: "Presentar el contexto: cuándo, dónde y quién estaba." },
    { t: "Small talk", d: "Conversación informal y ligera sobre temas poco importantes (clima, fin de semana, fútbol) para romper el hielo o ser sociable. No busca profundidad." },
    { t: "so that / because / in order to", d: "Conectores de propósito y causa para explicar hábitos, planes o consejos." },
    { t: "so that / because it matters", d: "Explicar por qué el plan es importante." },
    { t: "so that / in order to", d: "Conectores de propósito: para que / con el fin de." },
    { t: "social conversation toolkit", d: "Herramientas de conversación: How have you been? / Really? / By the way / Anyway..." },
    { t: "tend to", d: "Tener la tendencia a hacer algo (soler hacer). Expresa un hábito o patrón general de comportamiento." },
    { t: "That must be tough / I understand", d: "Expresiones de empatía antes de dar un consejo." },
    { t: "That sounds good, but...", d: "Expresión de discrepancia respetuosa al dar la propia opinión." },
    { t: "time expressions (past)", d: "Marcadores temporales: last year, ago, in 2022, when I was ten." },
    { t: "Turn-taking", d: "El turno para hablar en una conversación. En inglés, las señales de turn-taking indican cuándo ceder o tomar la palabra de forma educada." },
    { t: "usually", d: "Normalmente, generalmente. Adverbio de frecuencia (~80% del tiempo). Va antes del verbo principal pero después de 'be'." },
    { t: "wake up", d: "Dejar de dormir y abrir los ojos por la mañana (despertarse). Verbo irregular: wake → woke → woken." },
    { t: "We could + infinitive", d: "Propuesta amable de plan grupal o comunitario." },
    { t: "What do you prefer, X or Y?", d: "Pregunta estándar para conocer las preferencias de alguien." },
    { t: "What do you think I should do?", d: "Pregunta estándar para pedir consejo en inglés." },
    { t: "What have you been up to?", d: "¿Qué has estado haciendo últimamente? Pregunta informal para iniciar conversación y ponerse al día con alguien." },
    { t: "while / when", d: "Conectores de simultaneidad: mientras / cuando." },
    { t: "Why don't you + verb?", d: "Sugerencia informal y amistosa." },
    { t: "You should / shouldn't + infinitive", d: "Consejo directo: deberías / no deberías hacer algo." },
  ],
  "IN-V": [
    { t: "According to the author / According to the text...", d: "A citation phrase used to attribute an idea to the source text without copying it verbatim. Essential for academic writing and reading responses." },
    { t: "achievement", d: "Logro: algo que se consiguió mediante esfuerzo y dedicación. En un contexto académico o profesional, se refiere a éxitos concretos." },
    { t: "As demonstrated in this project... / The evidence shows that...", d: "Phrases used in conclusions to refer back to the content of the project. They introduce a summary of findings or a final argument supported by the work done." },
    { t: "As far as I know... / In my understanding...", d: "Phrases to introduce an answer when you are not 100% certain. They show intellectual honesty and are common in academic and professional conversations." },
    { t: "Based on my research... / According to [source]...", d: "Phrases to introduce evidence or findings from reading and research. They show that the project is based on information, not just personal opinion." },
    { t: "career", d: "Carrera profesional: la trayectoria laboral o el camino profesional de una persona a largo plazo. ¡Ojo! No confundir con 'carrera universitaria' = degree o major. 'Career' se refiere a la vida profesional en general." },
    { t: "Could you explain...?", d: "A polite request for an explanation. 'Could you explain + noun/phrase?' is more formal and indirect than 'Can you explain...?' Structure: explain [something] to [someone]." },
    { t: "Could you repeat that, please? / Could you clarify what you mean by...?", d: "Clarification requests used when you do not understand a question or comment. Essential communication strategies for professional and academic interactions." },
    { t: "Dear Mr./Ms. [Last Name], / Best regards, / Yours sincerely,", d: "Formal salutations and closings. 'Dear + title + last name' opens formal emails. 'Best regards' or 'Kind regards' are semi-formal closings. 'Yours sincerely' is used when the recipient's name is known." },
    { t: "experience", d: "Experiencia: conocimiento o habilidad adquirida mediante la práctica o vivencias. También puede referirse a un evento específico que se vivió." },
    { t: "field of study", d: "Campo de estudio: el área académica o disciplina en la que una persona se especializa o que le interesa." },
    { t: "First... Second... Finally... / The first step is to...", d: "Structures for describing a process in order. These discourse markers help explain procedures step by step clearly." },
    { t: "First... Then... After that... Finally...", d: "Sequencing connectors used to organize a narrative in chronological order. Essential for telling a story or describing a sequence of events clearly." },
    { t: "From my experience... / Based on what I have learned...", d: "Phrases to introduce personal experience or knowledge as support for an argument or response in an interview or discussion." },
    { t: "From my point of view... / As I see it...", d: "Phrases to introduce a personal perspective or interpretation, slightly more emphatic than 'in my opinion'. Common in discussions and debates." },
    { t: "Furthermore, / Moreover, / In addition to this...", d: "Additive connectors used to introduce additional supporting points or evidence. They make the argument richer and show that the writer has multiple supporting ideas." },
    { t: "How does... work?", d: "A question used to ask for an explanation of how a system, machine, concept, or process functions. Uses auxiliary 'does' for third person singular." },
    { t: "However / Nevertheless / On the other hand...", d: "Contrast connectors used in texts to introduce opposing ideas, counterarguments, or contrasting information. Recognizing them helps comprehension of complex texts." },
    { t: "I am worried about / I am concerned about...", d: "Structures to express concern or anxiety about a situation or problem. Both are followed by a noun or gerund (-ing form)." },
    { t: "I am writing to... (inform / request / propose / inquire)", d: "The standard opening for a formal email or letter in English. It states the purpose directly. 'I am writing to' is always followed by the base form of a verb (the to-infinitive): 'I am writing to inform you…', 'I am writing to request…'." },
    { t: "I find this text / argument... because...", d: "An opinion structure for evaluating a text. 'I find [noun/adjective] because [reason]' expresses a personal evaluation supported by reasoning." },
    { t: "I have always been interested in...", d: "Uses the present perfect with 'always' to describe a long-standing interest that started in the past and continues now." },
    { t: "I look forward to hearing from you.", d: "A standard closing phrase in formal English correspondence. It expresses expectation of a reply. 'Look forward to' is followed by a gerund (-ing form)." },
    { t: "I prefer... to... / I would rather... than...", d: "'I prefer [gerund] to [gerund]' and 'I would rather [base verb] than [base verb]' are both used to express preference between two options." },
    { t: "I see your point, but... / That's a good point, however...", d: "Polite disagreement phrases. They acknowledge the other person's idea before introducing a contrasting view. Essential for respectful discussion." },
    { t: "I strongly believe that... / I am not sure, but...", d: "Adverbs like 'strongly' intensify an opinion. 'I am not sure, but...' introduces a tentative opinion with less certainty — useful for hedging." },
    { t: "I would like to... / I would appreciate it if...", d: "Polite request structures used in formal writing. 'Would like to' is more direct; 'would appreciate it if + past subjunctive' is more indirect and very formal." },
    { t: "I'm currently studying...", d: "A phrase using the present continuous to describe your current field or course of study. It indicates an ongoing activity happening now." },
    { t: "In conclusion, / To wrap up, / To summarize...", d: "Closing phrases that signal the end of a presentation. They introduce the final summary or main takeaway for the audience." },
    { t: "In my opinion, / I believe that...", d: "Phrases used to introduce a personal opinion. 'In my opinion' is placed at the start of the sentence. 'I believe that' is followed by a full clause." },
    { t: "In other words, / That is to say...", d: "Paraphrasing markers used in texts to restate a complex idea in simpler terms. Useful for both comprehension and for writing summaries." },
    { t: "internship", d: "Pasantía / práctica profesional: período de trabajo en una empresa u organización, generalmente parte de los estudios, para ganar experiencia práctica. Puede ser pagada o no pagada." },
    { t: "It is related to...", d: "A phrase to show connections between your field and other topics, subjects, or real-world applications. Preposition 'to' is always used after 'related'." },
    { t: "It is used to... / It is designed to...", d: "Passive voice structures to explain the purpose or function of a tool, concept, or procedure. 'Used to' = purpose; 'designed to' = intended function." },
    { t: "It was a challenging / rewarding / eye-opening experience.", d: "Adjective phrases used to evaluate a past experience. 'Challenging' = difficult but worthy. 'Rewarding' = satisfying. 'Eye-opening' = it changed how you see something." },
    { t: "Moving on to... / Now let's look at... / Turning to...", d: "Transition phrases (signposting language) used to move from one section or point to the next in a presentation. They help the audience follow the structure." },
    { t: "My field of study is...", d: "A simple and direct phrase to introduce the area or discipline you are studying. 'Field' means a domain of knowledge or professional activity." },
    { t: "One of the main goals of this field is to...", d: "A structure to describe the purpose or objective of a field of study. 'Goal' = objective or aim. Use 'to + infinitive' after 'goal is'." },
    { t: "opportunity", d: "Oportunidad: circunstancia o momento favorable para hacer algo o alcanzar un objetivo. Muy usado en contextos académicos y profesionales." },
    { t: "Please find attached / I am enclosing...", d: "Phrases used to refer to documents or files attached to an email or letter. 'Please find attached' is common in emails; 'I am enclosing' is used in paper letters." },
    { t: "Professionals in this field...", d: "A phrase to describe what experts or workers in your area of study typically do. It introduces typical tasks, roles, or responsibilities." },
    { t: "skill", d: "Habilidad: capacidad o destreza para hacer algo bien, ya sea técnica (programar, diseñar) o interpersonal (comunicarse, liderar). Puede ser natural o aprendida." },
    { t: "That is why I decided to...", d: "A cause-and-effect connector in the past tense, used to explain the reason for a decision. Links an experience to a conclusion or action." },
    { t: "That's a great question. / Let me think about that for a moment.", d: "Phrases used to buy time and acknowledge a question before answering. They are polite, professional, and natural in English conversations and interviews." },
    { t: "The main idea of the text is...", d: "A phrase used to introduce the central message or topic of a text when summarizing or analyzing it. Equivalent to 'the text is mainly about...'" },
    { t: "This area involves...", d: "Used to explain what activities, skills, or tasks are part of a particular field. 'Involve' is followed by a gerund (verb + -ing)." },
    { t: "This experience taught me...", d: "A past simple structure to explain what you learned from a specific experience. 'Teach' (past: taught) is used with a person as the indirect object." },
    { t: "This project aims to... / The purpose of this project is to...", d: "Phrases to state the objective or goal of a final project in the introduction. Clear purpose statements orient the reader and demonstrate planning." },
    { t: "Throughout this project, I have... / This experience helped me...", d: "Reflective phrases used in conclusions to comment on the learning process. They show metacognitive awareness — the student reflects on what they learned and how." },
    { t: "To improve... I would recommend... / For future work, it would be useful to...", d: "Recommendation structures for the conclusion of a project. They show critical thinking by identifying limitations and proposing next steps." },
    { t: "To sum up / In conclusion / To summarize...", d: "Summary markers used at the end of a text or paragraph to restate the most important points. They signal that the writer is closing or concluding." },
    { t: "Today I am going to talk about... / My presentation focuses on...", d: "Standard opening statements for a formal presentation in English. They signal the topic clearly and orient the audience from the beginning." },
    { t: "volunteer work", d: "Servicio social / trabajo voluntario: actividades realizadas sin recibir pago, generalmente para ayudar a una comunidad u organización. En México, el servicio social universitario es un requisito." },
    { t: "We propose that... / I would like to suggest...", d: "Structures for making a formal proposal or suggestion. 'We propose that + subject + base verb' is for formal proposals; 'I would like to suggest + gerund or that-clause' is common in emails." },
    { t: "What's the process for...?", d: "A question structure to ask about the steps or procedure involved in doing something. 'Process' refers to a series of actions or steps." },
    { t: "When I was..., I...", d: "A structure using the past simple to set a time context and narrate what happened. 'When I was [age/place], I [past simple verb]...'" },
  ],
};
