export const GLOSARIO_PM: Record<string, { t: string; d: string }[]> = {
  "PM-II": [
    { t: "Binomio", d: "Expresión algebraica de dos términos unidos por suma o resta." },
    { t: "Coeficiente", d: "Número que multiplica a la parte literal de un término." },
    { t: "Diferencia de cuadrados", d: "Resultado del producto de binomios conjugados: (a + b)(a − b) = a² − b²." },
    { t: "Ecuación", d: "Igualdad verdadera solo para ciertos valores de la incógnita." },
    { t: "Expresión algebraica", d: "Combinación de números, letras y operaciones." },
    { t: "Factor común", d: "Factor que comparten todos los términos y que se extrae al factorizar." },
    { t: "Factorizar", d: "Escribir una expresión como producto de factores." },
    { t: "Grado", d: "Mayor exponente de la variable en la expresión." },
    { t: "Identidad", d: "Igualdad verdadera para cualquier valor de las letras que contiene." },
    { t: "Igualdad", d: "Relación que afirma que dos expresiones tienen el mismo valor." },
    { t: "Incógnita", d: "Valor desconocido que se busca en una ecuación, representado por una letra." },
    { t: "Lenguaje algebraico", d: "Forma de expresar relaciones y cantidades usando números, letras y signos." },
    { t: "Monomio", d: "Expresión algebraica de un solo término (coeficiente y parte literal)." },
    { t: "Polinomio", d: "Expresión algebraica de varios términos sumados o restados." },
    { t: "Porcentaje", d: "Proporción referida a 100, útil en descuentos y aumentos." },
    { t: "Producto notable", d: "Multiplicación cuyo resultado sigue un patrón conocido y se puede escribir de memoria." },
    { t: "Propiedad de uniformidad", d: "Si a = b, se puede aplicar la misma operación a ambos lados y la igualdad se conserva." },
    { t: "Propiedad distributiva", d: "Regla para multiplicar: cada término de un factor multiplica a cada término del otro." },
    { t: "Término", d: "Cada una de las partes de una expresión separadas por suma o resta." },
    { t: "Términos semejantes", d: "Términos con la misma variable elevada al mismo exponente; pueden sumarse o restarse." },
    { t: "Trinomio", d: "Expresión algebraica de tres términos." },
    { t: "Trinomio cuadrado perfecto", d: "Trinomio que es el cuadrado de un binomio." },
    { t: "Variable", d: "Letra que representa una cantidad que puede cambiar o que es desconocida." },
  ],
  "PM-III": [
    { t: "Aplicación: distancia entre puntos", d: "La distancia entre dos puntos (x₁, y₁) y (x₂, y₂) en el plano se obtiene con el Teorema de Pitágoras: d = √((x₂−x₁)² + (y₂−y₁)²)." },
    { t: "Área de figuras planas", d: "Superficie encerrada. Triángulo: A=(b·h)/2; rectángulo: A=a·b; círculo: A=πr²." },
    { t: "Cateto", d: "Cada uno de los dos lados que forman el ángulo recto en un triángulo rectángulo." },
    { t: "Ceros (raíces) de la función", d: "Valores de x donde f(x) = 0; son los puntos donde la parábola cruza el eje x. Se obtienen resolviendo ax²+bx+c=0." },
    { t: "Circunferencia y círculo", d: "Circunferencia (perímetro): C=2πr. Área del círculo: A=πr²." },
    { t: "Completar el cuadrado", d: "Método algebraico que transforma ax²+bx+c=0 en la forma (x+h)²=k para despejar x." },
    { t: "Congruencia de triángulos", d: "Dos triángulos son congruentes si tienen exactamente la misma forma y el mismo tamaño (todos los lados y ángulos correspondientes son iguales)." },
    { t: "Criterio ALA", d: "Ángulo-Lado-Ángulo: si dos ángulos y el lado comprendido son iguales en ambos triángulos, son congruentes." },
    { t: "Criterio LAL", d: "Lado-Ángulo-Lado: si dos lados y el ángulo comprendido entre ellos son iguales en ambos triángulos, son congruentes." },
    { t: "Criterio LLL", d: "Lado-Lado-Lado: si los tres lados de un triángulo son iguales a los tres lados correspondientes de otro, los triángulos son congruentes." },
    { t: "Desigualdad", d: "Relación que indica que una cantidad es mayor o menor que otra." },
    { t: "Despejar", d: "Aislar la incógnita en un lado de la igualdad mediante operaciones inversas." },
    { t: "Discriminante (Δ)", d: "Expresión Δ = b²−4ac que determina la naturaleza de las raíces de ax²+bx+c=0 sin necesidad de resolverla." },
    { t: "Ecuación cuadrática", d: "Ecuación de la forma ax² + bx + c = 0 con a ≠ 0. También llamada ecuación de segundo grado." },
    { t: "Ecuación lineal", d: "Ecuación en la que la incógnita está elevada a la potencia 1." },
    { t: "Ecuación lineal con dos incógnitas", d: "Igualdad que relaciona dos variables (x, y) elevadas a la potencia 1, por ejemplo y = m·x + b. Su gráfica es una recta." },
    { t: "Eje de simetría", d: "Recta vertical x = −b/(2a) que divide la parábola en dos mitades simétricas." },
    { t: "Factorización", d: "Método para resolver ax² + bx + c = 0 expresándola como producto de dos factores lineales." },
    { t: "Fórmula general (cuadrática)", d: "x = (−b ± √(b²−4ac)) / (2a). Resuelve cualquier ecuación cuadrática." },
    { t: "Función cuadrática", d: "Función de la forma f(x) = ax² + bx + c (a ≠ 0). Su gráfica es una parábola." },
    { t: "Hipotenusa", d: "El lado más largo del triángulo rectángulo; el lado opuesto al ángulo de 90°." },
    { t: "Incógnita", d: "Valor desconocido que se busca en la ecuación." },
    { t: "Inecuación", d: "Desigualdad con una incógnita que se resuelve para hallar los valores que la cumplen." },
    { t: "Intersección con el eje y", d: "El punto donde la parábola cruza el eje y se obtiene evaluando f(0) = c." },
    { t: "Intervalo", d: "Conjunto de todos los números entre dos extremos (o desde uno hacia el infinito)." },
    { t: "Método de eliminación", d: "Sumar o restar las ecuaciones para eliminar una incógnita." },
    { t: "Método de igualación", d: "Despejar la misma incógnita en ambas ecuaciones e igualar los resultados." },
    { t: "Método de sustitución", d: "Despejar una incógnita en una ecuación y sustituirla en la otra." },
    { t: "Ordenada al origen (b)", d: "Valor de y cuando x = 0; el punto (0, b) donde la recta cruza el eje Y." },
    { t: "Parábola", d: "Curva simétrica con forma de 'U' (o '∩') que es la gráfica de toda función cuadrática." },
    { t: "Pendiente (m)", d: "Inclinación de la recta: cuánto cambia y por cada unidad que aumenta x (m = subida ÷ avance). Positiva sube, negativa baja, cero es horizontal." },
    { t: "Perímetro de polígonos", d: "Suma de la longitud de todos sus lados. Para un rectángulo: P = 2(a+b); para un cuadrado: P = 4l." },
    { t: "Plano cartesiano", d: "Sistema de dos ejes numéricos perpendiculares (X horizontal, Y vertical) que se cruzan en el origen y permiten ubicar puntos con pares ordenados (x, y)." },
    { t: "Raíces (soluciones) de la ecuación", d: "Los valores de x que satisfacen ax²+bx+c=0. Una ecuación cuadrática tiene a lo más dos raíces reales." },
    { t: "Raíz (cero) de la recta", d: "Valor de x donde y = 0, es decir, el punto donde la recta cruza el eje X: x = −b/m." },
    { t: "Raíz doble", d: "Cuando Δ=0, la única raíz es x=−b/(2a). La parábola correspondiente es tangente al eje x." },
    { t: "Razón de semejanza y áreas", d: "Si la razón de semejanza es k, la razón de los perímetros es k y la razón de las áreas es k²." },
    { t: "Recíproco del Teorema de Pitágoras", d: "Si los lados a, b, c de un triángulo cumplen a² + b² = c², entonces el triángulo es rectángulo." },
    { t: "Recta numérica", d: "Línea donde se ubican los números y se representan las soluciones de una inecuación." },
    { t: "Semejanza de triángulos", d: "Dos triángulos son semejantes si tienen los mismos ángulos y sus lados son proporcionales. La razón de proporcionalidad se llama razón de semejanza." },
    { t: "Sistema de ecuaciones", d: "Conjunto de dos o más ecuaciones que comparten las mismas incógnitas." },
    { t: "Solución", d: "Valor de la incógnita que hace verdadera la ecuación." },
    { t: "Solución de la ecuación", d: "Cualquier pareja (x, y) que cumple la ecuación. Una ecuación con dos incógnitas tiene infinitas: todos los puntos de su recta." },
    { t: "Solución del sistema", d: "Par de valores que satisface todas las ecuaciones a la vez." },
    { t: "Teorema de Pitágoras", d: "En todo triángulo rectángulo, la suma de los cuadrados de los catetos es igual al cuadrado de la hipotenusa: a² + b² = c²." },
    { t: "Triple pitagórico", d: "Conjunto de tres enteros positivos (a, b, c) que satisfacen a² + b² = c²." },
    { t: "Uso práctico del discriminante", d: "Permite clasificar las raíces antes de resolver y anticipar la cantidad de intersecciones de la parábola con el eje x." },
    { t: "Verificación de una raíz", d: "Sustituir la solución encontrada en la ecuación original para confirmar que la igualdad se cumple." },
    { t: "Vértice de la parábola", d: "Punto de máximo (a<0) o mínimo (a>0) de la parábola. Su abscisa es x_v = −b/(2a) y su ordenada es f(x_v)." },
    { t: "Volumen de la esfera", d: "V = (4/3)πr³. La superficie de una esfera es S = 4πr²." },
    { t: "Volumen de pirámide y cono", d: "V = (1/3) × área de la base × altura. Pirámide cuadrada: V=(1/3)l²h; cono: V=(1/3)πr²h." },
    { t: "Volumen de prismas y cilindros", d: "V = área de la base × altura. Prisma rectangular: V=l·a·h; cilindro: V=πr²h." },
    { t: "Δ < 0: sin raíces reales", d: "Cuando el discriminante es negativo, la ecuación no tiene soluciones en los números reales." },
    { t: "Δ = 0: raíz doble (real repetida)", d: "Cuando el discriminante es cero, la ecuación tiene una única raíz real (repetida): x = −b/(2a)." },
    { t: "Δ > 0: dos raíces reales distintas", d: "Cuando el discriminante es positivo, la ecuación tiene exactamente dos soluciones reales y diferentes." },
  ],
  "PM-IV": [
    { t: "Ángulo de referencia", d: "Ángulo agudo (0° a 90°) formado entre el lado terminal del ángulo y el eje x más cercano. Permite calcular razones trigonométricas de cualquier ángulo." },
    { t: "Ángulo en posición estándar", d: "Ángulo con vértice en el origen y lado inicial sobre el eje x positivo. Se mide en sentido antihorario (positivo) o horario (negativo)." },
    { t: "Ángulos notables: 30°, 45°, 60°", d: "Valores exactos: sen(30°)=1/2, cos(30°)=√3/2, tan(30°)=1/√3; sen(45°)=cos(45°)=√2/2, tan(45°)=1; sen(60°)=√3/2, cos(60°)=1/2, tan(60°)=√3." },
    { t: "Caso ambiguo (Ley de Senos)", d: "En el caso LLA con el lado dado opuesto al ángulo dado, puede haber 0, 1 o 2 triángulos solución. Se verifica comparando el lado dado con la altura h = b·sen(A)." },
    { t: "Caso LAL (Ley de Cosenos)", d: "Se conocen dos lados y el ángulo comprendido. Se usa la Ley de Cosenos para hallar el tercer lado y luego la Ley de Senos para los demás ángulos." },
    { t: "Caso LLL (Ley de Cosenos)", d: "Se conocen los tres lados. Se despeja el coseno de cualquier ángulo: cos(C) = (a² + b² − c²)/(2ab)." },
    { t: "Círculo unitario", d: "Circunferencia de radio 1 centrada en el origen del plano cartesiano. Cada punto de la circunferencia es (cos θ, sen θ) para un ángulo θ." },
    { t: "Circunferencia", d: "Conjunto de puntos a la misma distancia (radio r) de un centro; elipse con a = b." },
    { t: "Circunferencia (lugar geométrico)", d: "Conjunto de todos los puntos en el plano que equidistan de un punto fijo llamado centro. Ecuación estándar: (x − h)² + (y − k)² = r²." },
    { t: "Codominio y rango (imagen)", d: "El codominio es el conjunto de posibles salidas. El rango (o imagen) es el conjunto de valores que la función realmente toma." },
    { t: "Coseno (cos θ)", d: "Razón entre el cateto adyacente al ángulo θ y la hipotenusa: cos(θ) = adyacente/hipotenusa." },
    { t: "Desplazamiento vertical y horizontal", d: "g(x) = f(x) + k desplaza f verticalmente k unidades. g(x) = f(x − h) desplaza f horizontalmente h unidades (hacia la derecha si h > 0)." },
    { t: "Dominio", d: "Conjunto de todos los valores de entrada (x) para los cuales la función está definida." },
    { t: "Elipse", d: "Curva cerrada con dos focos; suma de distancias a ambos focos constante." },
    { t: "Estimación", d: "Usar la ecuación del modelo para calcular de forma aproximada un valor buscado." },
    { t: "Foco", d: "Punto especial de una cónica donde se concentran o desde donde se proyectan los rayos." },
    { t: "Forma general de la circunferencia", d: "x² + y² + Dx + Ey + F = 0. Se convierte a forma estándar completando el cuadrado en x y en y." },
    { t: "Forma pendiente-intercepto", d: "y = mx + b, donde m es la pendiente y b es el intercepto en y. Es la forma más usada para graficar una recta." },
    { t: "Forma punto-pendiente", d: "y − y₁ = m(x − x₁), donde (x₁, y₁) es un punto conocido y m es la pendiente. Útil cuando se conoce un punto y la pendiente." },
    { t: "Forma vértice de la parábola", d: "f(x) = a(x − h)² + k, donde (h, k) es el vértice. Facilita identificar transformaciones: desplazamientos y reflexiones." },
    { t: "Fórmula de la distancia", d: "La distancia entre P₁(x₁, y₁) y P₂(x₂, y₂) es d = √((x₂−x₁)² + (y₂−y₁)²). Se deriva del Teorema de Pitágoras." },
    { t: "Función", d: "Relación entre dos conjuntos (dominio y codominio) que asigna a cada elemento del dominio exactamente un elemento del codominio." },
    { t: "Función cuadrática (segundo grado)", d: "Función de la forma f(x) = ax² + bx + c (a ≠ 0). Su gráfica es una parábola que abre hacia arriba (a > 0) o hacia abajo (a < 0)." },
    { t: "Función lineal (primer grado)", d: "Función de la forma f(x) = mx + b donde m ≠ 0. Su gráfica es una recta con pendiente m e intercepto b en el eje y." },
    { t: "Hipérbola", d: "Curva de dos ramas; diferencia de distancias a dos focos constante; modela proporcionalidad inversa." },
    { t: "Identidad pitagórica trigonométrica", d: "sen²(θ) + cos²(θ) = 1 para todo ángulo θ. Se deriva directamente del Teorema de Pitágoras aplicado al triángulo rectángulo unitario." },
    { t: "Interceptos de cónicas", d: "Los interceptos en x se obtienen haciendo y = 0 y resolviendo; los interceptos en y haciendo x = 0. Útiles para graficar." },
    { t: "Ley de Cosenos", d: "c² = a² + b² − 2ab·cos(C). Generaliza el Teorema de Pitágoras. Aplica en casos: LAL (dos lados y el ángulo comprendido) y LLL (tres lados conocidos)." },
    { t: "Ley de Senos", d: "En cualquier triángulo △ABC: a/sen(A) = b/sen(B) = c/sen(C). Aplica en casos: AAL (dos ángulos y un lado) y LLA (caso ambiguo)." },
    { t: "Medición indirecta", d: "Técnica que usa razones trigonométricas para calcular distancias o alturas inaccesibles mediante ángulos de elevación o depresión." },
    { t: "Modelado", d: "Representar un fenómeno real mediante una ecuación matemática." },
    { t: "Notación f(x) y evaluación", d: "f(x) denota el valor de la función en x. Evaluar f(a) significa sustituir x = a en la expresión algebraica." },
    { t: "Parábola", d: "Curva de los puntos equidistantes de un foco y una recta directriz; refleja los rayos paralelos hacia el foco." },
    { t: "Parábola como lugar geométrico", d: "Conjunto de puntos equidistantes de un punto fijo (foco) y una recta fija (directriz). Ecuación con vértice en origen: y = ax² (vertical) o x = ay² (horizontal)." },
    { t: "Pendiente de la recta", d: "m = (y₂−y₁)/(x₂−x₁). Mide la inclinación de la recta. Rectas horizontales tienen m = 0; rectas verticales tienen pendiente indefinida." },
    { t: "Pendiente de una recta", d: "Razón de cambio m = (y₂ − y₁)/(x₂ − x₁). Indica la inclinación y dirección de la recta." },
    { t: "Período de seno y coseno", d: "Las funciones seno y coseno son periódicas con período 360° (2π rad): sen(θ + 360°) = sen(θ) y cos(θ + 360°) = cos(θ)." },
    { t: "Punto medio", d: "El punto medio M entre P₁(x₁, y₁) y P₂(x₂, y₂) es M = ((x₁+x₂)/2, (y₁+y₂)/2)." },
    { t: "Rectas paralelas y perpendiculares", d: "Paralelas: misma pendiente (m₁ = m₂) pero diferente intercepto. Perpendiculares: pendientes son recíprocas negativas (m₁ · m₂ = −1)." },
    { t: "Reflexión y dilatación", d: "g(x) = −f(x) refleja la gráfica respecto al eje x. g(x) = af(x) estira (|a| > 1) o comprime (|a| < 1) verticalmente." },
    { t: "Representación gráfica", d: "Conjunto de puntos (x, f(x)) graficados en el plano cartesiano. Se verifica con la prueba de la línea vertical." },
    { t: "Representación tabular", d: "Tabla de pares (x, f(x)) que muestra correspondencias concretas entre entradas y salidas de la función." },
    { t: "Sección cónica", d: "Las cónicas (circunferencia, elipse, parábola, hipérbola) se obtienen cortando un cono doble con un plano. Representan curvas fundamentales en matemáticas y física." },
    { t: "Seno (sen θ)", d: "Razón entre el cateto opuesto al ángulo θ y la hipotenusa del triángulo rectángulo: sen(θ) = opuesto/hipotenusa." },
    { t: "Signo por cuadrante (regla ACTS)", d: "Cuadrante I: todas positivas. Cuadrante II: solo seno (+). Cuadrante III: solo tangente (+). Cuadrante IV: solo coseno (+). Regla mnemotécnica: 'Todos Saben Tomar Café'." },
    { t: "Tangente (tan θ)", d: "Razón entre el cateto opuesto y el cateto adyacente: tan(θ) = opuesto/adyacente = sen(θ)/cos(θ)." },
    { t: "Triángulo oblicuángulo", d: "Triángulo que no tiene ningún ángulo recto. Puede ser acutángulo (todos los ángulos < 90°) u obtusángulo (un ángulo > 90°). Se resuelve con Ley de Senos o Cosenos." },
    { t: "Valores en los ejes (ángulos cuadrantales)", d: "Para 0°, 90°, 180°, 270°, 360°: los puntos del círculo unitario dan valores exactos sin necesidad de ángulo de referencia." },
    { t: "Vértice y eje de simetría de la parábola", d: "El vértice es el punto de la parábola más cercano a la directriz. El eje de simetría pasa por el vértice y el foco, perpendicular a la directriz." },
  ],
  "PM-V": [
    { t: "Acumulación de cambios continuos", d: "Sumar un ritmo que varía a cada instante para obtener un total." },
    { t: "Análisis completo de una función", d: "Procedimiento: (1) Dominio; (2) Interceptos; (3) f'(x)=0 → puntos críticos, intervalos crecientes/decrecientes; (4) f''(x)=0 → concavidad, puntos de inflexión; (5) Extremos; (6) Gráfica." },
    { t: "Antiderivada (primitiva)", d: "Función F cuya derivada es f, es decir F′(x) = f(x)." },
    { t: "Aplicación: estimación de raíces y potencias", d: "El diferencial permite estimar valores difíciles de calcular a mano: ⁿ√(a+h) ≈ ⁿ√a + h/(n·a^((n−1)/n)), usando la linealización de f(x) = x^(1/n)." },
    { t: "Área bajo la curva", d: "Región encerrada entre la gráfica de una función y el eje X dentro de un intervalo." },
    { t: "Cociente diferencial (incremental)", d: "La expresión [f(a+h) − f(a)]/h, donde h ≠ 0. Representa la pendiente de la recta secante que une (a, f(a)) y (a+h, f(a+h)). El numerador es el incremento de y; el denominador es el incremento de x." },
    { t: "Concavidad", d: "Si f''(x) > 0 en (a,b) → f es cóncava hacia arriba (taza de café boca arriba). Si f''(x) < 0 en (a,b) → f es cóncava hacia abajo (taza invertida)." },
    { t: "Continuidad", d: "Una función es continua si su gráfica se dibuja sin levantar el lápiz." },
    { t: "Continuidad en un intervalo", d: "f es continua en (a, b) si es continua en cada punto del intervalo. En los extremos [a, b] se exige continuidad lateral: desde la derecha en a y desde la izquierda en b." },
    { t: "Continuidad en un punto", d: "f es continua en x = a si: (1) f(a) existe, (2) lim(x→a) f(x) existe, (3) lim(x→a) f(x) = f(a). Las tres condiciones deben cumplirse." },
    { t: "Crecimiento / decrecimiento", d: "Tramo donde la función sube (crece) o baja (decrece) al avanzar en x." },
    { t: "Derivada de aˣ (base arbitraria)", d: "d/dx[aˣ] = aˣ·ln(a), para a > 0 y a ≠ 1." },
    { t: "Derivada de la exponencial natural eˣ", d: "d/dx[eˣ] = eˣ. Con la cadena: d/dx[e^(g(x))] = e^(g(x))·g'(x). La exponencial natural es su propia derivada." },
    { t: "Derivada de la tangente", d: "d/dx[tan x] = sec²x = 1/cos²x. Con la cadena: d/dx[tan(g(x))] = sec²(g(x))·g'(x)." },
    { t: "Derivada del logaritmo", d: "d/dx[ln x] = 1/x (x > 0). d/dx[log_a x] = 1/(x·ln a). Con la cadena: d/dx[ln(g(x))] = g'(x)/g(x)." },
    { t: "Derivada en un punto", d: "f'(a) = lim(h→0) [f(a+h) − f(a)]/h. Es el límite del cociente incremental cuando el incremento h tiende a cero. Representa la tasa de cambio instantánea de f en x = a." },
    { t: "Derivadas de secante, cosecante y cotangente", d: "d/dx[sec x] = sec x·tan x; d/dx[csc x] = −csc x·cot x; d/dx[cot x] = −csc²x." },
    { t: "Derivadas de seno y coseno", d: "d/dx[sin x] = cos x; d/dx[cos x] = −sin x. Con la cadena: d/dx[sin(g(x))] = cos(g(x))·g'(x)." },
    { t: "Diferencial dy", d: "Para y = f(x), el diferencial es dy = f'(x)·dx. Representa el cambio aproximado en y cuando x cambia en dx. Es la 'parte lineal' del cambio real Δy." },
    { t: "Diferencial en contextos de error", d: "Si se mide x con un error Δx, la propagación del error en y = f(x) es aproximadamente |Δy| ≈ |f'(x)|·|Δx|. Útil en laboratorio, topografía, ingeniería." },
    { t: "Discontinuidad de salto", d: "Los límites laterales existen pero son distintos: lim(x→a⁻) f(x) ≠ lim(x→a⁺) f(x). La gráfica presenta un salto finito en x = a." },
    { t: "Discontinuidad esencial (infinita)", d: "Alguno de los límites laterales es ±∞. La gráfica tiene una asíntota vertical en x = a." },
    { t: "Discontinuidad evitable (removible)", d: "El límite lim(x→a) f(x) = L existe, pero f(a) ≠ L o f(a) no está definida. Se puede eliminar redefiniendo f(a) = L." },
    { t: "Error en la aproximación lineal", d: "El error cometido es |Δy − dy| ≈ |f''(c)|·(Δx)²/2. Es de orden cuadrático en Δx: para Δx = 0.1, el error es del orden 0.01, mucho menor." },
    { t: "Forma indeterminada 0/0", d: "Cuando la sustitución directa da 0/0, se recurre a álgebra: factorización, racionalización o simplificación para eliminar el factor que causa la indeterminación." },
    { t: "Función de acumulación", d: "F(x) = ∫ₐˣ f(t) dt: el área acumulada desde a hasta x." },
    { t: "Función de variable real", d: "Regla que asigna a cada número real x un único número real y = f(x)." },
    { t: "Función derivada f'(x)", d: "Cuando se calcula f'(a) para todos los a en el dominio donde el límite existe, se obtiene la función derivada f'(x). Notaciones: f'(x), dy/dx, Df(x)." },
    { t: "Función impar", d: "Cumple f(−x) = −f(x); su gráfica es simétrica respecto al origen." },
    { t: "Función objetivo", d: "La cantidad que se desea maximizar o minimizar en un problema de optimización (área, volumen, costo, beneficio, tiempo, etc.). Se expresa en términos de una o más variables." },
    { t: "Función par", d: "Cumple f(−x) = f(x); su gráfica es simétrica respecto al eje Y." },
    { t: "Gráfica de una función", d: "Conjunto de todos los puntos (x, f(x)) dibujados en el plano cartesiano." },
    { t: "Incremento real Δy", d: "Δy = f(x+Δx) − f(x). Es el cambio exacto en y. Para Δx pequeño, Δy ≈ dy = f'(x)·Δx. El error es de orden (Δx)²." },
    { t: "Integral definida", d: "Área con signo bajo y = f(x) entre x = a y x = b; se escribe ∫ₐᵇ f(x) dx." },
    { t: "Intersección con el eje Y", d: "El punto (0, f(0)) donde la gráfica corta el eje vertical." },
    { t: "Límite al infinito", d: "lim(x→∞) f(x) describe el comportamiento de f(x) cuando x crece sin límite. Para cocientes de polinomios, el grado del numerador vs. denominador determina el resultado." },
    { t: "Límite de una función", d: "lim(x→a) f(x) = L significa que f(x) se acerca arbitrariamente a L cuando x se acerca a a, sin necesariamente llegar a a. El valor f(a) puede ser distinto de L o incluso no estar definido." },
    { t: "Límite trigonométrico fundamental", d: "lim(x→0) sen(x)/x = 1 (x en radianes). Este límite es la base para derivar funciones trigonométricas y no puede obtenerse por sustitución directa (forma 0/0)." },
    { t: "Límites de integración", d: "Los extremos a (inferior) y b (superior) que delimitan el intervalo donde se mide el área." },
    { t: "Límites laterales", d: "El límite por la izquierda lim(x→a⁻) f(x) considera x < a. El límite por la derecha lim(x→a⁺) f(x) considera x > a. El límite bilateral existe solo si ambos son iguales." },
    { t: "Linealización (aproximación lineal)", d: "L(x) = f(a) + f'(a)(x−a). La función lineal L(x) aproxima a f(x) cerca de x = a. Es la recta tangente vista como función aproximante." },
    { t: "Máximo local", d: "Punto donde la función deja de crecer y empieza a decrecer (una cumbre)." },
    { t: "Mínimo local", d: "Punto donde la función deja de decrecer y empieza a crecer (un valle)." },
    { t: "No derivabilidad", d: "Una función no es derivable en x = a si el límite del cociente diferencial no existe. Causas: cúspide (pico angular como en |x|), discontinuidad, o tangente vertical." },
    { t: "Operaciones inversas", d: "Integrar y derivar se deshacen mutuamente, como sumar y restar." },
    { t: "Optimización en economía", d: "Maximizar beneficio B(q) = I(q) − C(q) o minimizar costo promedio C(q)/q. La condición de primer orden B'(q) = 0 da ingreso marginal = costo marginal." },
    { t: "Optimización en geometría", d: "Problemas clásicos: maximizar área dado el perímetro, minimizar perímetro dada el área, maximizar volumen dado el material superficial. La solución suele ser una figura simétrica (cuadrado, cubo, cilindro)." },
    { t: "Procedimiento de optimización", d: "1) Identificar la función objetivo Q. 2) Escribir la restricción y despejar para reducir Q a una sola variable. 3) Calcular Q'=0 → puntos críticos. 4) Verificar si es máximo o mínimo. 5) Responder con unidades." },
    { t: "Prueba de la primera derivada", d: "Si f' cambia de + a − en c → máximo local. Si f' cambia de − a + en c → mínimo local. Si f' no cambia de signo en c → no es extremo (posible inflexión)." },
    { t: "Prueba de la segunda derivada", d: "Si f'(c)=0 y f''(c)>0 → mínimo local (cóncava arriba). Si f'(c)=0 y f''(c)<0 → máximo local (cóncava abajo). Si f''(c)=0 → la prueba es inconclusa." },
    { t: "Punto crítico", d: "Un punto c es crítico de f si f'(c) = 0 o f'(c) no existe. Todo extremo local está en un punto crítico, pero no todo punto crítico es extremo." },
    { t: "Punto de inflexión", d: "Punto (c, f(c)) donde la concavidad cambia de signo. Condición necesaria: f''(c) = 0 o f''(c) no existe, y f'' debe cambiar de signo a ambos lados de c." },
    { t: "Raíz o cero", d: "Valor de x donde f(x) = 0; la gráfica cruza o toca el eje X." },
    { t: "Recta secante vs. recta tangente", d: "La secante cruza la curva en dos puntos (a, f(a)) y (a+h, f(a+h)). Cuando h→0, la secante gira hasta coincidir con la tangente. La derivada es el límite de las pendientes secantes." },
    { t: "Recta tangente", d: "La recta tangente a la gráfica de f en (a, f(a)) tiene pendiente m = f'(a). Su ecuación es y − f(a) = f'(a)(x − a)." },
    { t: "Regla de la cadena", d: "Si h(x) = f(g(x)), entonces h'(x) = f'(g(x))·g'(x). Derivada exterior (evaluada en la interior) por derivada interior." },
    { t: "Regla de la constante multiplicativa", d: "d/dx[c·f(x)] = c·f'(x). Las constantes multiplicativas 'salen' de la derivada." },
    { t: "Regla de la potencia", d: "d/dx[xⁿ] = n·xⁿ⁻¹. Funciona para cualquier exponente real n (entero, fraccionario, negativo)." },
    { t: "Regla de la suma y diferencia", d: "d/dx[f(x) ± g(x)] = f'(x) ± g'(x). La derivada se distribuye sobre la suma y la diferencia." },
    { t: "Regla del cociente", d: "d/dx[f/g] = (f'·g − f·g')/g² (cuando g(x) ≠ 0). Mnemotecnia: 'hi d-lo minus lo d-hi, over hi-hi'." },
    { t: "Regla del producto", d: "d/dx[f·g] = f'·g + f·g'. No es el producto de las derivadas individuales." },
    { t: "Restricción", d: "Condición que limita los valores posibles de las variables (perímetro fijo, presupuesto fijo, volumen fijo, etc.). Se usa para reducir la función objetivo a una sola variable." },
    { t: "Suma de Riemann", d: "Aproximación del área con n rectángulos de ancho (b−a)/n; converge al área exacta cuando n crece." },
    { t: "Sustitución directa", d: "Si f es continua en a (polinomio, función racional sin cero en denominador, etc.), entonces lim(x→a) f(x) = f(a). Es el método más simple." },
    { t: "Teorema del Valor Extremo", d: "Toda función continua en [a, b] alcanza su máximo y mínimo absolutos. Estos ocurren en puntos críticos interiores o en los extremos a y b. Siempre se evalúa f en todos esos candidatos." },
    { t: "Teorema del Valor Intermedio (TVI)", d: "Si f es continua en [a, b] y N está entre f(a) y f(b), entonces existe al menos un c ∈ (a, b) tal que f(c) = N. Garantiza que una función continua no puede saltar valores." },
    { t: "Teorema Fundamental del Cálculo", d: "Conecta derivada e integral: F′(x) = f(x) y ∫ₐᵇ f = F(b) − F(a)." },
    { t: "Variable de integración", d: "La variable muda (t o x) sobre la que se suma dentro de la integral; el resultado no depende de su nombre." },
  ],
  "PM-VI": [
    { t: "Afirmaciones sin contexto y cherry-picking", d: "Reportar solo los datos que apoyan una conclusión (cherry-picking) y omitir los contradictorios es una forma de manipulación estadística. Todo resultado debe presentarse con su contexto completo." },
    { t: "Amplitud de clase", d: "Longitud de cada intervalo: amplitud = límite superior − límite inferior. Idealmente todos los intervalos tienen la misma amplitud para facilitar la comparación." },
    { t: "Área = probabilidad", d: "El área bajo la curva entre a y b es P(a ≤ X ≤ b); el área total vale 1." },
    { t: "Asociación", d: "Existe cuando las proporciones difieren entre grupos; las variables se relacionan." },
    { t: "Axiomas de Kolmogorov", d: "1) P(A) ≥ 0 para todo evento A. 2) P(Ω) = 1 (el espacio muestral tiene probabilidad 1). 3) Si A y B son mutuamente excluyentes: P(A∪B) = P(A) + P(B). Toda la teoría de probabilidad se construye sobre estos tres axiomas." },
    { t: "Coeficiente de correlación (r)", d: "Número entre −1 y +1 que mide fuerza y sentido de la relación lineal." },
    { t: "Coeficiente de variación (CV)", d: "CV = (σ/μ) × 100%. Mide la dispersión relativa respecto a la media, permitiendo comparar la variabilidad de conjuntos con diferentes unidades o medias." },
    { t: "Combinación", d: "Selección en la que no importa el orden: C(n,r)=n!/[r!(n−r)!]." },
    { t: "Complemento (Aᶜ)", d: "Elementos del universal que no están en A." },
    { t: "Con/sin reemplazo", d: "Si el objeto extraído se devuelve (con) o no (sin) antes de la siguiente extracción." },
    { t: "Conjunto", d: "Colección bien definida de objetos llamados elementos." },
    { t: "Conjunto universal (U)", d: "Conjunto de referencia con todos los elementos posibles del problema." },
    { t: "Conjunto vacío (∅)", d: "Conjunto sin elementos; es subconjunto de todos." },
    { t: "Correlación ≠ causalidad", d: "Una relación estadística no prueba que una variable cause la otra." },
    { t: "Correlación negativa", d: "Al crecer una variable, la otra tiende a decrecer (nube descendente, r < 0)." },
    { t: "Correlación positiva", d: "Al crecer una variable, la otra tiende a crecer (nube ascendente, r > 0)." },
    { t: "Correlación vs. causalidad", d: "Dos variables están correlacionadas si tienden a cambiar juntas, pero eso no implica que una cause a la otra. Puede haber una variable confusora (tercera variable) que explique la relación." },
    { t: "Dato y frecuencia", d: "Un dato es la observación individual de una variable. La frecuencia es el número de veces que aparece ese valor (frecuencia absoluta) o su proporción respecto al total (frecuencia relativa)." },
    { t: "Desviación de cada dato respecto a la media", d: "Para cada dato xᵢ, la desviación es (xᵢ − μ). La suma de todas las desviaciones es siempre 0, por lo que se usan las desviaciones al cuadrado para calcular la varianza." },
    { t: "Desviación estándar (σ)", d: "Raíz cuadrada de la varianza: σ = √σ². Se expresa en las mismas unidades que los datos, por lo que es más interpretable que la varianza. Indica cuánto se alejan los datos, en promedio, de la media." },
    { t: "Diagrama de árbol", d: "Representación visual de un experimento en etapas sucesivas. Cada rama muestra un resultado posible con su probabilidad. La probabilidad de una trayectoria es el producto de las probabilidades a lo largo de la rama." },
    { t: "Diagrama de dispersión", d: "Gráfica de puntos (x, y) para visualizar la relación entre dos variables cuantitativas." },
    { t: "Diagrama de Venn", d: "Representación gráfica: rectángulo (U) y óvalos (conjuntos) que se traslapan." },
    { t: "Diseño de encuesta: pasos esenciales", d: "1) Definir el objetivo y la población. 2) Elegir técnica de muestreo y calcular n. 3) Diseñar el cuestionario (preguntas claras, sin sesgo). 4) Recopilar datos. 5) Organizar y analizar. 6) Interpretar y reportar con medidas descriptivas." },
    { t: "Dispersión y confiabilidad de datos", d: "Una desviación estándar pequeña indica que los datos son consistentes y predecibles (alta confiabilidad). Una desviación estándar grande indica alta variabilidad e imprevisibilidad (menor confiabilidad)." },
    { t: "Distribución normal", d: "Modelo de probabilidad en forma de campana simétrica, definido por su media μ y su desviación σ." },
    { t: "Elemento / pertenencia (∈)", d: "Cada objeto del conjunto; ∈ indica que pertenece, ∉ que no." },
    { t: "Estadística descriptiva", d: "Rama de la estadística que organiza, resume y presenta datos mediante tablas, gráficas y medidas numéricas (medias, medianas, desviaciones) sin generalizaciones más allá del conjunto de datos estudiado." },
    { t: "Estadística inferencial", d: "Rama que usa datos de una muestra para hacer generalizaciones (inferencias) sobre una población más amplia, con un nivel de confianza o margen de error asociado." },
    { t: "Evento complementario", d: "El complemento de A (Aᶜ o Ā) es el evento que ocurre cuando A no ocurre. P(Aᶜ) = 1 − P(A). La suma de las probabilidades de un evento y su complemento siempre es 1." },
    { t: "Eventos dependientes", d: "Uno afecta al otro; la probabilidad del segundo cambia según el primero." },
    { t: "Eventos independientes", d: "El resultado de uno no afecta al otro; P(A y B)=P(A)×P(B)." },
    { t: "Eventos independientes vs. dependientes", d: "A y B son independientes si P(A|B) = P(A) (o equivalentemente P(B|A) = P(B), o P(A∩B) = P(A)·P(B)). Son dependientes si la ocurrencia de uno modifica la probabilidad del otro." },
    { t: "Eventos mutuamente excluyentes", d: "Dos eventos son mutuamente excluyentes (o disjuntos) si no pueden ocurrir simultáneamente: A∩B = ∅ → P(A∩B) = 0. No confundir con independencia: los eventos mutuamente excluyentes NO son independientes (si uno ocurre, el otro tiene probabilidad 0)." },
    { t: "Experimento aleatorio y espacio muestral", d: "Un experimento aleatorio es aquel cuyo resultado no puede predecirse con certeza. El espacio muestral (Ω o S) es el conjunto de todos los resultados posibles del experimento." },
    { t: "Factorial (n!)", d: "Producto de todos los enteros positivos del 1 al n." },
    { t: "Histograma", d: "Gráfico de barras adyacentes donde cada barra representa un intervalo de clase. El ancho de la barra es la amplitud del intervalo; la altura es la frecuencia (absoluta o relativa). Visualiza la forma de la distribución." },
    { t: "Independencia", d: "Dos variables son independientes si la distribución de una no cambia según la otra." },
    { t: "Intersección (∩)", d: "Elementos que están en A y en B a la vez («y»)." },
    { t: "Leyes de De Morgan", d: "(A∪B)ᶜ=Aᶜ∩Bᶜ y (A∩B)ᶜ=Aᶜ∪Bᶜ." },
    { t: "Manipulación gráfica", d: "Técnicas que distorsionan la percepción visual de los datos: eje truncado (no inicia en 0), escala no uniforme, gráficas 3D que exageran volúmenes, selección parcial del período mostrado." },
    { t: "Marca de clase (punto medio)", d: "Valor central de cada intervalo, calculado como (límite inferior + límite superior)/2. Se usa como representante del intervalo en cálculos de media y en la construcción del polígono." },
    { t: "Media (μ)", d: "Medida de tendencia central; el centro y eje de simetría de la campana." },
    { t: "Media aritmética (promedio)", d: "Suma de todos los valores dividida entre el número total de datos: x̄ = Σxᵢ/n. Es sensible a valores extremos (atípicos)." },
    { t: "Media ponderada", d: "Promedio donde cada valor xᵢ tiene un peso wᵢ. Fórmula: x̄ₚ = Σ(xᵢ·wᵢ)/Σwᵢ. Usada cuando los datos no tienen igual importancia." },
    { t: "Mediana", d: "Valor central de los datos ordenados de menor a mayor. Con n impar: posición (n+1)/2. Con n par: promedio de los valores en posiciones n/2 y n/2+1." },
    { t: "Medidas de dispersión", d: "Rango, varianza y desviación estándar; cuantifican qué tan esparcidos están los datos." },
    { t: "Medidas de tendencia central", d: "Media, mediana y moda; en una normal perfecta las tres coinciden en μ." },
    { t: "Medidas en datos agrupados", d: "Cuando los datos están en tabla de frecuencias, la media se aproxima con las marcas de clase: x̄ ≈ Σ(mᵢ·fᵢ)/n, donde mᵢ es la marca de clase y fᵢ la frecuencia de cada intervalo." },
    { t: "Moda", d: "Valor o valores que aparecen con mayor frecuencia en el conjunto de datos. Un conjunto puede ser unimodal (una moda), bimodal (dos) o multimodal. Si todos los valores tienen la misma frecuencia, no hay moda." },
    { t: "Muestreo aleatorio simple", d: "Técnica en la que cada elemento de la población tiene la misma probabilidad de ser seleccionado. Se puede realizar mediante números aleatorios, tómbola o tabla de números aleatorios." },
    { t: "Muestreo estratificado", d: "La población se divide en subgrupos homogéneos (estratos: sexo, grado, región) y se selecciona una muestra aleatoria de cada estrato en proporción a su tamaño." },
    { t: "Muestreo por conglomerados", d: "La población se divide en grupos heterogéneos (conglomerados), se seleccionan aleatoriamente algunos conglomerados y se estudian todos sus elementos." },
    { t: "Muestreo sistemático", d: "Se elige aleatoriamente uno de los primeros k elementos y luego se selecciona cada k-ésimo elemento: k = N/n (tamaño de la población entre tamaño de la muestra)." },
    { t: "Normal estándar", d: "La normal con μ = 0 y σ = 1; cualquier normal se convierte a ella con la puntuación z." },
    { t: "Ojiva (polígono de frecuencias acumuladas)", d: "Gráfico que representa la frecuencia acumulada (F) en función del límite superior de cada clase. Tiene forma de S ascendente. Permite leer percentiles directamente." },
    { t: "Permutación", d: "Arreglo en el que importa el orden: P(n,r)=n!/(n−r)!." },
    { t: "Población y muestra", d: "La población es el conjunto completo de individuos u objetos de interés. La muestra es un subconjunto representativo extraído de la población para su estudio." },
    { t: "Polígono de frecuencias", d: "Gráfico de líneas que une los puntos (marca de clase, frecuencia) de cada intervalo. Se cierra en los extremos conectando los puntos en cero para las clases anterior y posterior." },
    { t: "Preguntas para evaluar una estadística", d: "Al ver un dato estadístico, pregunta: ¿Quién lo publicó y tiene intereses? ¿Cuál fue el método de muestreo? ¿El tamaño muestral es adecuado? ¿Los ejes de la gráfica comienzan en 0? ¿Se muestra el margen de error? ¿Es riesgo relativo o absoluto?" },
    { t: "Principio multiplicativo", d: "Si una tarea se hace en etapas, el total de resultados es el producto de las opciones de cada etapa." },
    { t: "Probabilidad clásica", d: "Casos favorables entre casos posibles." },
    { t: "Probabilidad clásica (regla de Laplace)", d: "P(A) = número de casos favorables a A / número total de casos igualmente posibles. Aplica cuando todos los resultados del espacio muestral son equiprobables." },
    { t: "Probabilidad condicionada", d: "P(B|A)=P(A y B)/P(A): probabilidad de B sabiendo que ocurrió A." },
    { t: "Probabilidad condicional P(A|B)", d: "La probabilidad de que ocurra A dado que B ya ocurrió: P(A|B) = P(A∩B)/P(B), siempre que P(B)>0. Actualiza la probabilidad de A con la información de que B es cierto." },
    { t: "Probabilidad frecuentista (empírica)", d: "P(A) ≈ número de veces que ocurrió A / número total de experimentos realizados (frecuencia relativa). Se aproxima al valor teórico conforme n → ∞ (Ley de los Grandes Números)." },
    { t: "Probabilidad subjetiva", d: "Estimación de la probabilidad basada en el juicio personal, experiencia o información experta, sin un espacio muestral simétrico ni experimentos repetidos. Puede variar entre personas." },
    { t: "Puntuación z", d: "z = (x − μ)/σ: número de desviaciones estándar que un valor está por encima (z>0) o por debajo (z<0) de la media." },
    { t: "Rango (recorrido)", d: "La medida de dispersión más sencilla: Rango = valor máximo − valor mínimo. Indica el intervalo total que abarcan los datos, pero es muy sensible a valores atípicos." },
    { t: "Regla de la suma (general)", d: "Para dos eventos cualesquiera A y B: P(A∪B) = P(A) + P(B) − P(A∩B). Si son mutuamente excluyentes (P(A∩B)=0): P(A∪B) = P(A) + P(B)." },
    { t: "Regla del producto (eventos independientes)", d: "Dos eventos A y B son independientes si la ocurrencia de uno no afecta al otro: P(A∩B) = P(A) × P(B). Si no son independientes: P(A∩B) = P(A) × P(B|A)." },
    { t: "Regla empírica 68-95-99.7", d: "En una normal, ~68 % de los datos caen en μ±1σ, ~95 % en μ±2σ y ~99.7 % en μ±3σ." },
    { t: "Riesgo relativo vs. riesgo absoluto", d: "El riesgo relativo (RR) es el cociente entre la probabilidad de un evento en dos grupos. El riesgo absoluto es la diferencia en probabilidades. Un RR grande puede corresponder a un beneficio absoluto pequeño si el riesgo basal es muy bajo." },
    { t: "Sesgo y error muestral", d: "El sesgo es un error sistemático que hace que la muestra no represente bien a la población (pregunta tendenciosa, muestra no representativa). El error muestral es la diferencia aleatoria inevitable entre el estadístico de la muestra y el parámetro de la población." },
    { t: "Sesgo y resistencia de medidas", d: "La media es sensible al sesgo (valores atípicos la distorsionan). La mediana y la moda son resistentes a valores extremos. En distribuciones simétricas las tres coinciden." },
    { t: "Subconjunto (⊆)", d: "B es subconjunto de A si todos los elementos de B están en A." },
    { t: "Tabla de contingencia", d: "Tabla de doble entrada que cruza las categorías de dos variables cualitativas y cuenta los casos." },
    { t: "Tabla de frecuencias", d: "Tabla que organiza datos en clases (intervalos) mostrando: límites del intervalo, marca de clase (punto medio), frecuencia absoluta (f), frecuencia relativa (f/n) y frecuencia acumulada (F)." },
    { t: "Tamaño y representatividad de la muestra", d: "Una muestra debe ser suficientemente grande Y representativa de la población para que las conclusiones sean válidas. Una muestra grande pero sesgada es menos útil que una pequeña y bien seleccionada." },
    { t: "Toma de decisiones basada en datos", d: "Proceso que utiliza análisis estadístico —descriptivo e inferencial— para respaldar decisiones en salud, política, economía, ciencia y vida cotidiana, reduciendo la subjetividad." },
    { t: "Unión (∪)", d: "Elementos que están en A, en B o en ambos («o»)." },
    { t: "Variable cualitativa", d: "Variable que expresa categorías, no números." },
    { t: "Variable cuantitativa", d: "Variable que toma valores numéricos." },
    { t: "Variable estadística", d: "Característica que puede tomar distintos valores en los individuos de una muestra. Se clasifica en cualitativa (categorías) o cuantitativa (números), y esta última en discreta o continua." },
    { t: "Varianza (σ²)", d: "El cuadrado de la desviación estándar; también mide la dispersión de los datos." },
    { t: "Varianza poblacional (σ²)", d: "Promedio de las desviaciones cuadráticas respecto a la media: σ² = Σ(xᵢ − μ)²/N. Se expresa en unidades al cuadrado (por ejemplo, kg², €²)." },
  ],
};
