/**
 * Contenido oficial MCCEMS 2025 — fuente única verbatim.
 *
 * AUTO-GENERADO desde los PDFs oficiales (cen-bachillerato/public/*.pdf) vía
 * pdftotext + extracción verbatim, el 2026-06-07. NO editar a mano: el texto es
 * fiel carácter por carácter al documento oficial (incluidos artefactos de
 * paginación del PDF documentados en 'nota'). Para regenerar, re-extraer y
 * volver a correr el generador.
 *
 * Modelo 2025: cada UAC tiene una asignatura oficial + tema, una meta educativa,
 * y hasta 8 "propósitos formativos" + "contenidos formativos" (no las
 * "progresiones de aprendizaje" del modelo 2022/2023).
 *
 * Datos PUROS: no importa three/@react-three; seguro para el bundle del Worker.
 */

export interface ContenidoUAC2025 {
  /** Código de UAC, p.ej. "CNEYT-I". */
  codigo: string;
  /** Nombre oficial de la asignatura con su número romano. */
  asignaturaOficial: string;
  /** Tema/subtítulo oficial del semestre. */
  temaOficial: string;
  /** Meta educativa verbatim. */
  metaEducativa: string;
  /** Propósitos formativos verbatim, en el orden oficial del documento. */
  propositos: string[];
  /** Contenidos formativos verbatim (un elemento por bloque del documento). */
  contenidos: string[];
  /** Nota de extracción (artefactos del PDF, niveles CEFR, etc.). */
  nota?: string;
}

export const CONTENIDO_2025: ContenidoUAC2025[] = [
  {
    codigo: "LC-I",
    asignaturaOficial: "Lengua y Comunicación I",
    temaOficial: "Leer y escribir para pensarnos juntos",
    metaEducativa: "Identifique la lectura y la escritura como actos colectivos de la experiencia humana útiles en la reflexión, comunicación y problematización del mundo circundante, y utilice algunos rasgos importantes para la escritura de textos propios.",
    propositos: [
      "Reflexiona sobre los vínculos entre la escritura y la lectura para dar sentido a la necesidad humana por comunicar información, ideas, pensamientos u opiniones.",
      "Investiga los gustos y las inclinaciones de las personas de su comunidad escolar respecto de la lectura y la escritura para conocer la diversidad de textos.",
      "Analiza en textos de su elección la información, ideas, pensamientos y opiniones, para comprender la importancia de transmitir con claridad las ideas en textos escritos.",
      "Reconoce los tipos de párrafos a partir de la exploración de diversos textos, para contrastar su estructura y diferenciar sus rasgos.",
      "Identifica información de un texto que lee para resaltar los elementos significativos.",
      "Analiza la concordancia y el uso de conectores a partir de la lectura de un texto para destacar su importancia.",
      "Practica la lectura en voz alta de algunos textos para luego emitir opiniones al respecto.",
      "Identifica las características de una exposición oral para conocer su desarrollo y ponerlo en práctica.",
    ],
    contenidos: [
      "La escritura como posibilidad de desarrollo del pensamiento humano, la empatía, la creación individual y colectiva, la comunicación y la estimulación del avance científico La lectura como experiencia de diálogo entre las personas de diversos contextos sociales, históricos y culturales La lectura como experiencia de placer individual o compartido",
      "Diversidad de textos escritos, soportes y formatos Características generales de los textos escritos Situaciones de la vida cotidiana donde son necesarios los textos escritos",
      "Introducción a las propiedades del texto: Claridad Coherencia Concordancia",
      "Escritura de ideas relacionadas con un tema específico",
      "Párrafos: Descriptivos Narrativos Argumentativos",
      "Escritura de comentarios Puntuación y sintaxis",
      "Ideas principales y secundarias Elementos paratextuales Escritura de ideas principales y secundarias",
      "Concordancia del texto Conectores:",
      "Causales Comparativos Adición",
      "Apreciaciones orales y escritas del texto Elementos paralingüísticos Escritura de elementos paralingüísticos que se perciben cuando comunican sus ideas",
      "Preparación y exposición de un texto de su preferencia",
      "Seleccionar el contenido Decidir la forma (individual o grupal) Establecer las etapas (planeación, acompañamiento y ejecución) Asignar los recursos (diapositivas, mapas mentales)",
    ],
  },
  {
    codigo: "LC-II",
    asignaturaOficial: "Lengua y Comunicación II",
    temaOficial: "Libertad para imaginar, poder para comunicar",
    metaEducativa: "Reconozca sus capacidades creativas y comunicativas en la elaboración de textos libres.",
    propositos: [
      "Narra situaciones de su historia de vida para compartir cómo han dejado una huella en su persona.",
      "Escribe un texto descriptivo o narrativo de su autoría.",
      "Identifica características lingüísticas a partir de la lectura de narrativas populares.",
      "Comprende, a partir de la exploración de diversos textos, la relevancia de personajes y escenarios en la narrativa popular, para desarrollar elementos que pueda integrar en sus propios escritos.",
      "Distingue los temas y las ideas centrales y secundarias en las narrativas populares, para reconocer su papel en las distintas expresiones.",
      "Reescribe un texto para integrar los elementos lingüísticos y narrativos que considere pertinentes.",
      "Colabora en el análisis de textos para conocer, aprovechar o corregir los procedimientos narrativos.",
      "Integra prácticas de lectura, escritura y oralidad en proyectos creativos para presentar el texto elaborado.",
    ],
    contenidos: [
      "Narración y descripción de situaciones vividas Diálogo y reflexión colectiva a partir de ideas prioritarias y secundarias de una narración",
      "Organización de ideas para la escritura de un texto Delimitación del sentido comunicativo en un texto Ficción y realidad",
      "Narrativas populares de acuerdo con el contexto e interés estudiantil Narración y oralidad Adaptaciones modernas de narrativas tradicionales:",
      "Cómics Creepypastas Cuentos Obras de teatro Leyendas y mitos Reescritura de alguna narración breve",
      "Caracterización de personajes y sus relaciones, de inicio a fin, en la narrativa Clasificación de los personajes Construcción de personajes de las narrativas",
      "Diferencia entre tema e idea principal Ideas secundarias y su función en la narrativa Comparación de un mismo tema en diferentes narrativas populares Palabras o frases que marcan jerarquías en la narración: conectores textuales",
      "Trama, conflicto o situación Narración:",
      "Realista Fantástica Histórica Autobiográfica Tonos narrativos: Humorístico Dramático Irónico",
      "Intercambio de experiencias Diálogo entre pares Construcción de textos narrativos colaborativos",
      "Análisis del pódcast u otro formato digital Elementos sobre guion (texto creado), grabación y edición Elementos extralingüísticos Producción y ejecución de un guion narrativo",
    ],
  },
  {
    codigo: "LC-III",
    asignaturaOficial: "Lengua y Comunicación III",
    temaOficial: "Describir culturas, apropiarse de las palabras",
    metaEducativa: "Explore y experimente con los movimientos y géneros literarios como manifestaciones culturales, para apropiarse de los diferentes elementos discursivos.",
    propositos: [
      "Analiza la información extraída de un texto para darle sentido desde sus conocimientos previos y toma postura frente a lo expuesto por quien lo escribió.",
      "Reconoce, mediante la lectura, los diversos movimientos literarios para comprender sus particularidades.",
      "Lee los géneros literarios para analizar su papel como forma de involucrar perspectivas de diversa índole.",
      "Identifica lecturas de subgéneros narrativos y sus elementos discursivos a partir de la lectura.",
      "Analiza fragmentos de poesía, a los que da lectura en voz alta, para valorar las figuras retóricas.",
      "Comprende las características de la reseña crítica para realizar una composición basada en uno de los movimientos literarios.",
      "Realiza la exposición oral formal (en un coloquio, un simposio o en foros presenciales o virtuales) de una reseña, para explicar y compartir su análisis crítico.",
    ],
    contenidos: [
      "Sentido global del texto Intención del autor Pensamiento crítico",
      "Conceptualización de literatura (movimientos artísticos):",
      "Barroco Neoclasicismo Romanticismo Realismo Modernismo Vanguardias Realismo mágico Literaturas disidentes y digitales Paráfrasis de una lectura",
      "Géneros literarios: Novela Cuento Poesía Drama Ensayo",
      "Subgéneros narrativos: Suspenso Terror Ciencia ficción Narrativas del cuerpo y autoficción Neorrealismo urbano Literaturas del antropoceno",
      "Género lírico: estructura y subgéneros Figuras retóricas:",
      "Metáfora Hipérbaton Hipérbole Ironía Prosopopeya (personificación) Rima y métrica Análisis de figuras retóricas a partir de la lectura",
      "Características de la idea principal y secundaria Interpretación de información Escritura de una reseña crítica",
      "Organización del coloquio, foro o simposio Planeación de logística (orden, espacio, fecha) Ejecución de presentaciones orales Seguimiento",
    ],
  },
  {
    codigo: "PM-I",
    asignaturaOficial: "Pensamiento Matemático I",
    temaOficial: "Pensamiento aritmético",
    metaEducativa: "Comprenda las matemáticas como expresión del pensamiento humano para aplicar los elementos esenciales de la aritmética y el pensamiento lógico en situaciones de interés.",
    propositos: [
      "Aplica conceptos básicos de lógica matemática en situaciones de su contexto para desarrollar esquemas de razonamiento estructurado.",
      "Comprende el concepto de conteo a partir del análisis de los procesos sociales que llevaron a su desarrollo para aplicarlo en situaciones de interés.",
      "Analiza distintas situaciones cotidianas en donde intervenga el proceso de contar, para comprender la clasificación de los números y realizar operaciones básicas entre números naturales y enteros.",
      "Comprende el concepto de unidad y la relación entre números fraccionarios y enteros, para realizar operaciones con fracciones y porcentajes.",
      "Comprende los conceptos de potenciación y radicación para realizar operaciones con exponentes y radicales.",
      "Comprende el concepto de medición a partir del análisis de los procesos sociales que llevaron a su desarrollo para aplicarlo en situaciones de interés.",
      "Aplica los elementos de la aritmética para resolver cálculos combinados con números reales.",
    ],
    contenidos: [
      "Conceptualización de lógica matemática Tablas de verdad Proposiciones compuestas y operadores lógicos: conjunción (y) y disyunción (o) Proposiciones condicionales y bicondicionales",
      "Sistemas de conteo en Mesopotamia, Egipto, América, India y Arabia; importancia del cero en los pueblos olmeca y maya Concepto de número y números naturales Leonardo de Pisa y el sistema numeral indoarábigo Concepto y uso del ábaco",
      "Clasificación de los números reales Operaciones aritméticas y sus operaciones inversas con números enteros Propiedades de las operaciones aritméticas: cerradura, conmutación, asociación y distribución; neutros e inversos aditivo y multiplicativo Factorización de números naturales (teorema fundamental de la aritmética) Máximo común divisor y mínimo común múltiplo",
      "Concepto de unidad y de los números racionales como fracciones (estructura) Equivalencias entre fracciones y entre números enteros y fracciones Simplificación de fracciones Proporción, proporción inversa y porcentaje",
      "Componentes de una potencia Operaciones con potenciación (reglas) Explicación de exponentes negativos como el inverso multiplicativo de la base Operaciones con exponentes (reglas) Definición de raíz cuadrada (enunciación de sus partes) y radicando diferente de 2 Raíz cuadrada como inverso de potencias de números positivos y cancelación de potencias y raíces",
      "Concepto de medición Unidades de medida y sistema internacional Magnitudes y notación científica Razón y proporción",
      "Técnicas para la resolución de operaciones combinadas (jerarquía de operaciones) Uso de símbolos para resolución de operaciones combinadas (paréntesis, corchetes, llaves y puntos) Resolución de restas de números enteros como la suma con el opuesto de otro Operaciones combinadas con adición, sustracción, multiplicación, división, potencias y raíces",
    ],
  },
  {
    codigo: "PM-II",
    asignaturaOficial: "Pensamiento Matemático II",
    temaOficial: "Introducción al álgebra",
    metaEducativa: "Entienda al lenguaje algebraico como un medio de representación de situaciones cotidianas y escolares para estimular el pensamiento abstracto.",
    propositos: [
      "Representa operaciones aritméticas utilizadas en situaciones de interés, mediante letras y símbolos, para comprender el lenguaje algebraico.",
      "Comprende la clasificación de las expresiones algebraicas para construir e identificar monomios, binomios, trinomios y polinomios.",
      "Aplica la aritmética y el manejo del álgebra para realizar operaciones con monomios y binomios, referentes a situaciones de interés, a partir del análisis de sus componentes.",
      "Aplica la aritmética y el manejo del álgebra para realizar operaciones con trinomios y polinomios, referentes a situaciones de interés, a partir del análisis de sus componentes.",
      "Aplica el álgebra en situaciones de interés para comprender su relevancia en otras áreas del conocimiento, fenómenos naturales o en distintas esferas de la vida humana.",
      "Comprende el concepto de ecuación a partir de las igualdades matemáticas para encontrar el valor de una incógnita utilizando situaciones de interés.",
    ],
    contenidos: [
      "Definición de: suma, producto, razón, cociente, diferencia y residuo Símbolos y letras utilizados en el lenguaje algebraico Concepto de incógnita Términos y expresiones algebraicas Representación de expresiones de lenguaje común a expresiones algebraicas",
      "Clasificación de expresiones algebraicas (monomio, binomio, trinomio y polinomio) Componentes de un monomio: coeficiente, variable, exponente positivo y grado Representación de situaciones reales con monomios y polinomios",
      "Suma, resta, multiplicación y división con monomios Aplicación de las reglas de los exponentes y los signos Aplicación de operaciones con fracciones Factorización de monomios Binomio y trinomio simple",
      "Suma, resta, multiplicación y división con polinomios Aplicación de las reglas de los exponentes y los signos Aplicación de operaciones con fracciones Productos notables Factorización de polinomios Trinomio cuadrado perfecto",
      "Cálculo de un presupuesto personal (ingresos, gastos, ahorros, etc.) Ajuste de proporciones en recetas según número de personas Hallar precios finales aplicando porcentajes y ecuaciones en compras con descuento",
      "Concepto de igualdad e identidad algebraica Relaciones de igualdad entre números reales Propiedades de igualdad: reflexiva, simétrica, transitiva, uniformidad",
    ],
  },
  {
    codigo: "PM-III",
    asignaturaOficial: "Pensamiento Matemático III",
    temaOficial: "Pensamiento algebraico e introducción a geometría plana",
    metaEducativa: "Aplique el lenguaje algebraico como herramienta para describir situaciones de la realidad y expresar relaciones matemáticas, y mediante procesos de intuición y razonamiento, logre explicar y resolver problemas.",
    propositos: [
      "Aplica la aritmética y el manejo del álgebra para encontrar el valor de una incógnita en ecuaciones lineales que refieran a situaciones de interés.",
      "Aplica la aritmética y el manejo del álgebra para resolver ecuaciones lineales con dos incógnitas que refieran a situaciones de interés.",
      "Aplica la aritmética, el manejo del álgebra y el método gráfico para resolver sistemas de ecuaciones lineales que refieran a situaciones de interés",
      "Aplica la aritmética y el manejo del álgebra para resolver ecuaciones cuadráticas que refieran a situaciones de interés.",
      "Expresa y resuelve diversas situaciones de interés a través de distintos tipos de ecuaciones para comprender su relevancia en otras áreas del conocimiento, fenómenos naturales o en distintas esferas de la vida humana.",
      "Revisa el teorema del triángulo de Napoleón, considerándolo como un problema-meta para aplicar resultados de la geometría euclidiana.",
    ],
    contenidos: [
      "Concepto de ecuación y sus partes Ecuaciones lineales de primer grado Procedimiento para encontrar el valor de una incógnita Forma estándar de las ecuaciones lineales",
      "Ecuaciones lineales con dos incógnitas Procedimiento para solucionar ecuaciones lineales con dos incógnitas Ecuación de la recta Concepto de plano cartesiano: ejes perpendiculares: horizontal (X) y vertical (Y) Representación gráfica de la ecuación de la recta",
      "Método de igualación Método de sustitución Método de reducción Método gráfico Método por determinantes",
      "Ecuaciones cuadráticas Forma general de la ecuación cuadrática Resolución por método de completar cuadrados Aplicación de fórmula general para ecuaciones cuadráticas (Bhaskara) Representación gráfica",
      "Cálculo de intereses simples y compuestos en finanzas personales Descripción del crecimiento poblacional o propagación de fenómenos (ej. epidemia) Determinar medidas o cantidades de material en proyectos de arquitectura",
      "Introducción a la geometría plana Ángulos, definición, tipos y componentes Teorema de Pitágoras Construcción de triángulos rectángulos Criterios de congruencia y semejanza de triángulos",
    ],
  },
  {
    codigo: "PM-IV",
    asignaturaOficial: "Pensamiento Matemático IV",
    temaOficial: "Trigonometría y geometría analítica",
    metaEducativa: "Resuelva problemas a partir del planteamiento y análisis de funciones trigonométricas, ecuaciones de primer y segundo grado, considerando la pertinencia y conocimiento de las variables y relaciones para explicar una situación o fenómeno.",
    propositos: [
      "Comprende el concepto de recta y de punto para su representación y análisis algebraico.",
      "Analiza la relación entre los lados y los ángulos de un triángulo rectángulo para establecer razones trigonométricas.",
      "Gráfica en el plano cartesiano polinomios de dos variables con coeficientes reales, con el fin de deducir la simetría y la extensión.",
      "Observa el comportamiento de dos variables en relación de proporcionalidad directa para deducir la ecuación de la recta.",
      "Analiza situaciones o fenómenos que involucren en su modelado de funciones cuadráticas para deducir propiedades analíticas de la parábola.",
      "Estudia movimientos circulares, de elipse, y coplanaridad mediante elementos como la ecuación de la circunferencia, las leyes de Kepler, y el pensamiento variacional, para entenderlos.",
      "Aplica conocimientos sobre ecuaciones con dos variables para realizar estimaciones sencillas, para consolidar los aprendizajes.",
    ],
    contenidos: [
      "Concepto de punto Concepto de recta Tipos de recta (tangente, secante) Construcción de figuras Circunferencia",
      "Razones trigonométricas Demostraciones de identidades trigonométricas",
      "Polinomios de dos variables con coeficientes reales Propiedades geométricas (simetría, extensión, etc.)",
      "Comportamiento de dos variables Ecuación de la recta (forma punto-pendiente, pendiente-ordenada al origen, simétrica)",
      "Propiedades analíticas de la parábola Ecuación ordinaria de parábolas verticales y horizontales, con vértice en y fuera del origen. Modelado",
      "Ecuación de la circunferencia Leyes de Kepler Elipse y coplanaridad",
      "Modelado y estimación Aplicación de las secciones cónicas: elipse, parábola, hipérbola y circunferencia",
    ],
  },
  {
    codigo: "PM-V",
    asignaturaOficial: "Pensamiento Matemático V",
    temaOficial: "Cálculo diferencial",
    metaEducativa: "Analice fenómenos donde el cambio es parte central de su estudio con la finalidad de encontrar soluciones óptimas a problemas o situaciones en su entorno u otras áreas del conocimiento.",
    propositos: [
      "Entiende de manera intuitiva los conceptos de variación promedio y variación instantánea para aproximarse al origen del cálculo.",
      "Investiga el origen y evolución del cálculo diferencial y el procedimiento de resolución de una función de la recta tangente a una curva en un punto dado, para la explicación de fenómenos físicos.",
      "Revisa situaciones o fenómenos donde el cambio es la parte central en su estudio y aplica funciones de variable real para modelarlas e identificar simetrías en su representación gráfica.",
      "Comprende el concepto de límite e identifica la continuidad de funciones de variable real para interpretar y modelar fenómenos naturales y sociales.",
      "Practica funciones exponencia les, logarítmicas y trigonométricas para describir sus propiedades y ejemplificar fenómenos en los que son aplicables.",
      "Aplica métodos para derivar funciones lineales y polinomiales, comprendiendo intuitivamente su utilidad como herramienta de análisis en fenómenos de cambio de las ciencias naturales y sociales.",
      "Aplica conocimientos de la derivada para resolver problemas de optimización, o situaciones de su entorno o de otras áreas del conocimiento.",
      "Comprende intuitivamente el Teorema Fundamental del Cálculo como conexión entre derivadas e integrales y su utilidad para analizar fenómenos de acumulación de cambios continuos.",
    ],
    contenidos: [
      "Introducción al cálculo diferencial Inicios del pensamiento variacional Arquímedes y la aproximación al área Paradoja de Zenón Variación promedio e instantánea",
      "Antecedentes históricos y origen del cálculo diferencial Función de la regla tangente y explicación de fenómenos físicos (movimiento)",
      "Funciones de variable real Representación gráfica de funciones de variable real Conceptos de continuidad, crecimiento, decrecimiento, máximos y mínimos Desigualdades",
      "Introducción al concepto de límite Noción intuitiva del límite Propiedades del límite Aplicación del concepto de límite en la continuidad de funciones y el modelado de situaciones reales",
      "Funciones logarítmicas Funciones trigonométricas (seno, coseno, tangente) Propiedades de las funciones trigonométricas (periodicidad, paridad, reciprocidad)",
      "Concepto de la derivada (como límite) Regla de los cuatro pasos Derivada de funciones constantes, lineales y polinomiales Reglas de derivación Análisis de la función derivada Resolución de problemas del entorno aplicando la derivada",
      "Aplicación del cálculo de derivada en distintas áreas del conocimiento o esferas de la vida humana",
      "Integral como función inversa de la derivada Área bajo la curva de una función dentro de un intervalo Representación gráfica",
    ],
    nota: "El propósito 5 reproduce verbatim el artefacto de paginación del PDF: 'funciones exponencia les' (espacio dentro de 'exponenciales').",
  },
  {
    codigo: "PM-VI",
    asignaturaOficial: "Pensamiento Matemático VI",
    temaOficial: "Pensamiento estadístico y probabilístico",
    metaEducativa: "Aplique procedimientos, técnicas y lenguaje matemático para plantear posibles soluciones a problemas derivados de fenómenos naturales o sociales, cuyo comportamiento puede describirse probabilísticamente y contribuir a una toma de decisiones fundamentada.",
    propositos: [
      "Entiende la importancia de la recolección y organización de datos en la elaboración de una muestra aleatoria para la explicación de fenómenos naturales y sociales.",
      "Identifica la incertidumbre como consecuencia de la variabilidad y, a través de simulaciones, plantea una hipótesis de trabajo para obtener la frecuencia y probabilidad de que suceda un evento.",
      "Comprende los conceptos básicos de la teoría de conjuntos para aplicarlos en problemas que le sean presentados.",
      "Selecciona y aplica una técnica de conteo (permutaciones, combinaciones, reemplazo con y sin orden) para calcular probabilidad en eventos simples y apoyar la toma de decisiones.",
      "Analiza los datos categóricos y cuantitativos a través de algunas de sus representaciones, para realizar gráficas de barras (variables cualitativas) o gráficos de puntos e histogramas (variables cuantitativas).",
      "Reconoce algunas problemáticas o fenómenos de interés, para identificar cómo se relacionan entre sí dos o más variables categóricas y dos o más variables cuantitativas.",
      "Extrae información a través del empleo de técnicas de muestreo, valora la importancia de la aleatoriedad al tomar la muestra.",
      "Explica un evento aleatorio cuyo comportamiento puede describirse a través del estudio de la distribución normal, para calcular la probabilidad.",
    ],
    contenidos: [
      "Eventos deterministas y aleatorios Recolección de datos",
      "Simulaciones probabilísticas Equiprobabilidad Frecuencia de los eventos",
      "Concepto general de conjunto Notación e igualdad de conjuntos Subconjunto, conjunto universal y subconjuntos Representación de conjuntos con diagramas de Venn Leyes de Morgan",
      "Técnicas de conteo Probabilidad dependiente e independiente Probabilidad condicionada",
      "Variables estadísticas Gráficas y su interpretación Gráficas y tendencias",
      "Independencia de variables cualitativas Correlación de variables cuantitativas",
      "Población y muestra Fuentes de información (primarias, secundarias y terciarias) Métodos de muestreo: aleatorio simple y sistemático",
      "Distribución normal Medidas de tendencia central Medidas de dispersión",
    ],
  },
  {
    codigo: "IN-I",
    asignaturaOficial: "Inglés I",
    temaOficial: "To be, or not to be, that is the question",
    metaEducativa: "Reconozca y comprenda palabras, frases y expresiones básicas para presentarse, interactuar en el aula y hablar de su entorno inmediato.",
    propositos: [
      "Se presenta y presenta a otras personas en distintos contextos sociales y culturales (saluda y comparte información básica con respeto e inclusión).",
      "Sigue indicaciones y participa en interacciones básicas dentro del aula (pide permiso, aclara dudas y responde a instrucciones).",
      "Identifica y describe objetos y espacios cotidianos del hogar o la escuela (reconoce características como forma, color y tamaño).",
      "Solicita y proporciona información personal básica en contextos escolares y comunitarios (nombre, edad, nacionalidad, teléfono, dirección, correo).",
      "Hace preguntas sencillas para obtener información general (ubicación, horarios).",
      "Describe personas, vestimenta y clima en contextos cotidianos, respetando la diversidad (identificación y ubicación en el entorno).",
      "Expresa gustos y opiniones simples en situaciones cotidianas (habla sobre preferencias y razones de forma empática).",
      "Expresa pertenencia de forma clara y respetuosa (pregunta y responde sobre posesión con el genitivo y los pronombres posesivos).",
    ],
    contenidos: [
      "Verbo to be (forma afirmativa) Pronombres personales Sustantivos: comunes y propios; singulares y plurales Información personal (name, age, nationality) Números cardinales y ordinales Países, nacionalidades Saludos formales e informales",
      "Imperativos (formas afirmativa y negativa) Instrucciones y materiales comunes del aula Verbos frecuentes para actividades escolares (open, close, read, listen) Expresiones útiles para la interacción en clase (How do you say… in English?; May I go to the bathroom? Can you repeat that, please?)",
      "Adjetivos comunes Demostrativos (this, that, these, those) Artículos definidos e indefinidos (the, a, an) Objetos del aula y del hogar Muebles Colores y tamaños",
      "Verbo to be (formas interrogativa y negativa) Preguntas cerradas (yes/no) Adjetivos posesivos (my, your, his, etc.) Números de teléfono y direcciones Alfabeto y deletreo básico (para aclarar su nombre y apellido y dar correo electrónico) Profesiones comunes en contexto (teacher, doctor, cook, driver, etc.) y vocabulario escolar",
      "Preguntas abiertas con wh- (what, where, when, who, how) Verbo to be (revisión de la forma interrogativa) Orden de las palabras en preguntas Preposiciones de tiempo (in, on, at) Años, días y meses Horas y momentos del día Lugares en la comunidad Materias escolares",
      "There is/are Preposiciones de lugar (in, on, under) Características físicas (tall, short, etc.) Lugares de la localidad (park, school, hospital, etc.) Habitaciones de la casa Objetos cotidianos",
      "Revisión de preguntas abiertas con wh- (what, where, when, who, how, why) Uso de favorite en frases simples y uso de prefer (My favorite color is blue; I prefer coffee.) Verbo-ing (gerundio) Intensificadores básicos (very) Adjetivos (big/small, hot/cold) Actividades y eventos comunes (party, study, etc.) Pasatiempos Conjunciones: because, and, so (para responder y dar razones)",
      "Pronombres posesivos (mine, yours, his, hers) Genitivo sajón (‘s) con nombres propios en singular (It’s María’s) Preguntas con whose (Whose pencil is this?) Objetos personales y escolares Colores y materiales Frases simples para indicar pertenencia (It’s Ana’s; It’s mine)",
    ],
    nota: "Nivel A1. Horas/semana: 3 horas.",
  },
  {
    codigo: "IN-II",
    asignaturaOficial: "Inglés II",
    temaOficial: "These are a few of my favorite things",
    metaEducativa: "Intercambie información básica sobre su vida cotidiana y su entorno. Participe en interacciones breves y comprensibles que impliquen rutinas sociales, gustos, descripciones simples y necesidades básicas, en contextos escolares y comunitarios.",
    propositos: [
      "Describe rutinas diarias y actividades cotidianas en casa, la escuela o la comunidad (reconoce acciones frecuentes y las organiza en el tiempo).",
      "Habla sobre lo que hacen otras personas en su tiempo libre y cuándo lo hacen (relaciona actividades con momentos del día o la semana).",
      "Expresa habilidades y pide o da permiso en situaciones cotidianas (reconoce lo que se puede o no se puede hacer).",
      "Describe personas, vestimenta y clima respetando la diversidad y el contexto cultural (usa el lenguaje para observar sin juzgar).",
      "Compara personas, lugares y objetos en contextos cercanos (usa adjetivos para expresar diferencias con respeto).",
      "Pregunta cómo llegar a un lugar y orienta a otras personas en su comunidad (da y sigue referencias para ubicarse).",
      "Participa en intercambios cotidianos sobre necesidades personales o comunitarias (expresa deseos, elige y muestra empatía).",
      "Consolida aprendizajes clave en contextos escolares y comunitarios (revisa estructuras y vocabulario mediante actividades guiadas e integradoras).",
    ],
    contenidos: [
      "Presente simple (forma afirmativa) Adverbios de frecuencia (always, usually, sometimes, never) Verbos comunes en tercera persona (he/she) Rutinas diarias Actividades escolares y del hogar Expresiones de tiempo y horarios",
      "Presente simple (forma negativa) Preguntas con do/does Respuestas cortas Pasatiempos y actividades de ocio Revisión de días de la semana Momentos del día (in the morning, at night)",
      "Can / Can’t (habilidad y permiso) Preguntas y respuestas con can Habilidades comunes (play the guitar, swim, cook) Normas del aula y del hogar Actividades escolares y reglas",
      "Verbo to be (revisión) Have/has Adjetivos posesivos (his, her, their) Present continuous para descripciones Características físicas y vestimenta Clima y estaciones Adjetivos relacionados con el clima y la ropa",
      "Comparativos (bigger than, more interesting than) Adjetivos de una y dos sílabas Personas, lugares y objetos Preferencias y elecciones",
      "Imperativos (go straight, turn left) There is/are (revisión) Preposiciones de movimiento (into, across, next to) Lugares en la ciudad Medios de transporte Indicaciones de ubicación",
      "Would like + sustantivo/infinitivo (I’d like a coffee; I’d like to go to the park.) How much / How many Sustantivos contables e incontables Alimentos y bebidas Precios y cantidades",
      "Presente simple (revisión general: singular vs. plural, primera y tercera persona) Vocabulario complementario Números cardinales (hasta centenas o millares) Números ordinales (1st, 2nd, 3rd...) Deletreo de nombres y palabras comunes",
    ],
    nota: "Nivel A1+. Horas/semana: 3 horas.",
  },
  {
    codigo: "IN-III",
    asignaturaOficial: "Inglés III",
    temaOficial: "What we were, we share",
    metaEducativa: "Participe en intercambios sociales básicos, exprese ideas sobre experiencias personales y amplíe su repertorio comunicativo en contextos cotidianos escolares y comunitarios.",
    propositos: [
      "Habla sobre rutinas pasadas y recientes en la vida cotidiana (describe lo que hizo en días recientes o durante la semana).",
      "Comparte experiencias personales recientes (cuenta qué ha hecho y con quién).",
      "Describe lugares conocidos y actividades que se pueden realizar ahí (da información y recomendaciones básicas).",
      "Habla sobre hábitos, frecuencia y preferencias en la vida cotidiana (compara lo que hacen, eligen o prefieren las personas en diferentes momentos o contextos).",
      "Habla sobre responsabilidades y normas en la casa, la escuela o la comunidad (expresa obligación y prohibición).",
      "Pide, da y entiende instrucciones más completas (orienta a otra persona para hacer algo o llegar a un lugar).",
      "Relata eventos cotidianos y su secuencia (cuenta algo que pasó usando conectores simples).",
      "Consolida lo aprendido mediante actividades significativas y producción guiada (aplica estructuras clave en tareas contextualizadas, orales y escritas).",
    ],
    contenidos: [
      "Pasado simple (verbos regulares) Expresiones de tiempo pasado (yesterday, last week) Actividades diarias Rutinas escolares y del hogar",
      "Presente perfecto (Have/has + past participle) (introducción) para experiencias personales Actividades con amigos, familia o comunidad Eventos escolares o culturales",
      "There is/are (revisión) Can para expresar posibilidad (formas afirmativa y negativa) Preposiciones de lugar (between, next to, in front of, behind) Lugares públicos y naturales (city hall, forest, river, etc.) Actividades recreativas",
      "Adverbios de frecuencia (revisión y expansión: often, sometimes, rarely) Comparativos y superlativos Uso de like + noun / verb-ing (I like music; He likes playing football; They don’t like studying at night.) Comida, música, deportes, uso del tiempo libre",
      "Must / mustn’t Have to / don’t have to Reglas del aula (más complejas) Tareas del hogar Convivencia comunitaria",
      "Imperativos para dar indicaciones (Walk straight until you see the park; Don’t forget to bring your ID; Speak clearly.) Conectores secuenciales (first, then, after that, finally) Indicaciones y procesos simples (recetas, instrucciones digitales, tareas prácticas) Rutinas cotidianas o procedimientos escolares/comunitarios (cómo registrarse, cómo reciclar, cómo usar una aplicación digital escolar)",
      "Pasado simple (verbos irregulares básicos) Conectores narrativos (then, after, later, suddenly) Anécdotas personales Experiencias escolares",
      "Revisión de presente perfecto y pasado simple Uso integrado de conectores, verbos modales y descripciones Textos breves orales y escritos (experiencias, descripciones, recomendaciones) Tareas integradoras (diálogos, cartas, historias cortas)",
    ],
    nota: "Nivel A2. Horas/semana: 3 horas.",
  },
  {
    codigo: "IN-IV",
    asignaturaOficial: "Inglés IV",
    temaOficial: "Should I stay or should I go?",
    metaEducativa: "Fortalezca su autonomía comunicativa en tareas sociales y académicas sencillas, ampliando el uso del lenguaje para describir, explicar, comparar y argumentar ideas simples en contextos cotidianos.",
    propositos: [
      "Describe experiencias pasadas con mayor detalle y conexión (narra lo que ocurrió, dónde y cómo).",
      "Expresa y justifica preferencias de forma respetuosa (compara elecciones personales en contextos cotidianos).",
      "Describe rutinas y hábitos con conciencia del contexto (explica lo que se hace y por qué, en la escuela, la casa o la comunidad).",
      "Solicita y da consejos de forma empática y contextualizada (relacionados con la salud, el estudio o la convivencia diaria).",
      "Habla sobre planes y propósitos personales o comunitarios (expresa lo que se piensa hacer y por qué es importante).",
      "Participa en conversaciones sociales breves con expresiones de cortesía (inicia, mantiene y cierra intercambios breves con respeto y empatía).",
      "Cuenta una anécdota o experiencia significativa (narra de forma clara y organizada lo que se vivió o aprendió).",
      "Consolida estrategias para comprender y expresar ideas de forma clara y estructurada (aplica lo aprendido en tareas orales y escritas con sentido y propósito).",
    ],
    contenidos: [
      "Pasado simple (verbos regulares e irregulares) Conectores de secuencia (first, then, after that, in the end) Viajes, celebraciones comunitarias, eventos escolares",
      "Comparativos y superlativos (revisión y expansión) Conjunciones coordinantes (and / so / but) Ropa, comida, transporte, lugares públicos",
      "Presente simple (revisión completa) Conectores lógicos (because) para expresar causa y justificar ideas (I’m tired because I studied all night.) Hábitos saludables, organización del tiempo, rutinas semanales",
      "Should / shouldn’t Imperativos afirmativos y negativos (revisión) Problemas frecuentes en casa o la escuela Recomendaciones cotidianas",
      "Futuro idiomático (be going to) Futuro simple (Will - introducción) Planes para vacaciones, metas personales y proyectos escolares o comunitarios",
      "Expresiones de cortesía (Would you like to…?; Can I help you…?; That’s great!; Nice to meet you.) Revisión de preguntas y respuestas comunes (How are you?; What do you do?; Do you live around here?; I’m fine, thanks.) Conversaciones en eventos o espacios compartidos (Small talk: The weather is nice today; This place is really interesting; I like your shirt.)",
      "Pasado simple y pasado continuo Uso narrativo de adverbios de tiempo (yesterday, last week, then, after that, later, finally, in the end) y de lugar (here, there, at school, in the kitchen, outside, near: I saw her near the river yesterday) Experiencias reales o imaginadas Historias personales con emociones (happy, excited, nervous, surprised, worried, confused, sad, angry, proud)",
      "Revisión general: presente, pasado, futuro Estructura de párrafos y secuencia de ideas (conectores) Textos funcionales: notas, correos, relatos breves Interacciones extendidas: conversaciones, presentaciones o diálogos guiados",
    ],
    nota: "Nivel A2+. Horas/semana: 3 horas.",
  },
  {
    codigo: "IN-V",
    asignaturaOficial: "Inglés V",
    temaOficial: "We are the champions",
    metaEducativa: "Desarrolle habilidades comunicativas que le permitan comprender y producir textos orales y escritos sobre temas de interés académico, técnico, profesional o comunitario, para fortalecer su agencia lingüística, su pensamiento crítico y su colaboración.",
    propositos: [
      "Explora y describe el área de estudio, ocupación o interés del grupo (introduce el campo o tema, y su relevancia).",
      "Comparte experiencias personales o escolares relacionadas con el campo de estudio elegido (narra por qué le interesa).",
      "Formula y responde preguntas sobre procesos, conceptos o procedimientos básicos (entrevistas simuladas, demostraciones, explicaciones).",
      "Expresa opiniones, preferencias y preocupaciones sobre temas relacionados con el campo de estudio o la comunidad.",
      "Lee y analiza textos breves vinculados con el campo temático o el campo de estudio(comprensión, resumen, opinión).",
      "Redacta textos funcionales para informar, solicitar o proponer acciones (correos, solicitudes, propuestas breves).",
      "Participa en una interacción oral semiestructurada (entrevista, presentación breve, panel).",
      "Explora y describe el área de estudio, ocupación o interés del grupo (el campo o tema y su relevancia).",
    ],
    contenidos: [
      "Presente simple y presente continuo (revisión aplicada) Verbos comunes en contextos específicos: comunitarios, académicos o técnicos Campos como la tecnología, la salud, el medioambiente, etcétera.",
      "Present perfect Tiempos verbales narrativos (past simple, past continuous, present perfect) y conectores de secuencia (first, then, later, finally) Trayectorias escolares, influencias personales, experiencias previas",
      "Formas interrogativas (How does it work?; What happens when...?) Voz pasiva (introducción) Procedimientos, reglas, pasos básicos",
      "Modales para sugerencias, hipótesis o duda (should, could, might) Conectores de causa y efecto (because, so, even though) Temas sociales, dilemas éticos, sostenibilidad, justicia",
      "Estrategias de lectura (skimming, scanning, identifying fact and opinion) Vocabulario técnico básico contextualizado Artículos, infografías, entrevistas, blogs",
      "Registro formal e informal Patrones verbales (want to, plan to, suggest + verb-ing) Textos: notas, correos, formularios, invitaciones, propuestas",
      "Estrategias de participación oral (turn-taking strategies: Can I say something?; What do you think?; Sorry to interrupt, but...) Frases guía para interacción (In my opinion; I agree/disagree; What do you think?) Situaciones prácticas: ferias escolares o eventos comunitarios, debates, juegos de rol",
      "Revisión integrada de estructuras y vocabulario relevante Organización de ideas para presentaciones o informes Productos finales: cartel, miniartículo, podcast, video",
    ],
    nota: "Nivel A2+ / B1. Horas/semana: 5 horas. El propósito formativo 8 del documento oficial repite (con ligera variante) el propósito 1 («Explora y describe el área de estudio, ocupación o interés del grupo»); se transcribe verbatim tal como aparece.",
  },
  {
    codigo: "CD-I",
    asignaturaOficial: "Cultura Digital I",
    temaOficial: "Ciudadanía digital",
    metaEducativa: "Conozca y utilice de manera crítica y responsable el ciberespacio y los distintos recursos digitales, apegándose a su marco normativo para ejercer una ciudadanía digital, acceder al conocimiento y resolver situaciones, fenómenos o problemas de su contexto.",
    propositos: [
      "Identifica el conjunto de elementos físicos que componen un dispositivo electrónico, así como el conjunto de programas, instrucciones y reglas que permiten que funcione, para analizar críticamente su evolución a lo largo del tiempo.",
      "Conoce los requerimientos, tipos de licenciamiento del software y hardware para acceder a servicios tecnológicos, al ciberespacio y a los servicios digitales (licencias de uso privativo y licencias libres).",
      "Analiza de manera crítica el impacto que tienen el uso de las tecnologías digitales —y las políticas relacionadas con la disponibilidad y gestión de la información— en las personas y en las comunidades.",
      "Utiliza herramientas de software libre y experimenta con alternativas a los programas de patente y del software como servicio.",
      "Identifica y aplica la normatividad que regula el uso del ciberespacio y servicios digitales para cuidar su seguridad digital y la de otros.",
      "Utiliza los recursos digitales a su alcance con fines personales, académicos y sociales para interactuar con seguridad y con consideración al medio ambiente.",
      "Reconoce las posibles formas de comprensión y resolución de problemas algorítmicos para desarrollar una estrategia frente a una situación, fenómeno o problemática, utilizando medios tecnológicos y digitales.",
      "Conoce los elementos del lenguaje algorítmico a través de medios digitales, para resolver situaciones, fenómenos o problemáticas presentes en las diferentes asignaturas.",
    ],
    contenidos: [
      "Introducción al hardware y software Historia crítica del desarrollo de tecnología digital Historia del software libre",
      "Licencia GPL (General Public License) Creative Commons y otras licencias libres Conectividad Navegadores Sistemas operativos Niveles de acceso Unidades de medida (velocidad, procesamiento y almacenamiento)",
      "Corporaciones de innovación tecnológica Colonialismo de datos Mercantilización de la atención de las personas usuarias Dependencia tecnológica Desigualdad en el acceso a las tecnologías digitales (socioeconómica, regional o de género)",
      "Las 4 libertades del software libre GNU/ Linux Cultura hacker y el “Hazlo tú mismx” en la tecnología Software libre vs. open source Procesadores de texto, hojas de cálculo y presentaciones electrónicas",
      "Normatividad en el uso del ciberespacio y servicios digitales Privacidad de la información Seguridad digital Protección de datos Uso responsable y ético de la Inteligencia Artificial (IA) Licenciamientos copyleft",
      "Ciudadanía e identidad digital Credenciales de acceso Plataformas de uso cotidiano Contaminación digital y tecnológica",
      "Pasos para solucionar un problema: Identificar el problema por resolver Comprender el problema Analizar alternativas de solución Seleccionar la mejor alternativa de solución Utilizar métodos, técnicas o diagramas de flujo para resolver problemas",
      "Dato Información Variables Constantes Expresiones Operadores lógicos Operaciones relacionales Operadores aritméticos Estructuras condicionales, selectivas y repetitivas",
    ],
  },
  {
    codigo: "CD-II",
    asignaturaOficial: "Cultura Digital II",
    temaOficial: "Aprendizaje individual y colaborativo",
    metaEducativa: "Interactúe con las TICCAD para potenciar su aprendizaje autónomo y colaborativo, de una forma creativa e innovadora, de acuerdo con las características y necesidades de su contexto.",
    propositos: [
      "Utiliza herramientas digitales de una manera innovadora y eficiente para acceder al conocimiento y la experiencia de aprendizaje de las diferentes asignaturas.",
      "Utiliza las TICCAD para interactuar y comunicase con equipos colaborativos de trabajo, e investigar, buscar, discriminar y gestionar información de una situación, fenómeno o problemática personal, social o ambiental.",
      "Aplica técnicas y métodos de investigación digital para buscar, recopilar, extraer, organizar y difundir información de una situación, fenómeno o problemática personal, social o ambiental.",
      "Procesa datos relacionados con una situación, fenómeno o problemática de índole personal, social o ambiental, utilizando herramientas de software que permitan calcular medidas de tendencia central y dispersión, así como generar representaciones gráficas que contribuyan a su análisis.",
      "Utiliza las páginas web para ayudar a difundir información sobre una situación, fenómeno o problemática personal, social o ambiental relacionada con otras asignaturas.",
    ],
    contenidos: [
      "Trabajo colaborativo digital Herramientas de trabajo colaborativo digital libre (Cryptpad, Riseup pad, entre otras)",
      "Tecnologías de Información, Comunicación, Conocimiento y Aprendizajes Digitales de libre acceso (Cryptpad, Riseup pad, entre otras)",
      "Técnicas y métodos de investigación digital (Ciberetnografía, análisis en línea de contenido, grupo focal, entrevista, observación, entre otros)",
      "Licencias permisivas (Cryptpad, Riseup pad, Libre office, entre otras) Software estadístico libre (Jamovi, XLSTAT Free, JASP, entre otros)",
      "Páginas web (que impliquen un diseño simple, por ejemplo: Wordpress, Blogspot, entre otras)",
    ],
  },
  {
    codigo: "CD-III",
    asignaturaOficial: "Cultura Digital III",
    temaOficial: "Uso y difusión del conocimiento",
    metaEducativa: "Interactúe con las TICCAD para ampliar su conocimiento y vincularse con su entorno de una manera crítica, creativa e innovadora.",
    propositos: [
      "Conoce la comunicación digital por su alcance y por sus medios de transmisión, para conectar dispositivos tecnológicos conforme a sus recursos y contexto.",
      "Utiliza herramientas de comunicación digital para difundir información, conocimientos, experiencias y aprendizajes, de acuerdo con su contexto personal, académico, social y ambiental.",
      "Utiliza dispositivos tecnológicos, servicios de difusión y herramientas de software para crear y editar contenido digital, conforme a sus recursos y contextos.",
      "Analiza críticamente las desigualdades de género y socioeconómicas que influyen en las vocaciones del estudiantado en campos relacionados con las tecnologías digitales, con el fin de orientar sus decisiones personales, educativas o laborales.",
    ],
    contenidos: [
      "Comunicación digital directa (Signal, Telegram, WhatsApp, Messenger, Jitsi, Zoom, Google Meet, entre otras). Emisión y descarga continua (PeerTube, YouTube, Twitch, Facebook Gaming, entre otras) Transmisión por secuencias (Wirecast, vMix, OBS Studio, entre otras) Lectura y difusión continuas (Zotero, Evernote, Google Keep, entre otras)",
      "Contenido digital: Didáctico Documental Demostrativo Entretenimiento e informativo",
      "Vocaciones tecnológico-digitales con perspectiva de género y de las desigualdades socioeconómicas:",
      "Inteligencia Artificial Internet de las cosas Industria 4.0 Ciberseguridad Ciencia de datos Robótica Ingeniería computacional, entre otras",
    ],
  },
  {
    codigo: "CH-I",
    asignaturaOficial: "Conciencia Histórica I",
    temaOficial: "Coordenadas de la Historia",
    metaEducativa: "Formule problemas históricos a partir del análisis de los conceptos y categorías fundamentales de la Historia como disciplina, para fortalecer una mirada crítica, situada y reflexiva sobre el pasado, presente, y futuro como parte fundamental de la conciencia histórica.",
    propositos: [
      "Problematiza el pasado, presente y futuro a partir de procesos históricos, con el fin de comprender críticamente su continuidad y cambio.",
      "Establece conexiones entre fenómenos, acontecimientos y procesos de la realidad, con el fin de fortalecer la comprensión del devenir histórico.",
      "Plantea preguntas a partir de problemáticas actuales en diversos contextos, implementando los conceptos y categorías históricas para el análisis.",
      "Reconoce el valor de la diversidad de discursos para la construcción de explicaciones históricas.",
    ],
    contenidos: [
      "La relación entre Historia y Conciencia Histórica Tiempo histórico Tiempo cronológico Espacio histórico Cambio-continuidad",
      "Proceso histórico Causalidad (antecedentes, causas, desarrollo y consecuencias de los hechos) Distinción entre hechos y acontecimientos Lo trascendental en la historia",
      "Identificación de los problemas Delimitación geográfica Situar el problema en el contexto histórico Formulación de preguntas para la indagación histórica",
      "Descripción de datos históricos Organización y análisis de la información Intenciones discursivas sobre el pasado, presente, y futuro",
    ],
  },
  {
    codigo: "CH-II",
    asignaturaOficial: "Conciencia Histórica II",
    temaOficial: "La experiencia histórica",
    metaEducativa: "Descubra su propia historicidad y la del entorno social al que pertenece a partir de distinguir las dimensiones política, económica, social y cultural de los procesos históricos.",
    propositos: [
      "Construye hipótesis para cuestionar las interpretaciones del pasado y su impacto en la construcción de identidades.",
      "Desarrolla explicaciones históricas que guarden relación con sus preguntas para comprender los cambios y continuidades expresadas en los procesos históricos de la humanidad.",
      "Comprende el sentido histórico de los acontecimientos y los significados en diversos contextos, para analizar críticamente las explicaciones históricas.",
      "Construye un vínculo ético con las personas, sujetos históricos, por medio de la reflexión sobre la diversidad de contextos.",
    ],
    contenidos: [
      "La historicidad como categoría analítica Hipótesis histórica Contexto e identidad",
      "Coherencia entre las preguntas y las explicaciones históricas Sujetos históricos Construcción de argumentos históricos Orígenes del conflicto humano",
      "Sentido histórico Dimensiones de los hechos históricos (política, económica, social, cultural)",
      "Ética en la historia Memoria cultural Memoria nacional",
    ],
  },
  {
    codigo: "CH-III",
    asignaturaOficial: "Conciencia Histórica III",
    temaOficial: "Navegar en el tiempo: investigaciones históricas",
    metaEducativa: "Construya narraciones históricas partiendo de la evaluación de fuentes, para problematizar y argumentar sobre los procesos históricos, respondiendo a preguntas de investigación.",
    propositos: [
      "Identifica la diversidad de fuentes históricas para construir explicaciones contextualizadas del pasado, reconociendo el carácter del conocimiento humano.",
      "Examina de manera crítica las evidencias y evalúa su validez, considerando los criterios de procedencia, intencionalidad y contexto, así como el uso ético de la información y los posicionamientos.",
      "Argumenta la validez de sus propias interpretaciones sobre acontecimientos, fenómenos y procesos históricos, mediante el diálogo, la contrastación con otras perspectivas y el uso fundamentado de fuentes.",
      "Elabora argumentos e interpretaciones históricas con base en fuentes variadas y pertinentes, integrando el uso de información.",
    ],
    contenidos: [
      "Distinción entre fuentes por su naturaleza (primaria y secundaria), objetivo (directo e indirecto) y forma (escrita, oral y material) Contraste de fuentes históricas",
      "Recolección de fuentes de acuerdo con la pregunta de investigación La lectura de fuentes históricas: ideas principales, afirmaciones, lenguaje y perspectiva Aplicación de la información de fuentes históricas: autoría, perspectiva, intención, contexto de producción, credibilidad, neutralidad",
      "Contextualización de las fuentes históricas: contraste del contexto de producción y el contexto de recepción de las fuentes históricas Corroboración de fuentes históricas: diversidad narrativa, comparación, tipos de argumentos y evidencias",
      "Proceso narrativo (introducción, desarrollo, conclusiones, uso de evidencias) Proceso de escritura de argumentos (diferenciar postura personal respecto de la fuente)",
    ],
  },
  {
    codigo: "CS-I",
    asignaturaOficial: "Ciencias Sociales I",
    temaOficial: "Estado, ciudadanía y relaciones de poder",
    metaEducativa: "Problematice la ciudadanía como un derecho y su relación con el Estado, así como la construcción de la democracia.",
    propositos: [
      "Comprende la conformación e importancia del concepto de Estado, para repensar la construcción de una ciudadanía crítica y reflexiva.",
      "Analiza el devenir del concepto de ciudadanía, para la conformación de un Estado democrático e incluyente.",
      "Comprende y contrasta las normas sociales para explicar su rol en la vida cotidiana.",
      "Discute y reconoce que la diversidad forma parte del espacio democrático.",
    ],
    contenidos: [
      "Concepto de Estado El Estado como garante de derechos y la perspectiva de derechos humanos Sistema jurídico mexicano",
      "Estado y ciudadanía: Política Civil Económica Cultural",
      "Concepto de ciudadanía, democracia participativa y representativa: espacios para el ejercicio de la ciudadanía Concepto de justicia social Políticas públicas y derechos ciudadanos",
      "Normas sociales, normatividad consuetudinaria como fuente de derechos Contrato social con perspectiva de género e intercultural Funciones y obligaciones de las instituciones federales, estatales y municipales",
      "Inclusión e igualdad, adelantos y pendientes: Acciones afirmativas La edad como clave de discriminación (edadismo)",
      "¿Derechos para todas las personas?: accesos diferenciados y claves de exclusión social",
    ],
  },
  {
    codigo: "CS-II",
    asignaturaOficial: "Ciencias Sociales II",
    temaOficial: "Organización, relaciones sociales y económicas",
    metaEducativa: "Comprenda la forma en que las personas participan en los procesos de organización social, producción y distribución, y analice el origen de las desigualdades económicas y sociales desde su entorno familiar y comunitario.",
    propositos: [
      "Identifica sus necesidades y satisfactores materiales, personales, familiares y los de su comunidad, para debatir sobre las formas en que se organiza la sociedad.",
      "Analiza las características y formas de organización social, para comparar y explicar las relaciones entre personas, grupos, comunidades e instituciones.",
      "Relaciona los procesos y factores de producción, para explicar las formas de distribución desigual de los bienes en la sociedad.",
      "Reconoce y problematiza las relaciones de poder para explicar su función dentro de la diversidad en el funcionamiento de la organización social.",
    ],
    contenidos: [
      "Bienestar social desde el enfoque de los derechos: diferentes formas de satisfacer las necesidades económicas y sociales de las personas Dimensiones de los procesos de desigualdad Necesidades vitales de las personas, y las diferentes formas de satisfacerlas",
      "Formas de organización social: comunitaria, personal y familiar en el contexto económico nacional y local Diversidad cultural y exclusión: la discriminación y el racismo Disidencias, luchas y resistencias Diferentes manifestaciones de la discriminación: subordinación, exclusión y dominación",
      "Contextos locales, nacionales y globales: intercambios desiguales Diferencias regionales, urbano-rural Factores de producción y bienes: tierra, trabajo, capital, organización y tiempo Modos de producción y modelos de desarrollo: procesos económicos, incluyendo trabajos del hogar y cuidados",
      "Instituciones y prácticas sociales (roles sociales) Hegemonía, consensos y negociación Interseccionalidad: clase social, género, raza, origen étnico, orientación sexual, entre otros Desafíos de los procesos demográficos y su impacto en el ámbito económico, social y político Relación sociedad, naturaleza, y degradación ambiental: diferencias regionales y locales",
    ],
  },
  {
    codigo: "CS-III",
    asignaturaOficial: "Ciencias Sociales III",
    temaOficial: "Las dinámicas de la realidad actual: la condición estudiantil al centro",
    metaEducativa: "Analice su papel en contextos de crisis y conflictividad social, para reconocerse con capacidad de transformación.",
    propositos: [
      "Analiza las políticas públicas para explicar las desigualdades, así como las contradicciones y omisiones en la satisfacción de las necesidades materiales y sociales de las personas.",
      "Problematiza el papel de los diferentes actores sociales para explicar, contrastar e interpretar dinámicas y sucesos recientes.",
      "Reflexiona sobre las juventudes en las sociedades actuales, para reconocerse como un agente crítico y de transformación social.",
    ],
    contenidos: [
      "Desigualdad de oportunidades y desigualdad de resultados desde la perspectiva estudiantil -joven-adulto Calidad de vida, bienestar social y bienestar subjetivo Distribución inequitativa del bienestar social en el marco de la movilidad social Causas e impactos multidimensionales de problemáticas sociales: medioambientales, contextos de violencia o diversidades culturales Responsabilidades desde la óptica de diversos actores, con y hacia las juventudes Propuestas y alternativas a las problemáticas abordadas",
      "Énfasis en problematizaciones multidimensionales, colocando al estudiantado en el centro del análisis:",
      "Guerras y conflictos contemporáneos Actuación de organismos e instituciones internacionales Papel del gobierno mexicano en el ámbito internacional Narcotráfico y globalización Migraciones nacionales e internacionales Movilizaciones y justicia social Discriminación, xenofobia y exclusión",
      "Las juventudes: Cultura e identidades Diversidades sexogenéricas Cuerpo y afectividades Redes sociales y brecha digital Derecho a la salud Derecho a la educación Trabajo digno Expresiones y alternativas de participación de las juventudes Políticas públicas y estructura gubernamental",
    ],
  },
  {
    codigo: "PFH-I",
    asignaturaOficial: "Pensamiento Filosófico y Humanidades I",
    temaOficial: "El ejercicio de filosofar y la perspectiva humanista",
    metaEducativa: "Desarrolle la capacidad de formular preguntas filosóficas y de participar en diálogos argumentativos. Para ello, aplica métodos de razonamiento y considera diversos enfoques filosóficos, lo que le permite analizar los desafíos de su entorno desde una perspectiva humanista.",
    propositos: [
      "Reconoce la posibilidad del pensamiento propio a partir de experiencias cotidianas, identificando la práctica filosófica como un modo de problematizar la realidad.",
      "Formula preguntas significativas sobre la vida a partir de un ejercicio filosófico que genere pensamiento crítico, creativo y cuidadoso con el fin de cuestionar lo que comúnmente se considera cierto y explorar diversas respuestas que enriquezcan la visión del mundo.",
      "Analiza la cotidianidad desde las normas, valores, creencias y visiones del mundo, para comprender el sentido de la vida desde distintas perspectivas filosóficas, cuestionando lo dado.",
      "Formula preguntas filosóficas en torno al Conocimiento, Ciencia y grados de Verdad para reconocer su relevancia en la vida cotidiana, desarrollando una comprensión crítica sobre cómo se construye el conocimiento.",
      "Integra la formulación de preguntas para participar con mayor rigor en comunidades de diálogo centradas en problemas filosóficos contemporáneos.",
    ],
    contenidos: [
      "¿Para qué reflexionar sobre el pensamiento? Naturaleza del pensamiento filosófico y perspectiva humanista Introducción a la argumentación filosófica y comunidades de diálogo",
      "¿Por qué y para qué preguntar? Tipos de preguntas Importancia de preguntar Validez de las preguntas La formulación de preguntas filosóficas",
      "¿Qué es un problema filosófico? La experiencia de categorizar y conceptualizar Problemas filosóficos: Realidad, Devenir, Tiempo, Muerte, Libertad, Felicidad, Lenguaje, Sentido de la vida, entre otros",
      "Encuentros y desencuentros entre el conocimiento científico y los saberes sociales y humanísticos Teorías del Conocimiento El Problema de la Verdad Percepción y Razón Posverdad ¿Qué implica interpretar?",
      "¿Para qué dialogamos? Características del diálogo filosófico con perspectiva humanista Actitudes y posturas del diálogo filosófico Reglas para la discusión filosófica La controversia como posibilidad de diálogo filosófico",
    ],
  },
  {
    codigo: "PFH-II",
    asignaturaOficial: "Pensamiento Filosófico y Humanidades II",
    temaOficial: "Las reflexiones filosóficas sobre el Conocer",
    metaEducativa: "Desarrolle la capacidad de problematizar el conocimiento desde una actitud filosófica, asumiendo que conocer implica posicionarse, interpretar y dialogar con distintos marcos de sentido.",
    propositos: [
      "Desarrolla la capacidad de cuestionar y reflexionar sobre los fundamentos del Ser, desplegando un pensamiento crítico acerca de las nociones de Existencia, Ser y Conocimiento, a partir del análisis filosófico-ontológico.",
      "Promueve la comprensión de los fundamentos éticos y su aplicación en la vida cotidiana, fomentando la reflexión crítica sobre dilemas morales y el papel de la Filosofía en la toma de decisiones.",
      "Desarrolla una conciencia crítica en torno a los desafíos éticos que plantean los avances de la ciencia y la tecnología en nuestro país.",
      "Analiza las desigualdades de género desde una mirada filosófica, contrastando diversas perspectivas feministas, para promover la reflexión, el diálogo y la postura política frente a los problemas de género.",
      "Integra saberes filosóficos y perspectivas humanistas para elaborar reflexiones argumentadas sobre los problemas contemporáneos de la Ontología, la Ética, la Bioética, la perspectiva de género y la interculturalidad.",
    ],
    contenidos: [
      "El asombro como origen de la Filosofía Límites del pensamiento filosófico Ontología y Metafísica: ¿qué es el Ser? Realidad y apariencia El ser humano y su existencia",
      "Fundamentos de la Ética Criterios morales y conductuales Fundamentos de la Moral La relación entre Ética y Política La Justicia, la Libertad y la Igualdad Dilemas morales Debates filosóficos",
      "Perspectivas bioéticas Posturas bioéticas sobre la tecnología y la ciencia La inteligencia artificial y los debates sobre la naturaleza del Ser Problemas medioambientales, una postura Ética Filosofía de la animalidad",
      "Feminismos en México Experiencias de desigualdad de género Perspectivas filosóficas sobre la desigualdad de género Subjetividades trans",
      "Construyendo el futuro desde la praxis transformadora Hacia un mundo habitable y justo Perspectiva del Humanismo Mexicano La Ética del pensamiento",
    ],
  },
  {
    codigo: "PFH-III",
    asignaturaOficial: "Pensamiento Filosófico y Humanidades III",
    temaOficial: "Las reflexiones filosóficas sobre el Hacer",
    metaEducativa: "Desarrolle capacidades para analizar, debatir e intervenir en su realidad desde una praxis que problematice el hacer como expresión de autonomía, cuidado y creación. Se promueve una comprensión crítica que posibilite la transformación de la vida en común, que cuestione el poder y abra posibilidades de justicia, de expresión artística y de sentido en la existencia.",
    propositos: [
      "Fortalece con rigor su capacidad argumentativa al aplicar herramientas filosóficas para la construcción, análisis y evaluación de argumentos. Además, propicia espacios de debate en donde ensaya la persuasión argumentativa.",
      "Desarrolla una comprensión crítica sobre los problemas de Filosofía política, a través de un análisis argumentado, para cuestionar las situaciones de la realidad social contemporánea.",
      "Promueve una reflexión crítica sobre la cultura contemporánea y su influencia en la vida cotidiana, a partir del análisis del Arte y las categorías estéticas desde la perspectiva filosófica.",
      "Integra saberes filosóficos y perspectivas humanistas para elaborar reflexiones argumentadas sobre problemas contemporáneos, considerando sus implicaciones éticas, sociales y culturales, reconociéndose como capaz de transformar la realidad a través de los ejercicios de pensamiento.",
    ],
    contenidos: [
      "La lógica del pensamiento Construcción de argumentos filosóficos Persuasión argumentativa Detectar falacias Debate filosófico Filosofías del lenguaje",
      "El origen y las formas de la organización del poder político El Estado Las leyes Análisis biopolítico del Estado Sexo, género, raza, clase, entre otras categorías de sujeción política",
      "Filosofía y Arte Análisis crítico a las categorías estéticas El arte como acto disruptivo Economía y Política del Arte Semiótica del Arte Arte digital Fenomenología de la corporalidad La poética del lenguaje de las artes",
      "¿Para qué sirve el pensamiento complejo? Filosofías de la corporalidad, prácticas de libertad Reflexionar, ¿para qué?",
    ],
    nota: "En el documento oficial los propósitos formativos de PFH-III aparecen intercalados con sus bloques de contenidos formativos (propósito 1 + contenido 1; luego propósitos 2-4 seguidos de los contenidos 2-4). Aquí se separaron en sus arreglos respectivos conservando el orden original.",
  },
  {
    codigo: "CNEYT-I",
    asignaturaOficial: "Ciencias Naturales, Experimentales y Tecnología I",
    temaOficial: "Invitación a la ciencia. Naturaleza de la materia",
    metaEducativa: "Comprenda el carácter creativo, social y colectivo de las ciencias naturales, a través de la apropiación de conceptos que permiten la construcción de explicaciones en torno a la naturaleza intrínseca de la materia. ​",
    propositos: [
      "Reconoce la ciencia como actividad creativa, social y colectiva que involucra el planteamiento de preguntas y la búsqueda de explicaciones sobre fenómenos naturales de su entorno, a través de la experimentación y el análisis.",
      "Comprende que los fenómenos de la naturaleza están interrelacionados, y pueden estudiarse en su conjunto o de forma especializada, para la generación de conocimiento o innovación tecnológica.",
      "Comprende los conceptos de materia, cuerpo, masa y densidad, a partir de los objetos del entorno perceptible, para describirlos y analizarlos.",
      "Comprende los conceptos de sustancia, sustancia pura, elemento compuesto y mezcla, y los aplica para clasificar de forma práctica o analítica distintos tipos de materia y reconocer sus propiedades físicas y químicas.",
      "Comprende el átomo y su composición eléctrica como la partícula microscópica que estructura la materia.",
      "Analiza la formación de iones, moléculas y sustancias, a partir de la unión de dos o más átomos que tienden a la estabilidad energética, para explicar la formación de enlaces químicos.",
      "Explica las propiedades físicas de los estados de agregación de la materia en función del movimiento, separación y fuerzas de atracción o repulsión de las partículas internas, y las vincula con los conceptos de energía cinética, potencial e interna.",
      "Construye explicaciones sobre la naturaleza energética y corpuscular de la materia, y explora aplicaciones tecnológicas relacionadas.",
    ],
    contenidos: [
      "Concepto de ciencia Relatos sobre la historia de los descubrimientos científicos y la ciencia en México El método científico y el conocimiento empírico y tradicional, como formas de comprensión de la naturaleza Medición: concepto de medición, magnitudes y unidad de medida, y su aplicación en las ciencias naturales",
      "Objetivos de estudio de la física, la química y la biología; elementos en común y sus diferencias Ejemplos de ciencias naturales derivadas e interdisciplinares: ecología, ciencias de la Tierra, entre otros Concepto de tecnología y su vínculo con las ciencias naturales",
      "Concepto de materia y cuerpo Concepto de masa como cantidad de materia, unidad de medida y su diferencia con el concepto de peso Concepto de densidad Cálculo de volumen y densidad",
      "Clasificación de la materia Propiedades físicas y químicas de la materia Tipos y características de las mezclas; métodos de separación Cálculo de concentración de disoluciones: masa-masa, masa-volumen, volumenvolumen y partes por millón Clasificación periódica de los elementos",
      "Teoría Atómica: Dalton, Thomson, Rutherford, Bohr y Schrödinger Modelos atómicos y carga eléctrica Número y masa atómica Isótopos Concepto de configuración electrónica y valencia",
      "Enlace químico Electronegatividad y fuerzas intramoleculares Iones y moléculas",
      "Concepto de energía Noción intuitiva de movimiento y conceptos de energía cinética, potencial e interna Teoría cinética de la materia Estados de agregación de la materia y sus cambios (sólidos, líquidos, gases y plasma)",
      "Fenómenos naturales donde participa la actividad eléctrica de la materia Aplicaciones tecnológicas vinculadas con la materia",
    ],
  },
  {
    codigo: "CNEYT-II",
    asignaturaOficial: "Ciencias Naturales, Experimentales y Tecnología II",
    temaOficial: "El poder de la energía",
    metaEducativa: "Comprenda la importancia de la energía para construir explicaciones sobre diversos fenómenos naturales.",
    propositos: [
      "Comprende, a partir del análisis de fenómenos naturales cotidianos, que la energía puede transformarse y transferirse sin destruirse.",
      "Analiza el cambio de posición de un cuerpo al interactuar con otro, para comprender los conceptos de fuerza, movimiento y su relación con la energía mecánica.",
      "Analiza el intercambio de calor entre cuerpos y con el entorno, para comprender su concepto, el de temperatura y su diferencia.",
      "Analiza la interacción entre la energía y la estructura de la materia para comprender las formas de propagación de calor.",
      "Analiza el vínculo entre trabajo mecánico y calor, para comprender el concepto de termodinámica.",
      "Analiza tanto la producción de calor que se genera por procesos mecánicos como las propiedades de un gas ideal, para comprender la primera ley de la termodinámica.",
      "Analiza las aplicaciones de la primera ley de la termodinámica en situaciones de interés, para comprender el concepto de entropía, entalpía, así como la segunda y tercera leyes de la termodinámica.",
      "Construye explicaciones sobre fenómenos naturales en donde intervienen distintos tipos de energía, y explora aplicaciones tecnológicas relacionadas.",
    ],
    contenidos: [
      "Definición de energía Manifestaciones, tipos y transformación de la energía Ley de conservación de la energía Medición de la energía y unidades de medida",
      "Concepto de fuerza Conceptos de posición, movimiento y velocidad Concepto de energía mecánica Cálculo de la energía cinética de un cuerpo o partícula",
      "Calor y temperatura Medición de calor Escalas termométricas absolutas y relativa Equilibrio térmico",
      "Propagación de calor: conducción y convección Transferencia de calor por radiación Conductividad calorífica y capacidad térmica específica",
      "Trabajo mecánico Concepto de termodinámica Vínculo del trabajo mecánico con la termodinámica Equivalencia entre una caloría y un Joule Principio cero de la termodinámica",
      "Dinámica y ecuación de un gas ideal Características de un sistema termodinámico: fronteras, sistemas abiertos o cerrados, y variables de estado Primera ley de la termodinámica",
      "Concepto de Entropía Concepto de Entalpía Segunda y tercera leyes de la termodinámica",
      "Fenómenos naturales donde interviene la energía Aplicaciones tecnológicas de la energía",
    ],
  },
  {
    codigo: "CNEYT-III",
    asignaturaOficial: "Ciencias Naturales, Experimentales y Tecnología III",
    temaOficial: "Nuestro hogar. El sistema terrestre",
    metaEducativa: "Construya explicaciones sobre fenómenos naturales que subyacen a la estructura y función de sistemas o esferas terrestres, y comprenda su importancia para la existencia de la vida en la Tierra, así como la relevancia de las acciones humanas para su cuidado.",
    propositos: [
      "Comprende a la Tierra como un sistema, a partir del análisis de los subsistemas que lo conforman y sus interacciones.",
      "Aplica el conocimiento sobre los estados de agregación y clasificación de la materia; propiedades de los cuerpos y temperatura para explicar las capas, composición e interacción de la hidrósfera y atmósfera.",
      "Analiza los flujos de materia y energía que suceden en los ecosistemas y entre las esferas terrestres, para comprender la importancia de la cadena trófica y el concepto de equilibrio ecológico.",
      "Analiza la estructura de una reacción química para comprender su importancia como proceso de transformación de la materia.",
      "Comprende la importancia del oxígeno para la vida en la Tierra, a partir del análisis del proceso de oxigenación de la atmósfera primitiva y la intervención de los organismos fotosintéticos.",
      "Comprende el proceso general de la fotosíntesis y su importancia para la transferencia de energía en la cadena trófica, así como para la captura del dióxido de carbono y la liberación de oxígeno.",
      "Analiza la dinámica de los subsistemas terrestres y la actividad humana, para comprender el concepto de deterioro ambiental, sus escalas y manifestaciones.",
      "Construye explicaciones sobre innovaciones tecnológicas que utilizan el conocimiento de los subsistemas terrestres para reducir el deterioro ambiental.",
    ],
    contenidos: [
      "La Tierra como sistema y características generales de la hidrósfera, atmósfera, litósfera y la biósfera",
      "Capas y composición química de la hidrósfera y la atmósfera Conceptos involucrados: aire, agua, densidad, presión, temperatura y compuestos químicos Ciclo biogeoquímico del agua Concepto de clima y tiempo atmosférico",
      "Concepto de ecosistema y biodiversidad; relación con la biósfera Componentes bióticos y abióticos del ecosistema Cadena trófica",
      "Biomasa y concepto de productividad primaria Eficiencia ecológica Ciclo biogeoquímico del carbono y aspectos generales de los ciclos del nitrógeno y del fósforo Concepto de equilibrio ecológico",
      "Concepto de reacción química Estructura de una reacción química Ecuación química como forma de representar una reacción Simbología utilizada en fórmulas y reacciones químicas",
      "Composición química de la atmósfera reductora según Oparin-Haldane y las diferencias con la atmósfera actual Ciclo biogeoquímico del oxígeno Formación de óxidos básicos y ácidos",
      "Fotosíntesis: aspectos generales de la fase luminosa y el ciclo de Calvin; ecuación y productos de la fotosíntesis Importancia de los organismos autótrofos para la vida en la Tierra",
      "Concepto de deterioro ambiental Deterioro a nivel global: el calentamiento y su relación con el efecto invernadero y el cambio climático; pérdida de la biodiversidad Deterioro a nivel local: deforestación Contaminación antropogénica, atmosférica y del agua",
      "Restauración de ecosistemas Aplicaciones tecnológicas para la reducción del deterioro ambiental",
    ],
  },
  {
    codigo: "CNEYT-IV",
    asignaturaOficial: "Ciencias Naturales, Experimentales y Tecnología IV",
    temaOficial: "El poder de la química",
    metaEducativa: "Comprenda la química como el estudio de la estructura, propiedades y transformación de la materia, para construir explicaciones sobre diversos fenómenos naturales.",
    propositos: [
      "Comprende las características de las reacciones químicas para clasificarlas e identificarlas en distintos fenómenos naturales de interés.",
      "Aplica el método de tanteo para el balanceo de ecuaciones, como una forma de verificación de la ley de conservación de la masa en las reacciones químicas.",
      "Comprende el concepto de equilibrio químico y la dinámica de las reacciones reversibles e irreversibles, para identificarlas en fenómenos naturales cotidianos o de interés.",
      "Analiza las propiedades físicas y químicas de sustancias ácidas y básicas de interés, así como su diferenciación de acuerdo con el potencial de Hidrógeno, para su identificación en la naturaleza o la vida cotidiana.",
      "Comprende las reacciones químicas de óxido-reducción y combustión para identificar su ocurrencia en la naturaleza, la vida cotidiana, así como su importancia para los seres vivos y la industria.",
      "Comprende la importancia de los compuestos orgánicos para el bienestar humano, así como su estructura, propiedades y nomenclatura para clasificarlos de forma analítica.",
      "Analiza las características y funciones de las biomoléculas, para comprender la importancia de los compuestos orgánicos en los seres vivos.",
      "Comprende los procesos químicos involucrados en la respiración aerobia y anaerobia, para identificar su importancia para los seres vivos y el bienestar humano y desarrollos tecnológicos vinculados.",
    ],
    contenidos: [
      "Características de las reacciones químicas: reactivos y productos; reorganización de átomos; liberación y absorción de energía Energía química Clasificación de las reacciones químicas (exotérmicas, endotérmicas, de síntesis, de descomposición, de desplazamiento y neutralización) Identificación de reacciones químicas en la naturaleza y el desarrollo tecnológico",
      "Ley de conservación de la masa Mol y Masa molar Balanceo de ecuaciones por el método de tanteo Mención de los métodos algebraico y redox para balanceo",
      "Reacciones reversibles e irreversibles Constante y ecuación de equilibrio químico Identificación de reacciones reversibles e irreversibles en la naturaleza",
      "Teorías sobre los ácidos y las bases de Arrhenius, Bronsted-Lowry y Lewis Clasificación de acuerdo con su conductividad Potencial de Hidrógeno (pH) y diferenciación de las sustancias de interés de acuerdo con su valor",
      "Reacciones de oxidación-reducción Reacciones de combustión Reacciones redox y de combustión en la naturaleza y la vida cotidiana Importancia de las reacciones redox y de combustión para los seres vivos y la industria",
      "Importancia de los compuestos orgánicos para el bienestar humano Estructura del carbono y sus tipos de enlace Clasificación de los compuestos orgánicos, grupos funcionales y su nomenclatura Definición de monómeros y polímeros",
      "Funciones y características de los carbohidratos, lípidos, proteínas y ácidos nucleicos Clasificación de los carbohidratos: monosacáridos, disacáridos y polisacáridos Clasificación de los lípidos: aceites, grasas, fosfolípidos y esteroides Aminoácidos esenciales y no esenciales",
      "Aspectos químicos de la glucólisis, ciclo de Krebs y cadena transportadora de electrones Aspectos químicos de la fermentación Desarrollos tecnológicos vinculados con la respiración aerobia y anaerobia",
    ],
  },
  {
    codigo: "CNEYT-V",
    asignaturaOficial: "Ciencias Naturales, Experimentales y Tecnología V",
    temaOficial: "Del átomo al universo. Fuerza y energía",
    metaEducativa: "Cuestione los fenómenos naturales que observa en su realidad inmediata, para la construcción de explicaciones sobre aquellos de carácter mecánico, ondulatorio, óptico y gravitatorio, a partir de su análisis conceptual y matemático.",
    propositos: [
      "Analiza la caída libre de los objetos y el movimiento rectilíneo uniforme de los cuerpos, en presencia y ausencia de la intervención de fuerzas, para construir explicaciones sobre la dinámica del movimiento uniforme y uniformemente acelerado, considerando las dos primeras leyes de Newton.",
      "Construye explicaciones sobre los fenómenos de acción y reacción en la interacción de los cuerpos, a partir de la comprensión de la tercera ley de Newton.",
      "Construye explicaciones sobre la caída libre de objetos con diferente masa y las órbitas de los cuerpos celestes, a partir de la comprensión de la ley de la gravitación universal y el movimiento planetario.",
      "Explica el comportamiento de fenómenos ondulatorios de interés, a partir de la comprensión de las propiedades físicas que los afectan.",
      "Comprende el comportamiento de la luz para explicar fenómenos naturales de carácter óptico.",
      "Analiza el comportamiento de fluidos para comprender sus propiedades físicas.",
      "Comprende los fundamentos del magnetismo y la electricidad, así como su relación para construir explicaciones sobre fenómenos electromagnéticos y explorar aplicaciones tecnológicas vinculadas.",
      "Discute con carácter divulgativo temas de interés de la física moderna y contemporánea.",
    ],
    contenidos: [
      "Concepto de fuerza, sus efectos y manifestaciones en fenómenos naturales cotidianos Concepto de peso, unidad escalar de una fuerza y su diferencia con el concepto de masa Movimiento uniforme y uniformemente acelerado Representación gráfica del movimiento y cálculo de velocidad y aceleración Carácter vectorial de una fuerza. Vectores y parámetros Conceptos de fuerza neta, fricción e inercia Primera y segunda leyes de Newton",
      "Representación vectorial de las fuerzas analizadas Tercera ley de Newton",
      "Fuerza gravitacional: masa, distancia y aceleración Ley de la gravitación universal: ecuación matemática Constante de Cavendish Leyes del movimiento planetario de Kepler",
      "Movimiento ondulatorio Tipos de ondas: armónicas, mecánicas, electromagnéticas, transversales y longitudinales Características de las ondas Velocidad de propagación",
      "Modelo de rayos de luz Reflexión y refracción de la luz Lentes convergentes y divergentes Modelo corpuscular y ondulatorio de la luz",
      "Principio de Pascal y de Arquímedes Tensión superficial y capilaridad Ecuación de continuidad y de Bernoulli Viscosidad",
      "Caracterización de fenómenos eléctricos y magnéticos Campos magnéticos y eléctricos Ley de Ohm-Coulomb Ley de Ampere-Maxwell Ley de Faraday-Henry Aplicaciones tecnológicas vinculadas al electromagnetismo",
      "Divulgación de temas de interés sobre estas sugerencias:",
      "a) Teoría de la relatividad especial y general de Einstein",
      "b) Mecánica cuántica c) Física de partículas y nuclear d) Condensado de Bose-Einstein e) Teleportación y computación cuántica f) Cosmología moderna g) Superconductores",
    ],
  },
  {
    codigo: "CNEYT-VI",
    asignaturaOficial: "Ciencias Naturales, Experimentales y Tecnología VI",
    temaOficial: "¿Qué es la vida? Evolución y diversidad biológica",
    metaEducativa: "Comprenda los rasgos que caracterizan a los seres vivos para construir explicaciones sobre fenómenos naturales, mediados por el funcionamiento celular, la herencia y la evolución biológica.",
    propositos: [
      "Analiza las interacciones entre materia y energía de la Tierra primitiva, así como la estructura de las biomoléculas para comprender la teoría quimiosintética del origen de la vida.",
      "Analiza los procesos históricos que llevaron al descubrimiento de la célula y el desarrollo de la teoría celular como unidad fundamental de los organismos vivos.",
      "Analiza las moléculas orgánicas y organelos celulares para comprender su estructura y función, y reconocer entre células procariotas, eucariotas y su relevancia en la naturaleza o el bienestar humano.",
      "Analiza la estructura molecular y las funciones del ADN y el ARN, así como las características de los cromosomas, para comprender las bases moleculares de la herencia biológica y su utilidad como herramienta de análisis genético.",
      "Identifica las fases de la mitosis y la meiosis para comprender su importancia como mecanismos de reproducción celular, y reconocer los procesos fundamentales de la división celular, así como las situaciones de interés en donde está implicada.",
      "Analiza los mecanismos de herencia biológica e identifica sus manifestaciones en situaciones reales, para comprender la importancia de la genética.",
      "Comprende el proceso de evolución por selección natural, para construir explicaciones sobre la diversidad biológica y las adaptaciones de especies de interés.",
      "Comprende las características que identifican a los seres vivos, para construir explicaciones sobre fenómenos biológicos vinculados a los contenidos formativos, y analiza aplicaciones tecnológicas relacionadas.",
    ],
    contenidos: [
      "Teorías sobre el origen de la vida: creacionismo, generación espontánea y panspermia Concepto de quimiosíntesis Teoría quimiosintética de Oparin-Haldane sobre el origen de la vida Experimento de Miller-Urey",
      "Procesos históricos que llevaron al descubrimiento de la célula Teoría celular",
      "Moléculas orgánicas de las células y su función Organelos celulares, su estructura y su función Diferencias entre células procariotas y eucariotas Teoría endosimbiótica de Lynn Margulis Relevancia de las células procariotas y eucariotas: salud, fotosíntesis, oxigenación, entre otras",
      "Concepto de herencia biológica y gen Estructura del ADN y el ARN; nucleótidos presentes Características de los cromosomas Aplicaciones del ADN como herramienta de análisis genético",
      "Fases e importancia de la mitosis Fases e importancia de la meiosis Importancia de la recombinación genética como factor de biodiversidad Procesos fundamentales de la división celular y situaciones de interés en donde la reproducción celular está implicada",
      "Conceptos de fenotipo y genotipo Leyes de Mendel y cuadros de Punnett Codominancia Teoría cromosómica de la herencia Características debidas a la herencia biológica Concepto de mutación, ejemplos e importancia evolutiva Relevancia de la herencia genética para los seres vivos",
      "Concepto de evolución biológica Teoría evolutiva de Lamarck Teoría evolutiva de Darwin-Wallace por selección natural Aspectos generales de la síntesis evolutiva moderna Diversidad de especies, su relación con la evolución y ejemplos de adaptaciones en las especies actuales",
      "Características que identifican a los seres vivos Fenómenos naturales biológicos vinculados a los temas revisados Desarrollos tecnológicos vinculados a la célula, su estructura y función, a la genética o a la biodiversidad",
    ],
  },
];

export function getContenido2025(codigo: string): ContenidoUAC2025 | undefined {
  return CONTENIDO_2025.find((c) => c.codigo === codigo);
}
